/**
 * Test skeleton for Story 1.4: OpenTelemetry + Prometheus + Loki + Grafana 部署
 *
 * AUTO-GENERATED by QA Test Design (Turing, 2026-05-11). Dev MUST keep every
 * static (Unit) scenario passing; runtime scenarios (Integration / E2E /
 * runtime-only Blind-Spot) stay `test.skip` with a pointer to
 * `docs/dev/logs/1.4-dev-log.md` §E2E.
 *
 * Static scenarios parse:
 *   - Helm values YAML via `yaml`
 *   - Dashboard JSON via `JSON.parse`
 *   - Go source / bash script / READMEs via raw text + regex
 *     (matches the deliverable_bindings convention SM/Architect already use).
 *
 * Skip rules:
 *   - File-presence asserts use `existsSync`; Dev's first deliverable is the
 *     file itself (failing assertion is the gate, not a thrown skeleton).
 *   - True runtime checks (cluster-side, container-side, real timing) live as
 *     `test.skip` with the canonical evidence path in their reason.
 *
 * Test Design: docs/qa/assessments/1.4-test-design-20260511.md
 */

import { describe, expect, test } from 'vitest';
import { readFileSync, statSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml, parseAllDocuments } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..', '..', '..');

const repoPath = (rel: string): string => resolve(REPO_ROOT, rel);
const repoFileExists = (rel: string): boolean => existsSync(repoPath(rel));
const readRepoFile = (rel: string): string =>
  readFileSync(repoPath(rel), 'utf8');
const loadYaml = <T = unknown>(rel: string): T =>
  parseYaml(readRepoFile(rel)) as T;
const loadAllYaml = (rel: string): unknown[] =>
  parseAllDocuments(readRepoFile(rel)).map((d) => d.toJSON());

// Helper: walk a parsed YAML/JSON structure and yield every `[path, value]`
// where `value` is a primitive (string/number/boolean). Used for negative
// "no plaintext password / no ingress block / no Tempo reference" sweeps.
function* walkPrimitives(
  obj: unknown,
  path: string[] = [],
): Generator<[string[], string | number | boolean]> {
  if (obj === null || obj === undefined) return;
  if (typeof obj === 'string' || typeof obj === 'number' || typeof obj === 'boolean') {
    yield [path, obj];
    return;
  }
  if (Array.isArray(obj)) {
    for (let i = 0; i < obj.length; i++) {
      yield* walkPrimitives(obj[i], [...path, String(i)]);
    }
    return;
  }
  if (typeof obj === 'object') {
    for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
      yield* walkPrimitives(v, [...path, k]);
    }
  }
}

// ============================================================
// AC1.A: 观测栈在 staging 集群 monitoring namespace 健康部署
// ============================================================

describe('AC1.A / T1: Chart selection & version pinning', () => {
  test('1.4-UNIT-001: infra/helm/observability/README.md lists all 5 charts', () => {
    const readme = readRepoFile('infra/helm/observability/README.md');
    expect(readme).toMatch(/kube-prometheus-stack/);
    expect(readme).toMatch(/loki/i);
    expect(readme).toMatch(/promtail/i);
    expect(readme).toMatch(/otel-collector|opentelemetry-collector/i);
    expect(readme).toMatch(/jaeger/i);
  });

  test('1.4-UNIT-002: README pins versions per tech-stack.md and observability §11.1', () => {
    const readme = readRepoFile('infra/helm/observability/README.md');
    // Prometheus 2.50+ / Grafana 10+ / Loki 3.x / Promtail 6.x / OTel Collector 0.x / Jaeger 1.55+
    expect(readme).toMatch(/Prometheus[^\n]*2\.50/);
    expect(readme).toMatch(/Grafana[^\n]*10/);
    expect(readme).toMatch(/Loki[^\n]*3\./);
    expect(readme).toMatch(/Promtail[^\n]*6\./);
    expect(readme).toMatch(/Jaeger[^\n]*1\.55/);
    // Collector chart version (0.x) — accept either word "Collector" or "otel-collector"
    expect(readme).toMatch(/(Collector|otel-collector)[^\n]*0\./i);
  });

  test('1.4-UNIT-003: each of the 5 chart sub-dirs has values.yaml + values-staging.yaml', () => {
    const charts = ['kube-prometheus-stack', 'loki', 'promtail', 'otel-collector', 'jaeger'];
    for (const c of charts) {
      expect(repoFileExists(`infra/helm/observability/${c}/values.yaml`)).toBe(true);
      expect(repoFileExists(`infra/helm/observability/${c}/values-staging.yaml`)).toBe(true);
    }
  });

  test('1.4-UNIT-004: README references Architect Round 1 Q1 (Hybrid) and M-2 (Promtail explicit)', () => {
    const readme = readRepoFile('infra/helm/observability/README.md');
    expect(readme).toMatch(/Q1|Hybrid|hybrid/);
    expect(readme).toMatch(/M-?2|Promtail/);
  });
});

describe('AC1.A / T2: kube-prometheus-stack values-staging.yaml', () => {
  const path = 'infra/helm/observability/kube-prometheus-stack/values-staging.yaml';

  test('1.4-UNIT-010: prometheus.prometheusSpec.retention === "24h"', () => {
    const v = loadYaml<any>(path);
    expect(v?.prometheus?.prometheusSpec?.retention).toBe('24h');
  });

  test('1.4-UNIT-011: prometheus.prometheusSpec.storageSpec is empty {} (emptyDir)', () => {
    const v = loadYaml<any>(path);
    const spec = v?.prometheus?.prometheusSpec?.storageSpec;
    expect(spec).toBeDefined();
    // accept either explicit {} or null (yaml empty mapping)
    expect(spec === null || (typeof spec === 'object' && Object.keys(spec).length === 0)).toBe(true);
  });

  test('1.4-UNIT-012: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues === false', () => {
    const v = loadYaml<any>(path);
    expect(v?.prometheus?.prometheusSpec?.serviceMonitorSelectorNilUsesHelmValues).toBe(false);
  });

  test('1.4-UNIT-013: grafana.adminPassword === "" (chart auto-gen secret trigger)', () => {
    const v = loadYaml<any>(path);
    expect(v?.grafana?.adminPassword).toBe('');
  });

  test('1.4-UNIT-014: grafana.persistence.enabled === false', () => {
    const v = loadYaml<any>(path);
    expect(v?.grafana?.persistence?.enabled).toBe(false);
  });

  test('1.4-UNIT-015: grafana.sidecar.dashboards.enabled === true AND label === "grafana_dashboard"', () => {
    const v = loadYaml<any>(path);
    expect(v?.grafana?.sidecar?.dashboards?.enabled).toBe(true);
    expect(v?.grafana?.sidecar?.dashboards?.label).toBe('grafana_dashboard');
  });

  test('1.4-UNIT-016: grafana.sidecar.datasources.enabled === true', () => {
    const v = loadYaml<any>(path);
    expect(v?.grafana?.sidecar?.datasources?.enabled).toBe(true);
  });

  test('1.4-UNIT-017: alertmanager enabled with empty storage spec', () => {
    const v = loadYaml<any>(path);
    expect(v?.alertmanager?.enabled).toBe(true);
    const storage = v?.alertmanager?.alertmanagerSpec?.storage;
    expect(storage === null || (typeof storage === 'object' && Object.keys(storage).length === 0)).toBe(true);
  });

  test('1.4-UNIT-018: nodeExporter.enabled === false (M-3 PSA baseline compatibility)', () => {
    const v = loadYaml<any>(path);
    expect(v?.nodeExporter?.enabled).toBe(false);
  });

  test('1.4-UNIT-019: kube-state-metrics.enabled === true', () => {
    const v = loadYaml<any>(path);
    // kube-state-metrics in kube-prometheus-stack values is keyed with hyphens
    const ksm = v?.['kube-state-metrics'] ?? v?.kubeStateMetrics;
    expect(ksm?.enabled).toBe(true);
  });

  test('1.4-UNIT-020: NO top-level ingress: block (Q5 prohibition)', () => {
    const v = loadYaml<any>(path);
    // Acceptable shapes: missing entirely, or explicitly enabled: false sub-key only.
    // Reject: any nested key under ingress.* that defines hosts / tls / className.
    function violatesIngress(node: any): boolean {
      if (!node || typeof node !== 'object') return false;
      if ('ingress' in node) {
        const ing = node.ingress;
        if (ing && typeof ing === 'object') {
          const keys = Object.keys(ing);
          // tolerate { enabled: false } only
          if (keys.length === 1 && ing.enabled === false) return false;
          if (keys.length === 0) return false;
          // anything else (hosts, tls, ingressClassName, etc.) is a violation
          if (keys.some((k) => k !== 'enabled') || ing.enabled === true) return true;
        }
      }
      for (const child of Object.values(node)) {
        if (violatesIngress(child)) return true;
      }
      return false;
    }
    expect(violatesIngress(v)).toBe(false);
  });

  test('1.4-UNIT-021: NO plaintext *Password value (only adminPassword: "" allowed)', () => {
    const v = loadYaml<any>(path);
    for (const [path, value] of walkPrimitives(v)) {
      const key = path[path.length - 1];
      if (typeof key === 'string' && /[Pp]assword$/.test(key) && typeof value === 'string' && value.length > 0) {
        throw new Error(`Plaintext password found at ${path.join('.')}: ${value.slice(0, 6)}…`);
      }
    }
  });

  test('1.4-UNIT-022: NO persistence.enabled: true / persistence.size non-zero anywhere', () => {
    const v = loadYaml<any>(path);
    function walk(node: any, trail: string[] = []): void {
      if (!node || typeof node !== 'object') return;
      if ('persistence' in node && node.persistence && typeof node.persistence === 'object') {
        if (node.persistence.enabled === true) {
          throw new Error(`persistence.enabled=true at ${trail.join('.')}.persistence`);
        }
        if (node.persistence.size && node.persistence.size !== '0') {
          throw new Error(`persistence.size set at ${trail.join('.')}.persistence`);
        }
      }
      for (const [k, child] of Object.entries(node)) walk(child, [...trail, k]);
    }
    walk(v);
  });

  test('1.4-UNIT-023: NO nodeExporter.enabled: true (M-3 prohibition explicit negative)', () => {
    const text = readRepoFile(path);
    expect(text).not.toMatch(/nodeExporter:\s*\n[^#]*enabled:\s*true/);
  });
});

describe('AC1.A / T3: Loki values-staging.yaml', () => {
  const path = 'infra/helm/observability/loki/values-staging.yaml';

  test('1.4-UNIT-030: deploymentMode === "SingleBinary"', () => {
    const v = loadYaml<any>(path);
    expect(v?.deploymentMode).toBe('SingleBinary');
  });

  test('1.4-UNIT-031: filesystem storage + replication_factor=1', () => {
    const v = loadYaml<any>(path);
    expect(v?.loki?.storage?.type).toBe('filesystem');
    expect(v?.loki?.commonConfig?.replication_factor).toBe(1);
  });

  test('1.4-UNIT-032: singleBinary.persistence disabled + ephemeral-storage cap 2Gi', () => {
    const v = loadYaml<any>(path);
    expect(v?.singleBinary?.persistence?.enabled).toBe(false);
    expect(v?.singleBinary?.resources?.limits?.['ephemeral-storage']).toBe('2Gi');
  });

  test('1.4-UNIT-033: loki.limits_config.retention_period === "48h"', () => {
    const v = loadYaml<any>(path);
    expect(v?.loki?.limits_config?.retention_period).toBe('48h');
  });
});

describe('AC1.A / T3: Promtail values-staging.yaml (Round 1 M-2)', () => {
  const path = 'infra/helm/observability/promtail/values-staging.yaml';

  test('1.4-UNIT-040: clients[0].url points at loki.monitoring SVC', () => {
    const v = loadYaml<any>(path);
    expect(v?.config?.clients?.[0]?.url).toBe(
      'http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push',
    );
  });

  test('1.4-UNIT-041: pipelineStages parses trace_id from JSON logs', () => {
    const text = readRepoFile(path);
    expect(text).toMatch(/pipelineStages|pipeline_stages/);
    expect(text).toMatch(/trace_id/);
  });

  test('1.4-UNIT-042: values do NOT override Promtail to Deployment kind (DaemonSet is chart default)', () => {
    const text = readRepoFile(path);
    expect(text).not.toMatch(/kind:\s*Deployment/);
  });
});

describe('AC1.A / T4: OTel Collector values-staging.yaml', () => {
  const path = 'infra/helm/observability/otel-collector/values-staging.yaml';

  test('1.4-UNIT-050: mode=deployment, replicaCount=1', () => {
    const v = loadYaml<any>(path);
    expect(v?.mode).toBe('deployment');
    expect(v?.replicaCount).toBe(1);
  });

  test('1.4-UNIT-051: receivers.otlp.protocols.grpc.endpoint === "0.0.0.0:4317"', () => {
    const v = loadYaml<any>(path);
    expect(v?.config?.receivers?.otlp?.protocols?.grpc?.endpoint).toBe('0.0.0.0:4317');
  });

  test('1.4-UNIT-052: receivers.otlp.protocols.http.endpoint === "0.0.0.0:4318"', () => {
    const v = loadYaml<any>(path);
    expect(v?.config?.receivers?.otlp?.protocols?.http?.endpoint).toBe('0.0.0.0:4318');
  });

  test('1.4-UNIT-053: exporters.otlp.endpoint targets jaeger-collector (M-5: Jaeger only)', () => {
    const v = loadYaml<any>(path);
    expect(v?.config?.exporters?.otlp?.endpoint).toBe(
      'jaeger-collector.monitoring.svc.cluster.local:4317',
    );
  });

  test('1.4-UNIT-054: NO "tempo" substring anywhere (M-5 negative)', () => {
    const text = readRepoFile(path);
    expect(text.toLowerCase()).not.toContain('tempo');
  });

  test('1.4-UNIT-055: exporters.otlp.tls.insecure === true (intra-cluster)', () => {
    const v = loadYaml<any>(path);
    expect(v?.config?.exporters?.otlp?.tls?.insecure).toBe(true);
  });

  test('1.4-UNIT-056: exporters.prometheus.endpoint === "0.0.0.0:8889"', () => {
    const v = loadYaml<any>(path);
    expect(v?.config?.exporters?.prometheus?.endpoint).toBe('0.0.0.0:8889');
  });

  // Story 9.4 (Q-COLLECTOR) added the PII keep-list + tail-sampling processors to
  // the traces pipeline, superseding the 1.4 `[batch]`-only contract. The scrub
  // MUST precede the sampling decision and the export.
  test('1.4-UNIT-057: pipelines.traces = otlp → redaction → tail_sampling → batch → otlp (9.4)', () => {
    const v = loadYaml<any>(path);
    const t = v?.config?.service?.pipelines?.traces;
    expect(t?.receivers).toEqual(['otlp']);
    expect(t?.processors).toEqual(['redaction', 'tail_sampling', 'batch']);
    expect(t?.exporters).toEqual(['otlp']);
  });

  // Story 9.4 BR-TR-16 — the redaction keep-list is the runtime PII backstop. Its
  // allowed_keys MUST be a superset of the registered §11.5 `he.*` set (9.4-INT-008)
  // and MUST NOT keep client-IP / Authorization / body attributes.
  test('1.4-UNIT-057b: redaction keep-list ⊇ §11.5 he.* and excludes PII (9.4)', () => {
    const v = loadYaml<any>(path);
    const r = v?.config?.processors?.redaction;
    expect(r?.allow_all_keys).toBe(false);
    const keys: string[] = r?.allowed_keys ?? [];
    expect(keys).toContain('he.request_id'); // the only registered §11.5 key today
    for (const banned of ['client.address', 'url.full', 'authorization', 'prompt']) {
      expect(keys).not.toContain(banned);
    }
  });

  // Story 9.4 Q-COLLECTOR — ERROR/non-OK traces retained at 100% via tail sampling.
  test('1.4-UNIT-057c: tail_sampling keeps ERROR status at 100% (9.4)', () => {
    const v = loadYaml<any>(path);
    const policies = v?.config?.processors?.tail_sampling?.policies ?? [];
    const errPolicy = policies.find((p: any) => p?.type === 'status_code');
    expect(errPolicy?.status_code?.status_codes).toEqual(['ERROR']);
  });

  test('1.4-UNIT-058: pipelines.metrics = otlp → batch → prometheus', () => {
    const v = loadYaml<any>(path);
    const m = v?.config?.service?.pipelines?.metrics;
    expect(m?.receivers).toEqual(['otlp']);
    expect(m?.processors).toEqual(['batch']);
    expect(m?.exporters).toEqual(['prometheus']);
  });

  test('1.4-UNIT-059: ServiceMonitor template/manifest exists and targets :8889 /metrics', () => {
    const candidates = [
      'infra/helm/observability/otel-collector/templates/servicemonitor.yaml',
      'infra/helm/observability/otel-collector/servicemonitor.yaml',
    ];
    const present = candidates.find(repoFileExists);
    expect(present, `expected one of: ${candidates.join(', ')}`).toBeDefined();
    const text = readRepoFile(present!);
    expect(text).toMatch(/kind:\s*ServiceMonitor/);
    expect(text).toMatch(/8889|prometheus/);
  });
});

describe('AC1.A / T5: Jaeger values-staging.yaml', () => {
  const path = 'infra/helm/observability/jaeger/values-staging.yaml';

  test('1.4-UNIT-070: provisionDataStore.cassandra=false AND elasticsearch=false', () => {
    const v = loadYaml<any>(path);
    expect(v?.provisionDataStore?.cassandra).toBe(false);
    expect(v?.provisionDataStore?.elasticsearch).toBe(false);
  });

  test('1.4-UNIT-071: storage.type === "memory"', () => {
    const v = loadYaml<any>(path);
    expect(v?.storage?.type).toBe('memory');
  });

  test('1.4-UNIT-072: collector.service.otlp.grpc.port === 4317', () => {
    const v = loadYaml<any>(path);
    expect(v?.collector?.service?.otlp?.grpc?.port).toBe(4317);
  });

  test('1.4-UNIT-073: query.service.type === "ClusterIP" (Q5 no public expose)', () => {
    const v = loadYaml<any>(path);
    expect(v?.query?.service?.type).toBe('ClusterIP');
  });

  test('1.4-UNIT-074: agent.enabled === false (OTel Collector replaces jaeger-agent)', () => {
    const v = loadYaml<any>(path);
    expect(v?.agent?.enabled).toBe(false);
  });

  test('1.4-UNIT-075: NO "tempo" substring anywhere (M-5 negative)', () => {
    const text = readRepoFile(path);
    expect(text.toLowerCase()).not.toContain('tempo');
  });
});

describe('AC1.A / T7: observability-rbac.yaml', () => {
  const path = 'infra/k8s-base/observability-rbac.yaml';

  test('1.4-UNIT-080: ClusterRole prometheus-scraper exists with services/endpoints/pods/nodes verbs', () => {
    const docs = loadAllYaml(path) as any[];
    const cr = docs.find(
      (d) => d?.kind === 'ClusterRole' && d?.metadata?.name === 'prometheus-scraper',
    );
    expect(cr).toBeDefined();
    const allRules = (cr.rules ?? []).flatMap((r: any) => r.resources ?? []);
    expect(allRules).toEqual(expect.arrayContaining(['services', 'endpoints', 'pods', 'nodes']));
  });

  test('1.4-UNIT-081: ClusterRoleBinding for prometheus-scraper → kube-prometheus-stack-prometheus SA', () => {
    const docs = loadAllYaml(path) as any[];
    const crb = docs.find(
      (d) =>
        d?.kind === 'ClusterRoleBinding' &&
        d?.roleRef?.name === 'prometheus-scraper',
    );
    expect(crb).toBeDefined();
    expect((crb.subjects ?? []).some((s: any) => s.name === 'kube-prometheus-stack-prometheus')).toBe(true);
  });

  test('1.4-UNIT-082: ClusterRole otel-collector-k8sattrs with pods/namespaces/nodes verbs', () => {
    const docs = loadAllYaml(path) as any[];
    const cr = docs.find(
      (d) => d?.kind === 'ClusterRole' && d?.metadata?.name === 'otel-collector-k8sattrs',
    );
    expect(cr).toBeDefined();
    const allRules = (cr.rules ?? []).flatMap((r: any) => r.resources ?? []);
    expect(allRules).toEqual(expect.arrayContaining(['pods', 'namespaces', 'nodes']));
  });

  test('1.4-UNIT-083: ClusterRoleBinding for otel-collector-k8sattrs', () => {
    const docs = loadAllYaml(path) as any[];
    const crb = docs.find(
      (d) =>
        d?.kind === 'ClusterRoleBinding' &&
        d?.roleRef?.name === 'otel-collector-k8sattrs',
    );
    expect(crb).toBeDefined();
  });

  test('1.4-UNIT-084: infra/k8s-base/kustomization.yaml includes observability-rbac.yaml', () => {
    const k = loadYaml<any>('infra/k8s-base/kustomization.yaml');
    expect(k?.resources ?? []).toEqual(expect.arrayContaining(['observability-rbac.yaml']));
  });
});

describe('AC1.A / T10: install.sh bootstrap', () => {
  const path = 'scripts/observability/install.sh';

  test('1.4-UNIT-100: script exists and is executable', () => {
    expect(repoFileExists(path)).toBe(true);
    const mode = statSync(repoPath(path)).mode;
    expect(mode & 0o100).not.toBe(0);
  });

  test('1.4-UNIT-101: first non-shebang line is the BOOTSTRAP MODE banner (m-2)', () => {
    const lines = readRepoFile(path).split('\n');
    let i = 0;
    if (lines[i]?.startsWith('#!')) i++;
    // skip blank lines
    while (i < lines.length && lines[i].trim() === '') i++;
    expect(lines[i]).toMatch(
      /#\s*BOOTSTRAP MODE\s*—\s*superseded by ArgoCD Application once ArgoCD is installed \(Story 1\.7\+\)/,
    );
  });

  test('1.4-UNIT-102: invokes helm upgrade --install for all 5 obs charts', () => {
    const text = readRepoFile(path);
    for (const chart of ['kube-prometheus-stack', 'loki', 'promtail', 'jaeger', 'otel-collector']) {
      const re = new RegExp(`helm\\s+upgrade\\s+--install\\s+${chart}\\b`);
      expect(text).toMatch(re);
    }
  });

  test('1.4-UNIT-103: invokes helm upgrade --install sample-otel-app with --set image.tag=$(git rev-parse --short HEAD) (M-4)', () => {
    const text = readRepoFile(path);
    expect(text).toMatch(/helm\s+upgrade\s+--install\s+sample-otel-app[\s\S]*--namespace\s+he-api-staging/);
    expect(text).toMatch(/--set\s+image\.tag=\$\(git\s+rev-parse\s+--short\s+HEAD\)/);
  });

  test('1.4-UNIT-104: kubectl wait for ServiceMonitor CRD between kube-prometheus-stack and dependents (m-3)', () => {
    const text = readRepoFile(path);
    const waitRe = /kubectl\s+wait\s+--for\s+condition=Established\s+crd\/servicemonitors\.monitoring\.coreos\.com\s+--timeout=60s/;
    expect(text).toMatch(waitRe);
    // ordering: wait command appears AFTER kube-prometheus-stack install line and BEFORE loki/promtail/jaeger/otel-collector lines
    const idxKps = text.indexOf('kube-prometheus-stack');
    const idxWait = text.search(waitRe);
    const idxLoki = text.indexOf('loki');
    expect(idxKps).toBeGreaterThanOrEqual(0);
    expect(idxWait).toBeGreaterThan(idxKps);
    expect(idxLoki).toBeGreaterThan(idxWait);
  });

  test('1.4-UNIT-105: install order matches Q1 ruling: kube-prometheus-stack → wait → loki → promtail → jaeger → otel-collector → sample-otel-app', () => {
    const text = readRepoFile(path);
    const labels = ['kube-prometheus-stack', 'loki', 'promtail', 'jaeger', 'otel-collector', 'sample-otel-app'];
    let prev = -1;
    for (const label of labels) {
      const idx = text.indexOf(label, prev + 1);
      expect(idx, `expected "${label}" after position ${prev}`).toBeGreaterThan(prev);
      prev = idx;
    }
  });

  test('1.4-UNIT-106: NO "tempo" substring (M-5 negative)', () => {
    expect(readRepoFile(path).toLowerCase()).not.toContain('tempo');
  });

  test('1.4-UNIT-107: each helm upgrade --install is followed by a kubectl wait pod barrier', () => {
    const text = readRepoFile(path);
    const installs = text.match(/helm\s+upgrade\s+--install\s+\S+/g) ?? [];
    expect(installs.length).toBeGreaterThanOrEqual(6);
    // Coarse check: total wait barriers >= number of installs
    const waitsPod = text.match(/kubectl\s+wait\s+--for=condition=ready\s+pod/g) ?? [];
    expect(waitsPod.length).toBeGreaterThanOrEqual(installs.length);
  });

  test('1.4-UNIT-108: --create-namespace flag present (forward-compat)', () => {
    expect(readRepoFile(path)).toMatch(/--create-namespace/);
  });

  test('1.4-UNIT-109: namespace separation: monitoring for obs charts, he-api-staging for sample-otel-app', () => {
    const text = readRepoFile(path);
    expect(text).toMatch(/--namespace\s+monitoring/);
    expect(text).toMatch(/--namespace\s+he-api-staging/);
  });
});

// ============================================================
// AC1.B: Grafana 可访问 + datasource 联通
// ============================================================

describe('AC1.B / T6: Grafana datasources + dashboards', () => {
  test('1.4-UNIT-120: 3 datasources (Prometheus default, Loki, Jaeger) declared with cluster-local URLs', () => {
    const candidates = [
      'infra/helm/observability/kube-prometheus-stack/templates/grafana-datasources.yaml',
      'infra/helm/observability/kube-prometheus-stack/grafana-datasources.yaml',
    ];
    const present = candidates.find(repoFileExists);
    expect(present, `expected one of: ${candidates.join(', ')}`).toBeDefined();
    const text = readRepoFile(present!);
    expect(text).toMatch(/Prometheus[\s\S]+kube-prometheus-stack-prometheus\.monitoring\.svc\.cluster\.local:9090/);
    expect(text).toMatch(/Loki[\s\S]+loki\.monitoring\.svc\.cluster\.local:3100/);
    expect(text).toMatch(/Jaeger[\s\S]+jaeger-query\.monitoring\.svc\.cluster\.local:16686/);
    expect(text).toMatch(/isDefault:\s*true/);
  });

  test('1.4-UNIT-121: NO Tempo datasource entry (Q2 + M-5 negative)', () => {
    const candidates = [
      'infra/helm/observability/kube-prometheus-stack/templates/grafana-datasources.yaml',
      'infra/helm/observability/kube-prometheus-stack/grafana-datasources.yaml',
    ];
    const present = candidates.find(repoFileExists);
    expect(present).toBeDefined();
    expect(readRepoFile(present!).toLowerCase()).not.toContain('tempo');
  });

  test('1.4-UNIT-122: datasources ConfigMap labelled grafana_datasource: "1"', () => {
    const candidates = [
      'infra/helm/observability/kube-prometheus-stack/templates/grafana-datasources.yaml',
      'infra/helm/observability/kube-prometheus-stack/grafana-datasources.yaml',
    ];
    const present = candidates.find(repoFileExists);
    expect(present).toBeDefined();
    expect(readRepoFile(present!)).toMatch(/grafana_datasource:\s*["']?1["']?/);
  });

  test('1.4-UNIT-123: gateway.json parses as JSON and has ≥4 panels', () => {
    const text = readRepoFile('infra/grafana-dashboards/gateway.json');
    const j = JSON.parse(text);
    expect(Array.isArray(j.panels)).toBe(true);
    expect(j.panels.length).toBeGreaterThanOrEqual(4);
  });

  test('1.4-UNIT-124: every PromQL in gateway.json uses http_server_request_duration_seconds_* metric (M-1)', () => {
    const j = JSON.parse(readRepoFile('infra/grafana-dashboards/gateway.json'));
    const exprs: string[] = [];
    for (const p of j.panels ?? []) {
      for (const t of p.targets ?? []) {
        if (typeof t.expr === 'string') exprs.push(t.expr);
      }
    }
    expect(exprs.length).toBeGreaterThan(0);
    for (const expr of exprs) {
      expect(expr).toMatch(/http_server_request_duration_seconds_(count|bucket|sum)/);
      expect(expr).not.toMatch(/http_server_requests_total\b/);
    }
  });

  test('1.4-UNIT-125: every label selector uses service_name= and http_response_status_code= (M-1, never bare service= / status=)', () => {
    const j = JSON.parse(readRepoFile('infra/grafana-dashboards/gateway.json'));
    const exprs: string[] = [];
    for (const p of j.panels ?? []) {
      for (const t of p.targets ?? []) {
        if (typeof t.expr === 'string') exprs.push(t.expr);
      }
    }
    for (const expr of exprs) {
      // No bare `service=` (without trailing _name)
      expect(expr).not.toMatch(/[{,\s]service[=~!]/);
      // No bare `status=` (without _code suffix)
      expect(expr).not.toMatch(/[{,\s]status[=~!]/);
      // If the expression filters on a service, it must use service_name
      if (/sample-otel-app/.test(expr)) {
        expect(expr).toMatch(/service_name=/);
      }
      // If the expression filters on a status, it must use http_response_status_code
      if (/(4\.\.|5\.\.)/.test(expr)) {
        expect(expr).toMatch(/http_response_status_code=/);
      }
    }
  });

  test('1.4-UNIT-126: gateway.json declares variable $service from label_values(http_server_request_duration_seconds_count, service_name)', () => {
    const j = JSON.parse(readRepoFile('infra/grafana-dashboards/gateway.json'));
    const vars = j?.templating?.list ?? [];
    const svc = vars.find((v: any) => v.name === 'service');
    expect(svc).toBeDefined();
    const q = typeof svc.query === 'string' ? svc.query : svc.query?.query;
    expect(q).toMatch(/label_values\(\s*http_server_request_duration_seconds_count\s*,\s*service_name\s*\)/);
  });

  test('1.4-UNIT-127: 4 placeholder dashboards exist and contain "Pending Epic" markdown panel', () => {
    for (const name of ['business', 'model', 'payment', 'compliance']) {
      const path = `infra/grafana-dashboards/${name}.json`;
      expect(repoFileExists(path), `missing ${path}`).toBe(true);
      const j = JSON.parse(readRepoFile(path));
      const md = (j.panels ?? []).find(
        (p: any) => p.type === 'text' && /Pending\s+Epic/.test(p.options?.content ?? p.content ?? ''),
      );
      expect(md, `missing 'Pending Epic …' markdown panel in ${name}.json`).toBeDefined();
    }
  });

  test('1.4-UNIT-128: kustomization.yaml is configMapGenerator referencing all 5 dashboards with grafana_dashboard label', () => {
    const k = loadYaml<any>('infra/grafana-dashboards/kustomization.yaml');
    const gens = k?.configMapGenerator ?? [];
    expect(gens.length).toBeGreaterThan(0);
    const allFiles = gens.flatMap((g: any) => g.files ?? []).join(' ');
    for (const name of ['gateway', 'business', 'model', 'payment', 'compliance']) {
      expect(allFiles).toContain(`${name}.json`);
    }
    // label propagation either at top-level commonLabels or per-generator options.labels
    const topLabels = k?.commonLabels ?? {};
    const genLabels = gens
      .map((g: any) => g?.options?.labels ?? {})
      .reduce((acc: Record<string, string>, l: Record<string, string>) => ({ ...acc, ...l }), {});
    expect(topLabels.grafana_dashboard ?? genLabels.grafana_dashboard).toBe('1');
  });

  test('1.4-UNIT-129: all 5 dashboard JSONs parse without exception', () => {
    for (const name of ['gateway', 'business', 'model', 'payment', 'compliance']) {
      expect(() => JSON.parse(readRepoFile(`infra/grafana-dashboards/${name}.json`))).not.toThrow();
    }
  });
});

// ============================================================
// AC1.C: Sample 服务可观测信号完整 (trace + metrics + bonus logs)
// ============================================================

describe('AC1.C / T8: sample-otel-app source', () => {
  test('1.4-UNIT-200: go.mod declares Go 1.22+ AND requires OTel SDK + otelhttp + otlptracegrpc + prometheus client', () => {
    const text = readRepoFile('apps/sample-otel-app/go.mod');
    expect(text).toMatch(/^go\s+1\.(2[2-9]|[3-9]\d)/m);
    expect(text).toMatch(/go\.opentelemetry\.io\/otel\b/);
    expect(text).toMatch(/go\.opentelemetry\.io\/contrib\/instrumentation\/net\/http\/otelhttp/);
    expect(text).toMatch(/go\.opentelemetry\.io\/otel\/exporters\/otlp\/otlptrace\/otlptracegrpc/);
    expect(text).toMatch(/github\.com\/prometheus\/client_golang/);
  });

  test('1.4-UNIT-201: main.go registers /hello, /healthz, /metrics routes', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/"\/hello"/);
    expect(src).toMatch(/"\/healthz"/);
    expect(src).toMatch(/"\/metrics"/);
  });

  test('1.4-UNIT-202: main.go listens on :8080', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/(":8080"|Addr:\s*":8080")/);
  });

  test('1.4-UNIT-203: main.go uses otlptracegrpc exporter wired to OTEL_EXPORTER_OTLP_ENDPOINT', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/otlptracegrpc/);
    expect(src).toMatch(/OTEL_EXPORTER_OTLP_ENDPOINT/);
  });

  test('1.4-UNIT-204: main.go declares OTel Resource with service.name/namespace/version', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/service\.name|ServiceName/);
    expect(src).toMatch(/sample-otel-app/);
    expect(src).toMatch(/he-api-staging/);
    expect(src).toMatch(/0\.1\.0/);
  });

  test('1.4-UNIT-205: main.go wraps mux with otelhttp middleware', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/otelhttp\.NewHandler|otelhttp\.NewMiddleware/);
  });

  test('1.4-UNIT-206: main.go registers promhttp.Handler() at /metrics', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/promhttp\.Handler\(\)/);
  });

  test('1.4-UNIT-207: main.go uses log/slog JSON handler AND extracts trace_id from SpanFromContext', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/slog\.NewJSONHandler/);
    expect(src).toMatch(/SpanFromContext/);
  });

  test('1.4-UNIT-208: main.go does NOT hardcode k8s.pod.name / k8s.namespace.name resource attrs', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    // tolerated: comments. forbidden: literal attribute keys assigned in resource.
    expect(src).not.toMatch(/attribute\.String\(\s*"k8s\.pod\.name"/);
    expect(src).not.toMatch(/attribute\.String\(\s*"k8s\.namespace\.name"/);
  });

  test('1.4-UNIT-209: main.go calls tracerProvider.Shutdown on SIGTERM/Interrupt (graceful flush)', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/Shutdown\(/);
    expect(src).toMatch(/SIGTERM|os\.Interrupt|syscall\.SIGINT/);
  });

  test('1.4-UNIT-210: main.go does NOT call log.Fatal/panic on empty OTEL_EXPORTER_OTLP_ENDPOINT (degraded mode)', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    // Heuristic: any block that detects empty endpoint should warn, not fatal/panic.
    // We assert the source does not contain `log.Fatal(...OTEL_EXPORTER...)` or `panic(...OTEL_EXPORTER...)`.
    expect(src).not.toMatch(/log\.Fatal[\s\S]{0,200}OTEL_EXPORTER_OTLP_ENDPOINT/);
    expect(src).not.toMatch(/panic\([^)]*OTEL_EXPORTER_OTLP_ENDPOINT/);
  });

  test('1.4-UNIT-211: main_test.go covers /hello, /metrics, and trace_id log field', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main_test.go');
    expect(src).toMatch(/Test\w*Hello/);
    expect(src).toMatch(/Test\w*Metrics/);
    // trace_id assertion (string literal or constant)
    expect(src).toMatch(/trace_id/);
  });

  test('1.4-UNIT-212: Dockerfile is multi-stage, distroless, USER 65532', () => {
    const text = readRepoFile('apps/sample-otel-app/Dockerfile');
    const fromCount = (text.match(/^FROM\b/gm) ?? []).length;
    expect(fromCount).toBeGreaterThanOrEqual(2);
    expect(text).toMatch(/gcr\.io\/distroless\//);
    expect(text).toMatch(/^USER\s+65532\b/m);
  });

  test('1.4-UNIT-213: deliverable_binding L475 — main.go contains OTEL_EXPORTER_OTLP_ENDPOINT or otlptracegrpc', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/OTEL_EXPORTER_OTLP_ENDPOINT|otlptracegrpc/);
  });

  test('1.4-UNIT-214: deliverable_binding L481 — main.go contains promhttp.Handler() or "/metrics"', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/promhttp\.Handler\(\)|"\/metrics"/);
  });

  test('1.4-UNIT-215: deliverable_binding L487 — main.go contains trace_id and SpanFromContext', () => {
    const src = readRepoFile('apps/sample-otel-app/cmd/server/main.go');
    expect(src).toMatch(/trace_id/);
    expect(src).toMatch(/SpanFromContext/);
  });
});

describe('AC1.C / T9: sample-otel-app Helm chart', () => {
  test('1.4-UNIT-220: Chart.yaml apiVersion=v2, name=sample-otel-app', () => {
    const c = loadYaml<any>('infra/helm/sample-otel-app/Chart.yaml');
    expect(c?.apiVersion).toBe('v2');
    expect(c?.name).toBe('sample-otel-app');
  });

  test('1.4-UNIT-221: deployment.yaml carries 6 Pod Security Restricted fields', () => {
    const text = readRepoFile('infra/helm/sample-otel-app/templates/deployment.yaml');
    expect(text).toMatch(/runAsNonRoot:\s*true/);
    expect(text).toMatch(/runAsUser:\s*65532/);
    expect(text).toMatch(/readOnlyRootFilesystem:\s*true/);
    expect(text).toMatch(/allowPrivilegeEscalation:\s*false/);
    expect(text).toMatch(/drop:\s*\n\s*-\s*ALL/);
    expect(text).toMatch(/seccompProfile:[\s\S]+type:\s*RuntimeDefault/);
  });

  test('1.4-UNIT-222: servicemonitor.yaml targets port 8080 with interval 15s', () => {
    const text = readRepoFile('infra/helm/sample-otel-app/templates/servicemonitor.yaml');
    expect(text).toMatch(/kind:\s*ServiceMonitor/);
    expect(text).toMatch(/(port:\s*(http|metrics|8080)|targetPort:\s*8080)/);
    expect(text).toMatch(/interval:\s*15s/);
  });

  test('1.4-UNIT-223: values-staging.yaml image.repository points at ${ACR_REGISTRY}/he-api/sample-otel-app', () => {
    const text = readRepoFile('infra/helm/sample-otel-app/values-staging.yaml');
    expect(text).toMatch(/image:[\s\S]+repository:\s*[^\n]*\$\{?ACR_REGISTRY\}?\/he-api\/sample-otel-app/);
  });

  test('1.4-UNIT-224: values-staging.yaml image.tag === "latest" (install.sh overrides with SHA per M-4)', () => {
    const v = loadYaml<any>('infra/helm/sample-otel-app/values-staging.yaml');
    expect(v?.image?.tag).toBe('latest');
  });

  test('1.4-UNIT-225: env OTEL_EXPORTER_OTLP_ENDPOINT === otel-collector.monitoring.svc.cluster.local:4317', () => {
    const text = readRepoFile('infra/helm/sample-otel-app/values-staging.yaml');
    expect(text).toMatch(/OTEL_EXPORTER_OTLP_ENDPOINT[\s\S]+otel-collector\.monitoring\.svc\.cluster\.local:4317/);
  });
});

describe('AC1.C / T11: CI extension (.github/workflows/infra-lint.yml)', () => {
  const path = '.github/workflows/infra-lint.yml';

  test('1.4-UNIT-240: helm-lint-observability job declares matrix of all 6 charts (M-2)', () => {
    const wf = loadYaml<any>(path);
    const job = wf?.jobs?.['helm-lint-observability'];
    expect(job).toBeDefined();
    const matrix = job?.strategy?.matrix?.chart ?? [];
    for (const c of ['kube-prometheus-stack', 'loki', 'promtail', 'otel-collector', 'jaeger', 'sample-otel-app']) {
      expect(matrix).toContain(c);
    }
    expect(matrix.length).toBeGreaterThanOrEqual(6);
  });

  test('1.4-UNIT-241: helm-lint-observability runs dependency update + lint + template|kubeconform', () => {
    const text = readRepoFile(path);
    expect(text).toMatch(/helm\s+dependency\s+update/);
    expect(text).toMatch(/helm\s+lint/);
    expect(text).toMatch(/helm\s+template[\s\S]+kubeconform/);
  });

  test('1.4-UNIT-242: dashboard-schema-validate job exists', () => {
    const wf = loadYaml<any>(path);
    expect(wf?.jobs?.['dashboard-schema-validate']).toBeDefined();
  });

  test('1.4-UNIT-243: paths filter includes infra/**, apps/sample-otel-app/**, .github/workflows/infra-lint.yml', () => {
    const wf = loadYaml<any>(path);
    const trigger = wf?.on?.pull_request ?? wf?.on?.push ?? wf?.on?.['true']; // YAML 1.1 'on' parses as boolean true
    // Try multiple shapes
    const paths: string[] =
      wf?.on?.pull_request?.paths ?? wf?.on?.push?.paths ?? trigger?.paths ?? [];
    const collected = paths.length > 0 ? paths : (() => {
      // Walk every paths array under any trigger
      const out: string[] = [];
      for (const triggerName of Object.keys(wf?.on ?? {})) {
        const node = wf.on[triggerName];
        if (Array.isArray(node?.paths)) out.push(...node.paths);
      }
      return out;
    })();
    expect(collected).toEqual(
      expect.arrayContaining(['infra/**', 'apps/sample-otel-app/**', '.github/workflows/infra-lint.yml']),
    );
  });

  test('1.4-UNIT-244: concurrency block reused from 1.3', () => {
    const wf = loadYaml<any>(path);
    expect(wf?.concurrency?.group).toMatch(/infra-lint-/);
    // cancel-in-progress is a GHA expression; tolerate either string form
    expect(String(wf?.concurrency?.['cancel-in-progress'])).toMatch(/pull_request/);
  });

  test('1.4-UNIT-245: 1.3 baseline jobs are NOT removed (still referenced in workflow)', () => {
    const wf = loadYaml<any>(path);
    // Story 1.3 introduced these 4 job IDs. Story 1.4 must add jobs only.
    for (const baseline of ['terraform-fmt', 'terraform-validate', 'tflint', 'helm-lint-api-gateway']) {
      // Tolerate alternate names by walking all job keys for substring match.
      const found = Object.keys(wf?.jobs ?? {}).some((k) =>
        k === baseline || k.replace(/-/g, '').includes(baseline.replace(/-/g, '')),
      );
      expect(found, `missing 1.3 baseline job similar to "${baseline}"`).toBe(true);
    }
  });
});

describe('AC1.C / T12: README "Observability" section', () => {
  test('1.4-UNIT-260: README has Observability heading', () => {
    const md = readRepoFile('README.md');
    expect(md).toMatch(/^#{1,6}\s*Observability/m);
  });

  test('1.4-UNIT-261: README contains the kubectl get secret extraction command for Grafana admin pwd', () => {
    const md = readRepoFile('README.md');
    expect(md).toMatch(/kubectl\s+get\s+secret[\s\S]+kube-prometheus-stack-grafana[\s\S]+admin-password[\s\S]+base64\s+-d/);
  });

  test('1.4-UNIT-262: README mentions cost ≈ +¥0 for staging emptyDir (Q4)', () => {
    const md = readRepoFile('README.md');
    expect(md).toMatch(/(\+¥0|\+0\s*¥|emptyDir.*¥0)/);
  });

  test('1.4-UNIT-263: README defers public exposure / TLS / auth to Story 1.7+', () => {
    const md = readRepoFile('README.md');
    expect(md).toMatch(/Story\s*1\.7\+?/);
    expect(md).toMatch(/(ingress|公网|TLS)/);
  });

  test('1.4-UNIT-264: README mentions BOOTSTRAP MODE / ArgoCD migration (m-2)', () => {
    const md = readRepoFile('README.md');
    expect(md).toMatch(/BOOTSTRAP|ArgoCD/);
  });

  test('1.4-UNIT-265: README lists 5 dashboard names with implementation status', () => {
    const md = readRepoFile('README.md');
    for (const name of ['Gateway', 'Business|业务', 'Model|模型', 'Payment|支付', 'Compliance|合规']) {
      expect(md).toMatch(new RegExp(name));
    }
    // status legend: at least one ✓ and one □ (placeholder)
    expect(md).toMatch(/[✓✔]/);
    expect(md).toMatch(/(□|placeholder|占位)/);
  });
});

// ============================================================
// Integration scenarios
// ============================================================

describe('AC1 / Integration', () => {
  test.skip('1.4-INT-001: PR-driven: helm-lint-observability matrix passes for all 6 charts — see docs/dev/logs/1.4-dev-log.md §CI Run', () => {});
  test.skip('1.4-INT-002: PR-driven: dashboard-schema-validate passes for all 5 dashboards — see docs/dev/logs/1.4-dev-log.md §CI Run', () => {});
  test.skip('1.4-INT-003: PR-driven: 1.3 existing 4 infra-lint jobs remain green — see docs/dev/logs/1.4-dev-log.md §CI Run', () => {});

  test('1.4-INT-004: bash -n scripts/observability/install.sh syntax check exits 0', async () => {
    const { execFileSync } = await import('node:child_process');
    expect(() =>
      execFileSync('bash', ['-n', repoPath('scripts/observability/install.sh')], { stdio: 'pipe' }),
    ).not.toThrow();
  });

  test.skip('1.4-INT-005: testcontainers-go OTLP/gRPC handshake — see docs/dev/logs/1.4-dev-log.md §Integration (optional)', () => {});
  test.skip('1.4-INT-006: kind cluster up{job="sample-otel-app"}=1 within 60s — see docs/dev/logs/1.4-dev-log.md §Integration (optional)', () => {});
});

// ============================================================
// E2E scenarios — Dev runs once on staging cluster (T13); evidence in dev-log §E2E
// ============================================================

describe('AC1 / E2E', () => {
  test.skip('1.4-E2E-001: install.sh real exec on staging — see docs/dev/logs/1.4-dev-log.md §E2E', () => {});
  test.skip('1.4-E2E-002: helm list -n monitoring shows 5 releases — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-003: kubectl get pod -n monitoring all Running/Completed — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-004: ServiceMonitor for sample-otel-app present — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-005: Grafana login via secret-extracted admin pwd — see dev-log §E2E (screenshot 2)', () => {});
  test.skip('1.4-E2E-006: 3 datasources Save&test green — see dev-log §E2E (screenshot 2)', () => {});
  test.skip('1.4-E2E-007: Negative — Grafana data sources contain no Tempo entry — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-008: sample-otel-app pod logs contain trace_id/span_id — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-009: curl /hello?name=test ×10 returns 200 — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-010: Jaeger search service sample-otel-app returns ≥1 trace — see dev-log §E2E (screenshot 3)', () => {});
  test.skip('1.4-E2E-011: trace contains GET /hello root + ≥1 child span — see dev-log §E2E (screenshot 3)', () => {});
  test.skip('1.4-E2E-012: span has OTel resource attrs incl. k8s.* — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-013: Gateway dashboard RED curves non-empty — see dev-log §E2E (screenshot 4)', () => {});
  test.skip('1.4-E2E-014: PromQL up{job="sample-otel-app"}=1 — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-015: PromQL rate(http_server_request_duration_seconds_count{service_name=…})>0 — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-016: Loki LogQL trace_id present (bonus) — see dev-log §E2E (screenshot 5)', () => {});
  test.skip('1.4-E2E-017: 5 screenshots collected in dev-log — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-018: SHA injection roundtrip — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-019: git diff .github/workflows/deploy-staging.yml empty — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-020: helm uninstall sample-otel-app preserves 1.3 baseline — see dev-log §E2E', () => {});
  test.skip('1.4-E2E-021: Q1-Q6 traceability table in dev-log — see dev-log §Architect Q-ruling Trace', () => {});
});

// ============================================================
// [BLIND-SPOT] scenarios
// ============================================================

describe('[BLIND-SPOT] scenarios', () => {
  // Static blind spots have real assertions; runtime blind spots stay test.skip.
  test('1.4-BLIND-ERROR-003 (BOUNDARY check): install.sh kubectl-wait for ServiceMonitor CRD precedes dependents', () => {
    const text = readRepoFile('scripts/observability/install.sh');
    const waitIdx = text.search(/kubectl\s+wait\s+--for\s+condition=Established\s+crd\/servicemonitors/);
    const lokiIdx = text.indexOf('loki');
    const promtailIdx = text.indexOf('promtail');
    const jaegerIdx = text.indexOf('jaeger');
    const otelIdx = text.indexOf('otel-collector');
    expect(waitIdx).toBeGreaterThan(-1);
    expect(waitIdx).toBeLessThan(lokiIdx);
    expect(waitIdx).toBeLessThan(promtailIdx);
    expect(waitIdx).toBeLessThan(jaegerIdx);
    expect(waitIdx).toBeLessThan(otelIdx);
  });

  test.skip('1.4-BLIND-BOUNDARY-001: GET /hello with empty name returns 200 — covered by main_test.go (UNIT-211)', () => {});
  test.skip('1.4-BLIND-BOUNDARY-002: GET /hello with 10K-char name does not OOM — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-BOUNDARY-003: malformed dashboard JSON fails dashboard-schema-validate — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-BOUNDARY-004: Loki ephemeral-storage 2Gi limit triggers eviction not OOMKill — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-ERROR-001: OTel collector down → sample-otel-app continues 200 — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-ERROR-002: empty OTEL_EXPORTER_OTLP_ENDPOINT → no-export degraded mode — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-FLOW-001: install.sh re-run idempotent (no resource recreation) — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-FLOW-002: install.sh Ctrl-C interrupt + resume — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-FLOW-003: trace_id propagation across handler chain — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-CONCURRENCY-001: 100 concurrent /hello — counter increments by 100 — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-CONCURRENCY-002: ServiceMonitor label-selector drift detected within 1 scrape — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-DATA-001: Prom 24h retention drop — see dev-log §Blind-spot (manual / accelerated)', () => {});
  test.skip('1.4-BLIND-RESOURCE-001: SIGTERM → TracerProvider.Shutdown flushes pending spans — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-RESOURCE-002: PSA baseline admission clean (no FailedCreate events) — see dev-log §Blind-spot', () => {});
  test.skip('1.4-BLIND-RESOURCE-003: helm release lock — second install fails fast — see dev-log §Blind-spot', () => {});
});
