/**
 * Test skeleton for Story 1.5: 内部 gRPC 服务模板（Go）
 *
 * AUTO-GENERATED by QA Test Design (Turing, 2026-05-11). Dev MUST keep every
 * static (Unit) scenario passing once the corresponding deliverable lands;
 * runtime / CI / E2E scenarios stay `test.skip` with a pointer to
 * `docs/dev/logs/1.5-dev-log.md` §Integration / §E2E.
 *
 * Static scenarios parse:
 *   - Bash source (`scripts/scaffold-svc.sh`) via raw text + regex
 *   - `.tmpl` template files under `scripts/scaffold-svc/templates/` via raw text
 *   - Buf config (`packages/proto/buf.yaml`, `buf.gen.yaml`) via `yaml`
 *   - Helm chart templates (rendered + `.tmpl`) via raw text + selective YAML
 *   - Go source (`packages/go-observability/*.go`, `apps/sample-grpc-app/...`) via text regex
 *   - Workflow YAML (`.github/workflows/{build-images,infra-lint,test}.yml`) via `yaml`
 *   - Story body / source-tree.md for traceability invariants
 *
 * Test Design: docs/qa/assessments/1.5-test-design-20260511.md
 */

import { describe, expect, test } from 'vitest';
import { readFileSync, existsSync, statSync, readdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..', '..', '..');

const repoPath = (rel: string): string => resolve(REPO_ROOT, rel);
const repoFileExists = (rel: string): boolean => existsSync(repoPath(rel));
const readRepoFile = (rel: string): string => readFileSync(repoPath(rel), 'utf8');
const loadYaml = <T = unknown>(rel: string): T => parseYaml(readRepoFile(rel)) as T;

const SCAFFOLD = 'scripts/scaffold-svc.sh';
const TPL_ROOT = 'scripts/scaffold-svc/templates';
const PROTO_ROOT = 'packages/proto';
const OBS_ROOT = 'packages/go-observability';
const SAMPLE_APP = 'apps/sample-grpc-app';
const SAMPLE_CHART = 'infra/helm/sample-grpc-app';
const SAMPLE_PROTO = 'packages/proto/he/sample/v1/sample.proto';
const STORY_FILE = 'docs/stories/1.5-internal-grpc-service-template-go.md';

const SKIP_REASON = 'runtime/CI/E2E scenario — see docs/dev/logs/1.5-dev-log.md';

// ============================================================
// AC1.A: Scaffolding 工具可执行且原子化（Q1 + Q2）
// ============================================================

describe('AC1.A / T1a: Tool entrypoint shape (scripts/scaffold-svc.sh)', () => {
  test('1.5-UNIT-001: scaffold-svc.sh exists AND is executable', () => {
    expect(repoFileExists(SCAFFOLD)).toBe(true);
    const mode = statSync(repoPath(SCAFFOLD)).mode;
    expect(mode & 0o100).not.toBe(0);
  });

  test('1.5-UNIT-002: first line is #!/usr/bin/env bash', () => {
    const lines = readRepoFile(SCAFFOLD).split('\n');
    expect(lines[0]).toBe('#!/usr/bin/env bash');
  });

  test('1.5-UNIT-003: contains `set -euo pipefail` within first 10 lines', () => {
    const head = readRepoFile(SCAFFOLD).split('\n').slice(0, 10).join('\n');
    expect(head).toMatch(/set -euo pipefail/);
  });

  test('1.5-UNIT-004: header anchor comment present', () => {
    expect(readRepoFile(SCAFFOLD)).toMatch(/# Story 1\.5 — gRPC service scaffolder/);
  });

  test('1.5-UNIT-005: trap covers EXIT and ERR with $STAGING cleanup', () => {
    const src = readRepoFile(SCAFFOLD);
    expect(src).toMatch(/trap[^\n]*EXIT[^\n]*ERR|trap[^\n]*ERR[^\n]*EXIT/);
    expect(src).toMatch(/rm -rf\s+"?\$\{?STAGING\}?"?/);
  });

  test('1.5-UNIT-006: mktemp -d invocation for staging dir', () => {
    expect(readRepoFile(SCAFFOLD)).toMatch(/mktemp\s+-d/);
  });

  test('1.5-UNIT-007: envsubst invocation present (Q1 — POSIX tool)', () => {
    expect(readRepoFile(SCAFFOLD)).toMatch(/envsubst/);
  });

  test('1.5-UNIT-008: --name regex ^[a-z][a-z0-9-]{1,30}$', () => {
    expect(readRepoFile(SCAFFOLD)).toMatch(/\[a-z\]\[a-z0-9-\]\{1,30\}/);
  });

  test('1.5-UNIT-009: --domain regex ^[a-z][a-z0-9]{1,30}$', () => {
    expect(readRepoFile(SCAFFOLD)).toMatch(/\[a-z\]\[a-z0-9\]\{1,30\}/);
  });

  test('1.5-UNIT-010: idempotency precheck for existing service paths', () => {
    const src = readRepoFile(SCAFFOLD);
    expect(src).toMatch(/already exists/);
    expect(src).toMatch(/apps\/\$\{?NAME\}?|apps\/\$NAME/);
  });

  test('1.5-UNIT-011: usage printer on missing args', () => {
    const src = readRepoFile(SCAFFOLD);
    expect(src.toLowerCase()).toMatch(/usage/);
  });

  test('1.5-UNIT-012: prints final Q8 followup line for build-images.yml', () => {
    const src = readRepoFile(SCAFFOLD);
    expect(src).toMatch(/📋 Followup/);
    expect(src).toMatch(/build-images\.yml/);
  });

  test('1.5-UNIT-013: appends ./apps/${NAME} into go.work use block', () => {
    const src = readRepoFile(SCAFFOLD);
    expect(src).toMatch(/awk|sed/);
    expect(src).toMatch(/\.\/apps\/\$\{?NAME\}?|\.\/apps\/\$NAME/);
    expect(src).toMatch(/go\.work/);
  });

  test('1.5-UNIT-014: appends svc into infra-lint.yml helm-lint-services matrix', () => {
    const src = readRepoFile(SCAFFOLD);
    expect(src).toMatch(/helm-lint-services/);
    expect(src).toMatch(/infra-lint\.yml/);
  });

  test('1.5-UNIT-015: post-write go.work parse-validate via go env GOWORK', () => {
    const src = readRepoFile(SCAFFOLD);
    expect(src).toMatch(/go env GOWORK|go list -m/);
  });

  test('1.5-UNIT-016: lib.sh (if present) carries strict-mode propagation', () => {
    const libPath = 'scripts/scaffold-svc/lib.sh';
    if (!repoFileExists(libPath)) return;
    expect(readRepoFile(libPath)).toMatch(/set -euo pipefail|source.*scaffold-svc\.sh/);
  });

  test('1.5-UNIT-017: `git add` step for vendored proto gen after buf generate', () => {
    const src = readRepoFile(SCAFFOLD);
    expect(src).toMatch(/git add[\s\S]*packages\/proto\/gen|buf generate/);
  });
});

describe('AC1.A / T1b: Template location (Q2 ruling)', () => {
  test('1.5-UNIT-018: scripts/scaffold-svc/templates/ directory exists', () => {
    expect(repoFileExists(TPL_ROOT)).toBe(true);
  });

  test('1.5-UNIT-019: apps/_template-svc/ does NOT exist (Q2 prohibition)', () => {
    expect(repoFileExists('apps/_template-svc')).toBe(false);
  });

  test('1.5-UNIT-020: top-level templates/ does NOT exist', () => {
    expect(repoFileExists('templates')).toBe(false);
  });
});

// ============================================================
// AC1.B: 生成产物完整、可编译、可 lint
// ============================================================

describe('AC1.B / T2: main.go.tmpl (connect-go server)', () => {
  const F = `${TPL_ROOT}/cmd/server/main.go.tmpl`;

  test('1.5-UNIT-030: main.go.tmpl exists', () => {
    expect(repoFileExists(F)).toBe(true);
  });

  test('1.5-UNIT-031: imports connectrpc.com/connect', () => {
    expect(readRepoFile(F)).toMatch(/connectrpc\.com\/connect/);
  });

  test('1.5-UNIT-032: imports packages/go-observability', () => {
    expect(readRepoFile(F)).toMatch(/github\.com\/he-api\/he-api\/packages\/go-observability/);
  });

  test('1.5-UNIT-033: invokes obs.NewTracerProvider(', () => {
    expect(readRepoFile(F)).toMatch(/\.NewTracerProvider\s*\(/);
  });

  test('1.5-UNIT-034: invokes obs.NewLogger(', () => {
    expect(readRepoFile(F)).toMatch(/\.NewLogger\s*\(/);
  });

  test('1.5-UNIT-035: invokes obs.WrapHTTPHandler(', () => {
    expect(readRepoFile(F)).toMatch(/\.WrapHTTPHandler\s*\(/);
  });

  test('1.5-UNIT-036: constructs http.NewServeMux + mux.Handle for connect handler', () => {
    const src = readRepoFile(F);
    expect(src).toMatch(/http\.NewServeMux\s*\(\s*\)/);
    expect(src).toMatch(/mux\.Handle\s*\(/);
  });

  test('1.5-UNIT-037: graceful shutdown via signal.NotifyContext + 5s timeout', () => {
    const src = readRepoFile(F);
    expect(src).toMatch(/signal\.NotifyContext/);
    expect(src).toMatch(/\.Shutdown\s*\(/);
    expect(src).toMatch(/5\s*\*\s*time\.Second|5\s*\*time\.Second/);
  });

  test('1.5-UNIT-038: listens on :8080', () => {
    expect(readRepoFile(F)).toMatch(/":8080"|:8080/);
  });

  test('1.5-UNIT-039: does NOT import google.golang.org/grpc (Q3 banned)', () => {
    expect(readRepoFile(F)).not.toMatch(/"google\.golang\.org\/grpc"/);
  });

  test('1.5-UNIT-040: contains template tokens ({{NAME}} / {{DOMAIN}} / {{ServiceCamel}} or envsubst form)', () => {
    const src = readRepoFile(F);
    expect(src).toMatch(/\{\{[A-Za-z]+\}\}|\$\{[A-Z_]+\}/);
  });
});

describe('AC1.B / T2: main_test.go.tmpl', () => {
  const F = `${TPL_ROOT}/cmd/server/main_test.go.tmpl`;

  test('1.5-UNIT-041: main_test.go.tmpl exists', () => {
    expect(repoFileExists(F)).toBe(true);
  });

  test('1.5-UNIT-042: imports net/http/httptest', () => {
    expect(readRepoFile(F)).toMatch(/"net\/http\/httptest"/);
  });

  test('1.5-UNIT-043: invokes httptest.NewServer(', () => {
    expect(readRepoFile(F)).toMatch(/httptest\.NewServer\s*\(/);
  });

  test('1.5-UNIT-044: invokes connect.NewClient targeting Ping', () => {
    const src = readRepoFile(F);
    expect(src).toMatch(/NewClient[^(\n]*\(/);
    expect(src).toMatch(/Ping/);
  });

  test('1.5-UNIT-045: contains at least one failure assertion (t.Fatal/t.Errorf)', () => {
    expect(readRepoFile(F)).toMatch(/t\.Fatal|t\.Errorf|t\.Fatalf/);
  });
});

describe('AC1.B / T2: go.mod.tmpl', () => {
  const F = `${TPL_ROOT}/go.mod.tmpl`;

  test('1.5-UNIT-050: go.mod.tmpl exists', () => {
    expect(repoFileExists(F)).toBe(true);
  });

  test('1.5-UNIT-051: module path follows github.com/he-api/he-api/apps/<NAME> pattern', () => {
    expect(readRepoFile(F)).toMatch(/^module\s+github\.com\/he-api\/he-api\/apps\/[\$\{a-zA-Z}]/m);
  });

  test('1.5-UNIT-052: declares go 1.22+', () => {
    const m = readRepoFile(F).match(/^go\s+1\.(\d+)/m);
    expect(m).not.toBeNull();
    expect(Number(m![1])).toBeGreaterThanOrEqual(22);
  });

  test('1.5-UNIT-053: requires connectrpc.com/connect', () => {
    expect(readRepoFile(F)).toMatch(/connectrpc\.com\/connect/);
  });

  test('1.5-UNIT-054: requires packages/proto', () => {
    expect(readRepoFile(F)).toMatch(/github\.com\/he-api\/he-api\/packages\/proto/);
  });

  test('1.5-UNIT-055: requires packages/go-observability', () => {
    expect(readRepoFile(F)).toMatch(/github\.com\/he-api\/he-api\/packages\/go-observability/);
  });

  test('1.5-UNIT-056: does NOT require google.golang.org/grpc', () => {
    expect(readRepoFile(F)).not.toMatch(/google\.golang\.org\/grpc/);
  });
});

describe('AC1.B / T2: Dockerfile.tmpl (m-4 ruling)', () => {
  const F = `${TPL_ROOT}/Dockerfile.tmpl`;

  test('1.5-UNIT-060: Dockerfile.tmpl exists', () => {
    expect(repoFileExists(F)).toBe(true);
  });

  test('1.5-UNIT-061: multi-stage with FROM golang:1.22 + FROM gcr.io/distroless/static-debian12 (no :nonroot)', () => {
    const src = readRepoFile(F);
    expect(src).toMatch(/FROM\s+golang:1\.22/);
    expect(src).toMatch(/FROM\s+gcr\.io\/distroless\/static-debian12\b(?!:nonroot)/);
  });

  test('1.5-UNIT-062: contains literal USER 65532', () => {
    expect(readRepoFile(F)).toMatch(/^USER\s+65532\s*$/m);
  });

  test('1.5-UNIT-063: EXPOSE 8080', () => {
    expect(readRepoFile(F)).toMatch(/^EXPOSE\s+8080\s*$/m);
  });

  test('1.5-UNIT-064: ENTRYPOINT ["/server"]', () => {
    expect(readRepoFile(F)).toMatch(/ENTRYPOINT\s*\[\s*"\/server"\s*\]/);
  });

  test('1.5-UNIT-065: does NOT use :nonroot suffix (m-4 prohibition)', () => {
    expect(readRepoFile(F)).not.toMatch(/gcr\.io\/distroless\/static-debian12:nonroot/);
  });
});

describe('AC1.B / T2: turbo.json.tmpl + package.json.tmpl (m-3 ruling)', () => {
  const TJ = `${TPL_ROOT}/turbo.json.tmpl`;
  const PJ = `${TPL_ROOT}/package.json.tmpl`;

  test('1.5-UNIT-070: turbo.json.tmpl exists', () => {
    expect(repoFileExists(TJ)).toBe(true);
  });

  test('1.5-UNIT-071: package.json.tmpl exists', () => {
    expect(repoFileExists(PJ)).toBe(true);
  });

  test('1.5-UNIT-072: package.json.tmpl build stub is literal m-3 payload', () => {
    expect(readRepoFile(PJ)).toMatch(/"build"\s*:\s*"echo \\"go build is run via go workspace, not Turborepo\\" && exit 0"/);
  });

  test('1.5-UNIT-073: package.json.tmpl lint stub returns exit 0', () => {
    expect(readRepoFile(PJ)).toMatch(/"lint"\s*:\s*"echo[^"]*"\s*&&\s*exit 0"/);
  });

  test('1.5-UNIT-074: package.json.tmpl test stub returns exit 0', () => {
    expect(readRepoFile(PJ)).toMatch(/"test"\s*:\s*"echo[^"]*"\s*&&\s*exit 0"/);
  });

  test('1.5-UNIT-075: package.json.tmpl name field is templated', () => {
    expect(readRepoFile(PJ)).toMatch(/"name"\s*:\s*"[^"]*(\{\{[A-Z]+\}\}|\$\{[A-Z_]+\})/);
  });
});

describe('AC1.B / T2: internal/.gitkeep (m-5 ruling)', () => {
  test('1.5-UNIT-080: scaffold-svc.sh emits apps/${NAME}/internal/.gitkeep OR dogfood file exists', () => {
    const scaffold = repoFileExists(SCAFFOLD) ? readRepoFile(SCAFFOLD) : '';
    const dogfoodExists = repoFileExists(`${SAMPLE_APP}/internal/.gitkeep`);
    expect(scaffold.includes('internal/.gitkeep') || dogfoodExists).toBe(true);
  });

  test('1.5-UNIT-081: README.md "Scaffolding a new gRPC service" mentions internal/', () => {
    const readme = readRepoFile('README.md');
    const section = readme.split(/##\s+Scaffolding a new gRPC service/i)[1] ?? '';
    expect(section).toMatch(/internal\//);
  });
});

describe('AC1.B / T3: Buf toolchain (Q4 ruling)', () => {
  const BUF = `${PROTO_ROOT}/buf.yaml`;
  const GEN = `${PROTO_ROOT}/buf.gen.yaml`;
  const GI = `${PROTO_ROOT}/.gitignore`;

  test('1.5-UNIT-090: buf.yaml exists AND parses as YAML', () => {
    expect(repoFileExists(BUF)).toBe(true);
    expect(() => loadYaml(BUF)).not.toThrow();
  });

  test('1.5-UNIT-091: buf.yaml declares version key', () => {
    const cfg = loadYaml<{ version?: string }>(BUF);
    expect(cfg.version).toBeDefined();
  });

  test('1.5-UNIT-092: buf.gen.yaml exists AND parses as YAML', () => {
    expect(repoFileExists(GEN)).toBe(true);
    expect(() => loadYaml(GEN)).not.toThrow();
  });

  test('1.5-UNIT-093: buf.gen.yaml declares Go plugin', () => {
    expect(readRepoFile(GEN)).toMatch(/protocolbuffers\/go|buf\.build\/protocolbuffers\/go/);
  });

  test('1.5-UNIT-094: buf.gen.yaml declares connect-go plugin', () => {
    expect(readRepoFile(GEN)).toMatch(/connectrpc\/go|connect-go|connectrpc\.com\/connect-go/);
  });

  test('1.5-UNIT-095: buf.gen.yaml output dir contains packages/proto/gen/go', () => {
    expect(readRepoFile(GEN)).toMatch(/packages\/proto\/gen\/go|gen\/go/);
  });

  test('1.5-UNIT-096: .gitignore does NOT ignore gen/ (Q4 vendored)', () => {
    if (!repoFileExists(GI)) return;
    expect(readRepoFile(GI)).not.toMatch(/^gen\/?\s*$/m);
  });

  test('1.5-UNIT-097: proto .tmpl exists under templates/proto/', () => {
    const candidates = [
      `${TPL_ROOT}/proto/<svc>.proto.tmpl`,
      `${TPL_ROOT}/proto/service.proto.tmpl`,
    ];
    const dir = `${TPL_ROOT}/proto`;
    const anyTmpl = repoFileExists(dir)
      ? readdirSync(repoPath(dir)).some((f) => f.endsWith('.proto.tmpl'))
      : false;
    expect(candidates.some(repoFileExists) || anyTmpl).toBe(true);
  });

  test('1.5-UNIT-098: proto template starts with syntax = "proto3";', () => {
    const dir = `${TPL_ROOT}/proto`;
    if (!repoFileExists(dir)) return;
    const tmpl = readdirSync(repoPath(dir)).find((f) => f.endsWith('.proto.tmpl'));
    if (!tmpl) return;
    expect(readRepoFile(join(dir, tmpl))).toMatch(/syntax\s*=\s*"proto3"\s*;/);
  });

  test('1.5-UNIT-099: proto template package he.${DOMAIN}.v1', () => {
    const dir = `${TPL_ROOT}/proto`;
    if (!repoFileExists(dir)) return;
    const tmpl = readdirSync(repoPath(dir)).find((f) => f.endsWith('.proto.tmpl'));
    if (!tmpl) return;
    expect(readRepoFile(join(dir, tmpl))).toMatch(/package\s+he\.(\$\{?DOMAIN\}?|\{\{DOMAIN\}\})\.v1\s*;/);
  });

  test('1.5-UNIT-100: proto template go_package option canonical form', () => {
    const dir = `${TPL_ROOT}/proto`;
    if (!repoFileExists(dir)) return;
    const tmpl = readdirSync(repoPath(dir)).find((f) => f.endsWith('.proto.tmpl'));
    if (!tmpl) return;
    expect(readRepoFile(join(dir, tmpl))).toMatch(
      /option\s+go_package\s*=\s*"github\.com\/he-api\/he-api\/packages\/proto\/gen\/go\/he\/.*\/v1;/,
    );
  });

  test('1.5-UNIT-101: proto template Ping rpc contract', () => {
    const dir = `${TPL_ROOT}/proto`;
    if (!repoFileExists(dir)) return;
    const tmpl = readdirSync(repoPath(dir)).find((f) => f.endsWith('.proto.tmpl'));
    if (!tmpl) return;
    expect(readRepoFile(join(dir, tmpl))).toMatch(
      /rpc\s+Ping\s*\(\s*PingRequest\s*\)\s+returns\s*\(\s*PingResponse\s*\)/,
    );
  });

  test('1.5-UNIT-102: proto template defines PingRequest + PingResponse with string fields', () => {
    const dir = `${TPL_ROOT}/proto`;
    if (!repoFileExists(dir)) return;
    const tmpl = readdirSync(repoPath(dir)).find((f) => f.endsWith('.proto.tmpl'));
    if (!tmpl) return;
    const src = readRepoFile(join(dir, tmpl));
    expect(src).toMatch(/message\s+PingRequest\s*\{[\s\S]*?string\s+\w+/);
    expect(src).toMatch(/message\s+PingResponse\s*\{[\s\S]*?string\s+\w+/);
  });
});

describe('AC1.B / T3: Dogfood vendored proto code (Q6)', () => {
  test('1.5-UNIT-110: packages/proto/gen/go/he/sample/v1/sample.pb.go exists', () => {
    expect(repoFileExists('packages/proto/gen/go/he/sample/v1/sample.pb.go')).toBe(true);
  });

  test('1.5-UNIT-111: at least one *.connect.go file under gen/go/he/sample/v1/', () => {
    const dir = 'packages/proto/gen/go/he/sample/v1';
    if (!repoFileExists(dir)) {
      expect(false).toBe(true);
      return;
    }
    const allFiles: string[] = [];
    const walk = (rel: string): void => {
      for (const e of readdirSync(repoPath(rel))) {
        const full = join(rel, e);
        const s = statSync(repoPath(full));
        if (s.isDirectory()) walk(full);
        else allFiles.push(full);
      }
    };
    walk(dir);
    expect(allFiles.some((f) => f.endsWith('.connect.go'))).toBe(true);
  });

  test('1.5-UNIT-112: sample.pb.go is auto-generated', () => {
    expect(readRepoFile('packages/proto/gen/go/he/sample/v1/sample.pb.go')).toMatch(
      /Code generated|DO NOT EDIT/,
    );
  });

  test('1.5-UNIT-113: source proto file packages/proto/he/sample/v1/sample.proto exists', () => {
    expect(repoFileExists(SAMPLE_PROTO)).toBe(true);
  });
});

describe('AC1.B / T4: Helm chart templates (Q7 ruling)', () => {
  const H = `${TPL_ROOT}/helm`;

  test('1.5-UNIT-120: Chart.yaml.tmpl exists', () => {
    expect(repoFileExists(`${H}/Chart.yaml.tmpl`)).toBe(true);
  });

  test('1.5-UNIT-121: values.yaml.tmpl exists', () => {
    expect(repoFileExists(`${H}/values.yaml.tmpl`)).toBe(true);
  });

  test('1.5-UNIT-122: values-staging.yaml.tmpl exists', () => {
    expect(repoFileExists(`${H}/values-staging.yaml.tmpl`)).toBe(true);
  });

  test('1.5-UNIT-123: templates/deployment.yaml.tmpl exists', () => {
    expect(repoFileExists(`${H}/templates/deployment.yaml.tmpl`)).toBe(true);
  });

  test('1.5-UNIT-124: deployment.yaml.tmpl contains literal runAsNonRoot: true', () => {
    expect(readRepoFile(`${H}/templates/deployment.yaml.tmpl`)).toMatch(/^\s*runAsNonRoot:\s*true\s*$/m);
  });

  test('1.5-UNIT-125: deployment.yaml.tmpl contains literal runAsUser: 65532', () => {
    expect(readRepoFile(`${H}/templates/deployment.yaml.tmpl`)).toMatch(/^\s*runAsUser:\s*65532\s*$/m);
  });

  test('1.5-UNIT-126: deployment.yaml.tmpl contains literal readOnlyRootFilesystem: true', () => {
    expect(readRepoFile(`${H}/templates/deployment.yaml.tmpl`)).toMatch(/^\s*readOnlyRootFilesystem:\s*true\s*$/m);
  });

  test('1.5-UNIT-127: deployment.yaml.tmpl contains literal allowPrivilegeEscalation: false', () => {
    expect(readRepoFile(`${H}/templates/deployment.yaml.tmpl`)).toMatch(/^\s*allowPrivilegeEscalation:\s*false\s*$/m);
  });

  test('1.5-UNIT-128: deployment.yaml.tmpl contains drop: [-ALL] capabilities', () => {
    const src = readRepoFile(`${H}/templates/deployment.yaml.tmpl`);
    expect(src).toMatch(/drop:\s*(\n\s*-\s*ALL|\[\s*ALL\s*\])/);
  });

  test('1.5-UNIT-129: deployment.yaml.tmpl contains seccompProfile RuntimeDefault', () => {
    const src = readRepoFile(`${H}/templates/deployment.yaml.tmpl`);
    expect(src).toMatch(/seccompProfile:[\s\S]*?type:\s*RuntimeDefault/);
  });

  test('1.5-UNIT-130: PSR fields are NOT wrapped in {{- }} Helm expressions', () => {
    const src = readRepoFile(`${H}/templates/deployment.yaml.tmpl`);
    expect(src).not.toMatch(/\{\{-?\s*[^}]*runAsNonRoot/);
    expect(src).not.toMatch(/\{\{-?\s*[^}]*runAsUser/);
    expect(src).not.toMatch(/\{\{-?\s*[^}]*readOnlyRootFilesystem/);
    expect(src).not.toMatch(/\{\{-?\s*[^}]*allowPrivilegeEscalation/);
  });

  test('1.5-UNIT-131: deployment.yaml.tmpl declares container port 8080', () => {
    expect(readRepoFile(`${H}/templates/deployment.yaml.tmpl`)).toMatch(/containerPort:\s*8080/);
  });

  test('1.5-UNIT-132: service.yaml.tmpl exists with port 8080 + ClusterIP', () => {
    const F = `${H}/templates/service.yaml.tmpl`;
    expect(repoFileExists(F)).toBe(true);
    const src = readRepoFile(F);
    expect(src).toMatch(/port:\s*8080/);
    expect(src).toMatch(/type:\s*ClusterIP/);
  });

  test('1.5-UNIT-133: serviceaccount.yaml.tmpl exists', () => {
    expect(repoFileExists(`${H}/templates/serviceaccount.yaml.tmpl`)).toBe(true);
  });

  test('1.5-UNIT-134: servicemonitor.yaml.tmpl scrapes /metrics on port 8080', () => {
    const F = `${H}/templates/servicemonitor.yaml.tmpl`;
    expect(repoFileExists(F)).toBe(true);
    const src = readRepoFile(F);
    expect(src).toMatch(/path:\s*\/metrics/);
    expect(src).toMatch(/port:\s*(http|8080|metrics)/);
  });

  test('1.5-UNIT-135: servicemonitor.yaml.tmpl interval 15s', () => {
    expect(readRepoFile(`${H}/templates/servicemonitor.yaml.tmpl`)).toMatch(/interval:\s*15s/);
  });

  test('1.5-UNIT-136: _helpers.tpl.tmpl exists', () => {
    expect(repoFileExists(`${H}/templates/_helpers.tpl.tmpl`)).toBe(true);
  });
});

describe('AC1.B / T4: Dogfood rendered Helm chart (Q6 + Q7 evidence)', () => {
  test('1.5-UNIT-140: infra/helm/sample-grpc-app/Chart.yaml exists', () => {
    expect(repoFileExists(`${SAMPLE_CHART}/Chart.yaml`)).toBe(true);
  });

  test('1.5-UNIT-141: values.yaml exists', () => {
    expect(repoFileExists(`${SAMPLE_CHART}/values.yaml`)).toBe(true);
  });

  test('1.5-UNIT-142: values-staging.yaml exists', () => {
    expect(repoFileExists(`${SAMPLE_CHART}/values-staging.yaml`)).toBe(true);
  });

  test('1.5-UNIT-143: rendered deployment.yaml has all 6 PSR literal fields', () => {
    const F = `${SAMPLE_CHART}/templates/deployment.yaml`;
    expect(repoFileExists(F)).toBe(true);
    const src = readRepoFile(F);
    expect(src).toMatch(/runAsNonRoot:\s*true/);
    expect(src).toMatch(/runAsUser:\s*65532/);
    expect(src).toMatch(/readOnlyRootFilesystem:\s*true/);
    expect(src).toMatch(/allowPrivilegeEscalation:\s*false/);
    expect(src).toMatch(/drop:\s*(\n\s*-\s*ALL|\[\s*ALL\s*\])/);
    expect(src).toMatch(/seccompProfile:[\s\S]*?RuntimeDefault/);
  });

  test('1.5-UNIT-144: rendered servicemonitor.yaml exists', () => {
    expect(repoFileExists(`${SAMPLE_CHART}/templates/servicemonitor.yaml`)).toBe(true);
  });
});

describe('AC1.B / T5: Observability shared package (Q5 ruling)', () => {
  test('1.5-UNIT-150: go.mod exists AND module path is correct', () => {
    const F = `${OBS_ROOT}/go.mod`;
    expect(repoFileExists(F)).toBe(true);
    expect(readRepoFile(F)).toMatch(
      /^module\s+github\.com\/he-api\/he-api\/packages\/go-observability\s*$/m,
    );
  });

  test('1.5-UNIT-151: go.mod declares go 1.22+', () => {
    const m = readRepoFile(`${OBS_ROOT}/go.mod`).match(/^go\s+1\.(\d+)/m);
    expect(m).not.toBeNull();
    expect(Number(m![1])).toBeGreaterThanOrEqual(22);
  });

  test('1.5-UNIT-152: tracer.go has NewTracerProvider', () => {
    const F = `${OBS_ROOT}/tracer.go`;
    expect(repoFileExists(F)).toBe(true);
    expect(readRepoFile(F)).toMatch(/func\s+NewTracerProvider\s*\(/);
  });

  test('1.5-UNIT-153: logger.go has NewLogger', () => {
    const F = `${OBS_ROOT}/logger.go`;
    expect(repoFileExists(F)).toBe(true);
    expect(readRepoFile(F)).toMatch(/func\s+NewLogger\s*\(/);
  });

  test('1.5-UNIT-154: logger.go has TraceContextHandler (or equivalent slog handler with trace_id extraction)', () => {
    const src = readRepoFile(`${OBS_ROOT}/logger.go`);
    expect(src).toMatch(/TraceContextHandler|trace_id/);
  });

  test('1.5-UNIT-155: http.go has WrapHTTPHandler', () => {
    const F = `${OBS_ROOT}/http.go`;
    expect(repoFileExists(F)).toBe(true);
    expect(readRepoFile(F)).toMatch(/func\s+WrapHTTPHandler\s*\(/);
  });

  test('1.5-UNIT-156: http.go references otelhttp', () => {
    expect(readRepoFile(`${OBS_ROOT}/http.go`)).toMatch(/otelhttp/);
  });

  test('1.5-UNIT-157: http.go references promhttp', () => {
    expect(readRepoFile(`${OBS_ROOT}/http.go`)).toMatch(/promhttp/);
  });

  test('1.5-UNIT-158: at least 4 *_test.go files in packages/go-observability/', () => {
    if (!repoFileExists(OBS_ROOT)) {
      expect(false).toBe(true);
      return;
    }
    const tests = readdirSync(repoPath(OBS_ROOT)).filter((f) => f.endsWith('_test.go'));
    expect(tests.length).toBeGreaterThanOrEqual(4);
  });

  test('1.5-UNIT-159: go.work use block contains ./packages/go-observability', () => {
    expect(readRepoFile('go.work')).toMatch(/\.\/packages\/go-observability/);
  });
});

describe('AC1.B / T6: Dogfood sample-grpc-app (Q6 ruling)', () => {
  test('1.5-UNIT-170: cmd/server/main.go exists', () => {
    expect(repoFileExists(`${SAMPLE_APP}/cmd/server/main.go`)).toBe(true);
  });

  test('1.5-UNIT-171: cmd/server/main_test.go exists', () => {
    expect(repoFileExists(`${SAMPLE_APP}/cmd/server/main_test.go`)).toBe(true);
  });

  test('1.5-UNIT-172: go.mod module path canonical', () => {
    expect(readRepoFile(`${SAMPLE_APP}/go.mod`)).toMatch(
      /^module\s+github\.com\/he-api\/he-api\/apps\/sample-grpc-app\s*$/m,
    );
  });

  test('1.5-UNIT-173: Dockerfile uses unsuffixed distroless + USER 65532 literal (m-4 parity)', () => {
    const F = `${SAMPLE_APP}/Dockerfile`;
    expect(repoFileExists(F)).toBe(true);
    const src = readRepoFile(F);
    expect(src).toMatch(/FROM\s+gcr\.io\/distroless\/static-debian12\b(?!:nonroot)/);
    expect(src).toMatch(/^USER\s+65532\s*$/m);
  });

  test('1.5-UNIT-174: turbo.json exists', () => {
    expect(repoFileExists(`${SAMPLE_APP}/turbo.json`)).toBe(true);
  });

  test('1.5-UNIT-175: package.json contains literal m-3 build stub (template-to-render parity)', () => {
    expect(readRepoFile(`${SAMPLE_APP}/package.json`)).toMatch(
      /"build"\s*:\s*"echo \\"go build is run via go workspace, not Turborepo\\" && exit 0"/,
    );
  });

  test('1.5-UNIT-176: internal/.gitkeep exists (m-5 dogfood)', () => {
    expect(repoFileExists(`${SAMPLE_APP}/internal/.gitkeep`)).toBe(true);
  });

  test('1.5-UNIT-177: main.go imports packages/go-observability', () => {
    expect(readRepoFile(`${SAMPLE_APP}/cmd/server/main.go`)).toMatch(
      /github\.com\/he-api\/he-api\/packages\/go-observability/,
    );
  });

  test('1.5-UNIT-178: go.work use block contains ./apps/sample-grpc-app', () => {
    expect(readRepoFile('go.work')).toMatch(/\.\/apps\/sample-grpc-app/);
  });

  test('1.5-UNIT-179: main.go imports vendored proto gen for sample', () => {
    expect(readRepoFile(`${SAMPLE_APP}/cmd/server/main.go`)).toMatch(
      /packages\/proto\/gen\/go\/he\/sample\/v1/,
    );
  });

  test('1.5-UNIT-180: source-tree.md registers apps/sample-grpc-app/ (m-2)', () => {
    expect(readRepoFile('docs/architecture/source-tree.md')).toMatch(/apps\/sample-grpc-app\//);
  });

  test('1.5-UNIT-181: source-tree.md updated to he/<domain>/v1/<service>.proto (m-1)', () => {
    expect(readRepoFile('docs/architecture/source-tree.md')).toMatch(/he\/<domain>\/v1\/<service>\.proto/);
  });
});

// ============================================================
// AC1.C: 端到端 5 分钟约束
// ============================================================

describe('AC1.C / T7: README "Scaffolding a new gRPC service" section', () => {
  const section = (): string => {
    const readme = repoFileExists('README.md') ? readRepoFile('README.md') : '';
    const parts = readme.split(/##\s+Scaffolding a new gRPC service/i);
    return parts[1] ?? '';
  };

  test('1.5-UNIT-190: README has Scaffolding section', () => {
    expect(readRepoFile('README.md')).toMatch(/##\s+Scaffolding a new gRPC service/i);
  });

  test('1.5-UNIT-191: section references scripts/scaffold-svc.sh', () => {
    expect(section()).toMatch(/scripts\/scaffold-svc\.sh/);
  });

  test('1.5-UNIT-192: section mentions buf generate', () => {
    expect(section()).toMatch(/buf generate/);
  });

  test('1.5-UNIT-193: section mentions helm install', () => {
    expect(section()).toMatch(/helm install/);
  });

  test('1.5-UNIT-194: section mentions kubectl get pod', () => {
    expect(section()).toMatch(/kubectl get pod/);
  });

  test('1.5-UNIT-195: section mentions build-images.yml manual append', () => {
    expect(section()).toMatch(/build-images\.yml/);
  });

  test('1.5-UNIT-196: section lists prerequisites Go/buf/helm/kubectl', () => {
    const s = section();
    expect(s).toMatch(/Go\s*1\.22/);
    expect(s.toLowerCase()).toMatch(/\bbuf\b/);
    expect(s.toLowerCase()).toMatch(/\bhelm\b/);
    expect(s.toLowerCase()).toMatch(/\bkubectl\b/);
  });

  test('1.5-UNIT-197: section mentions three connect-go protocols', () => {
    expect(section()).toMatch(/Connect|JSON|gRPC binary|gRPC-Web/);
  });
});

// ============================================================
// AC1.D: Observability 接入与 1.4 契约一致
// ============================================================

describe('AC1.D: Cross-deliverable observability wire-up (Q5 + AC1.D)', () => {
  test('1.5-UNIT-200: main.go.tmpl wires obs in ≤ 3 obs.* call lines', () => {
    const src = readRepoFile(`${TPL_ROOT}/cmd/server/main.go.tmpl`);
    const obsLines = src
      .split('\n')
      .filter((l) => !l.trim().startsWith('//'))
      .filter((l) => /\bobs\./.test(l) || /\.NewTracerProvider|\.NewLogger|\.WrapHTTPHandler/.test(l));
    expect(obsLines.length).toBeLessThanOrEqual(8); // 3 calls * ~2 lines each (formatted) + tolerance
  });

  test('1.5-UNIT-201: sample-grpc-app/cmd/server/main.go makes same 3 obs calls', () => {
    const src = readRepoFile(`${SAMPLE_APP}/cmd/server/main.go`);
    expect(src).toMatch(/\.NewTracerProvider\s*\(/);
    expect(src).toMatch(/\.NewLogger\s*\(/);
    expect(src).toMatch(/\.WrapHTTPHandler\s*\(/);
  });

  test('1.5-UNIT-202: http.go registers /metrics path', () => {
    expect(readRepoFile(`${OBS_ROOT}/http.go`)).toMatch(/"\/metrics"/);
  });

  test('1.5-UNIT-203: logger.go outputs JSON via slog.NewJSONHandler', () => {
    expect(readRepoFile(`${OBS_ROOT}/logger.go`)).toMatch(/slog\.NewJSONHandler/);
  });

  test('1.5-UNIT-204: logger.go injects trace_id AND span_id', () => {
    const src = readRepoFile(`${OBS_ROOT}/logger.go`);
    expect(src).toMatch(/trace_id/);
    expect(src).toMatch(/span_id/);
  });
});

// ============================================================
// AC1.E: CI 与 go.work 注册（Q8 PARTIAL）
// ============================================================

describe('AC1.E / T7: CI matrix refactor + go.work registration (Q8)', () => {
  test('1.5-UNIT-210: build-images.yml uses strategy.matrix', () => {
    expect(readRepoFile('.github/workflows/build-images.yml')).toMatch(/strategy:\s*\n\s*matrix:/);
  });

  test('1.5-UNIT-211: build-images.yml matrix.svc contains all 3 initial entries', () => {
    const src = readRepoFile('.github/workflows/build-images.yml');
    expect(src).toMatch(/api-gateway/);
    expect(src).toMatch(/sample-otel-app/);
    expect(src).toMatch(/sample-grpc-app/);
  });

  test('1.5-UNIT-212: infra-lint.yml has helm-lint-services job', () => {
    expect(readRepoFile('.github/workflows/infra-lint.yml')).toMatch(/^\s*helm-lint-services:/m);
  });

  test('1.5-UNIT-213: helm-lint-services matrix contains sample-grpc-app', () => {
    const src = readRepoFile('.github/workflows/infra-lint.yml');
    const idx = src.search(/^\s*helm-lint-services:/m);
    expect(idx).toBeGreaterThan(0);
    expect(src.slice(idx)).toMatch(/sample-grpc-app/);
  });

  test('1.5-UNIT-214: go.work contains both ./packages/go-observability AND ./apps/sample-grpc-app', () => {
    const src = readRepoFile('go.work');
    expect(src).toMatch(/\.\/packages\/go-observability/);
    expect(src).toMatch(/\.\/apps\/sample-grpc-app/);
  });

  test('1.5-UNIT-215: CI workflow contains buf generate drift detection', () => {
    const wfs = ['.github/workflows/test.yml', '.github/workflows/infra-lint.yml'];
    const found = wfs.some(
      (p) => repoFileExists(p) && /buf generate[\s\S]*git diff[\s\S]*packages\/proto\/gen/.test(readRepoFile(p)),
    );
    expect(found).toBe(true);
  });

  test('1.5-UNIT-216: build-images.yml matrix has no duplicate svc entries', () => {
    const src = readRepoFile('.github/workflows/build-images.yml');
    const matches = src.match(/-\s*(api-gateway|sample-otel-app|sample-grpc-app)/g) ?? [];
    expect(new Set(matches).size).toBe(matches.length);
  });
});

// ============================================================
// Cross-cutting traceability invariants
// ============================================================

describe('Cross-cutting: Architect Round 1/2 traceability invariants', () => {
  test('1.5-UNIT-220: Story body retains Q1-Q8 Rulings Traceability table', () => {
    expect(readRepoFile(STORY_FILE)).toMatch(/Q1-Q8 Rulings Traceability/);
  });

  test('1.5-UNIT-221: Change Log contains Created / RequiresRevision / Round 2 transitions', () => {
    const src = readRepoFile(STORY_FILE);
    expect(src).toMatch(/Created/);
    expect(src).toMatch(/RequiresRevision/);
    expect(src).toMatch(/Round 2/);
  });

  test('1.5-UNIT-222: all .tmpl deliverables collectively reference {{NAME}} AND {{DOMAIN}} tokens', () => {
    if (!repoFileExists(TPL_ROOT)) {
      expect(false).toBe(true);
      return;
    }
    const allTmpl: string[] = [];
    const walk = (rel: string): void => {
      for (const e of readdirSync(repoPath(rel))) {
        const full = join(rel, e);
        const s = statSync(repoPath(full));
        if (s.isDirectory()) walk(full);
        else if (full.endsWith('.tmpl')) allTmpl.push(full);
      }
    };
    walk(TPL_ROOT);
    const allSrc = allTmpl.map((f) => readRepoFile(f)).join('\n');
    expect(allSrc).toMatch(/\{\{NAME\}\}|\$\{NAME\}/);
    expect(allSrc).toMatch(/\{\{DOMAIN\}\}|\$\{DOMAIN\}/);
  });
});

// ============================================================
// Integration scenarios (PR-driven / local — runtime skips)
// ============================================================

describe('Integration: cross-workspace toolchain (PR run)', () => {
  test.skip(`1.5-INT-001: go build ./... exits 0 across workspace — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-002: go test ./... exits 0 incl. ≥4 obs pkg tests — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-003: go vet ./... exits 0 — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-004: golangci-lint run ./... exits 0 — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-005: cd packages/proto && buf lint exits 0 — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-006: buf generate && git diff --exit-code drift detection — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-007: helm lint infra/helm/sample-grpc-app exits 0 — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-008: helm template | kubeconform -strict exits 0 — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-009: PR Run infra-lint.yml helm-lint-services matrix green — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-010: PR Run build-images.yml matrix builds all 3 entries — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-011: bash -n scripts/scaffold-svc.sh syntax check exits 0 — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-012: scaffold _throwaway → full toolchain green (T8 self-test) — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-013: re-scaffold existing name → non-zero + "already exists" + no diff — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-INT-014: scaffold with bad --name (uppercase / digit-start / 32+ chars) → non-zero + usage — ${SKIP_REASON} §Integration`, () => {});
});

// ============================================================
// E2E scenarios (staging cluster — runtime skips)
// ============================================================

describe('E2E: 5-minute SLA + observability evidence (staging)', () => {
  test.skip(`1.5-E2E-001: AC1.C — t3 - t0 ≤ 5min wall-clock + ≤5 manual commands — ${SKIP_REASON} §E2E`, () => {});
  test.skip(`1.5-E2E-002: AC1.D — Grafana Jaeger trace by service.name=sample-grpc-app — ${SKIP_REASON} §E2E`, () => {});
  test.skip(`1.5-E2E-003: AC1.D — Prometheus up{job="sample-grpc-app"}=1 — ${SKIP_REASON} §E2E`, () => {});
  test.skip(`1.5-E2E-004: AC1.D — curl pod:8080/metrics returns 200 + http_server_request_duration_seconds_* — ${SKIP_REASON} §E2E`, () => {});
  test.skip(`1.5-E2E-005: AC1.D — kubectl logs shows JSON with trace_id field — ${SKIP_REASON} §E2E`, () => {});
  test.skip(`1.5-E2E-006: AC1.D — kubectl get servicemonitor includes sample-grpc-app — ${SKIP_REASON} §E2E`, () => {});
  test.skip(`1.5-E2E-007: AC1.C — CI 5-min SLA job (timeout 300s) green on standard runner — ${SKIP_REASON} §E2E`, () => {});
});

// ============================================================
// Blind-Spot scenarios [BLIND-SPOT]
// ============================================================

describe('[BLIND-SPOT] BOUNDARY: scaffold-svc.sh argument validation', () => {
  test.skip(`1.5-BLIND-BOUNDARY-001: --name "" → non-zero + usage; no mutation — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-BOUNDARY-002: --name "a" (1-char min) → succeeds — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-BOUNDARY-003: --name 31-char (max boundary) → succeeds — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-BOUNDARY-004: --name 32-char (just-beyond) → non-zero — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-BOUNDARY-005: --name "Auth-Svc" (uppercase) → non-zero — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-BOUNDARY-006: --name "9auth" (leading digit) → non-zero — ${SKIP_REASON} §Integration`, () => {});
});

describe('[BLIND-SPOT] ERROR: scaffold/buf/obs failure modes', () => {
  test.skip(`1.5-BLIND-ERROR-001: mid-execution failure (chmod -w apps/) → trap cleanup, no partial files — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-ERROR-002: buf generate failure (malformed proto) → non-zero + $STAGING clean — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-ERROR-003: empty OTLP endpoint env → tracer fallback no-op, no panic — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-ERROR-004: WrapHTTPHandler(nil) defensive guard — ${SKIP_REASON} §Integration`, () => {});
});

describe('[BLIND-SPOT] FLOW: atomicity + sequencing', () => {
  test.skip(`1.5-BLIND-FLOW-001: SIGTERM mid-scaffold → trap fires, repo diff empty — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-FLOW-002: parallel same-name scaffold → exactly one succeeds — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-FLOW-003: buf generate runs AFTER proto mv (ordering invariant) — ${SKIP_REASON} §Integration`, () => {});
});

describe('[BLIND-SPOT] CONCURRENCY: parallel scaffold', () => {
  test.skip(`1.5-BLIND-CONCURRENCY-001: parallel different-name scaffold → both succeed, go.work has both — ${SKIP_REASON} §Integration`, () => {});
});

describe('[BLIND-SPOT] DATA: registration consistency', () => {
  test.skip(`1.5-BLIND-DATA-001: go env GOWORK parse-valid after scaffold append — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-DATA-002: infra-lint.yml matrix idempotent (no duplicate sample-grpc-app) — ${SKIP_REASON} §Integration`, () => {});
  test.skip(`1.5-BLIND-DATA-003: build-images.yml YAML parses after manual append — ${SKIP_REASON} §Integration`, () => {});
});

describe('[BLIND-SPOT] RESOURCE: cleanup + shutdown', () => {
  test.skip(`1.5-BLIND-RESOURCE-001: $STAGING removed on all exit paths (incl. SIGTERM) — ${SKIP_REASON} §Integration`, () => {});
  test('1.5-BLIND-RESOURCE-002: main.go.tmpl Server.Shutdown(ctx) called within 5s', () => {
    const src = readRepoFile(`${TPL_ROOT}/cmd/server/main.go.tmpl`);
    expect(src).toMatch(/\.Shutdown\s*\(/);
    expect(src).toMatch(/5\s*\*\s*time\.Second/);
  });
  test('1.5-BLIND-RESOURCE-003: main.go.tmpl defers TracerProvider Shutdown', () => {
    const src = readRepoFile(`${TPL_ROOT}/cmd/server/main.go.tmpl`);
    expect(src).toMatch(/defer\s+[^\n]*\.Shutdown\s*\(/);
  });
});
