/**
 * Test skeleton for Story 1.6: 数据库基础（Postgres + Redis + ClickHouse）
 *
 * AUTO-GENERATED by QA Test Design (Turing, 2026-05-11). Dev MUST keep every
 * static (Unit) scenario passing once the corresponding deliverable lands;
 * runtime / CI / E2E scenarios stay `test.skip` with a pointer to
 * `docs/dev/logs/1.6-dev-log.md` §Integration / §E2E.
 *
 * Static scenarios parse:
 *   - Terraform module HCL (`infra/terraform/modules/{rds-postgres,redis-tair,clickhouse}/{main,variables,outputs,versions}.tf`) via raw text + regex
 *   - envs/staging wiring (`infra/terraform/envs/staging/{main,variables,outputs}.tf`) via raw text + regex
 *   - Migration files (`migrations/postgres/{atlas.hcl,0001_baseline.sql}`, `migrations/clickhouse/001_baseline.{up,down}.sql`) via raw text + regex
 *   - Bash scripts (`scripts/db-migrate.sh`, `scripts/db-doctor.sh`, `scripts/db-doctor/probes/redis-ping.sh`) via raw text + regex + stat mode
 *   - SQL probes (`scripts/db-doctor/probes/{postgres,clickhouse}.sql`) via raw text
 *   - Helm chart (`infra/helm/db-doctor/{Chart.yaml,values.yaml,templates/*.yaml}`) via raw text + selective YAML parse
 *   - CI workflow (`.github/workflows/db-migrate-check.yml`) via YAML parse + raw text
 *   - Operator docs (`docs/architecture/database-bootstrap.md`, `docs/architecture/source-tree.md`, `README.md`) via raw text
 *   - Story body for traceability invariants
 *
 * Test Design: docs/qa/assessments/1.6-test-design-20260511.md
 */

import { describe, expect, test } from 'vitest';
import { readFileSync, existsSync, statSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..', '..', '..');

const repoPath = (rel: string): string => resolve(REPO_ROOT, rel);
const repoFileExists = (rel: string): boolean => existsSync(repoPath(rel));
const readRepoFile = (rel: string): string => readFileSync(repoPath(rel), 'utf8');
const loadYaml = <T = unknown>(rel: string): T => parseYaml(readRepoFile(rel)) as T;
const isExecutable = (rel: string): boolean => (statSync(repoPath(rel)).mode & 0o100) !== 0;

const TF_PG = 'infra/terraform/modules/rds-postgres';
const TF_REDIS = 'infra/terraform/modules/redis-tair';
const TF_CH = 'infra/terraform/modules/clickhouse';
const TF_ENVS = 'infra/terraform/envs/staging';
const MIG_PG = 'migrations/postgres';
const MIG_CH = 'migrations/clickhouse';
const DB_MIGRATE = 'scripts/db-migrate.sh';
const DB_DOCTOR = 'scripts/db-doctor.sh';
const PROBES = 'scripts/db-doctor/probes';
const HELM_CHART = 'infra/helm/db-doctor';
const CI_DB_MIGRATE = '.github/workflows/db-migrate-check.yml';
const DOC_BOOT = 'docs/architecture/database-bootstrap.md';
const DOC_TREE = 'docs/architecture/source-tree.md';
const README = 'README.md';

const SKIP_REASON = 'runtime/CI/E2E scenario — see docs/dev/logs/1.6-dev-log.md';

// ============================================================
// AC1: Terraform three DB modules + envs/staging integration (Q4)
// ============================================================

describe('AC1 / T1a: Terraform module — rds-postgres', () => {
  test('1.6-UNIT-001: directory exists', () => {
    expect(existsSync(repoPath(TF_PG))).toBe(true);
  });
  test('1.6-UNIT-002: main.tf exists', () => {
    expect(repoFileExists(`${TF_PG}/main.tf`)).toBe(true);
  });
  test('1.6-UNIT-003: variables.tf exists', () => {
    expect(repoFileExists(`${TF_PG}/variables.tf`)).toBe(true);
  });
  test('1.6-UNIT-004: outputs.tf exists', () => {
    expect(repoFileExists(`${TF_PG}/outputs.tf`)).toBe(true);
  });
  test('1.6-UNIT-005: versions.tf exists', () => {
    expect(repoFileExists(`${TF_PG}/versions.tf`)).toBe(true);
  });
  test('1.6-UNIT-006: main.tf references RDS instance resource', () => {
    expect(readRepoFile(`${TF_PG}/main.tf`)).toMatch(/alicloud_db_instance|aliyun_rds_instance/);
  });
  test('1.6-UNIT-007: engine pinned to PostgreSQL 16+', () => {
    const src = readRepoFile(`${TF_PG}/main.tf`);
    expect(src).toMatch(/engine\s*=\s*"PostgreSQL"/);
    expect(src).toMatch(/engine_version\s*=\s*"?16(\.\d+)?"?/);
  });
  test('1.6-UNIT-008: multi-AZ via HighAvailability category or zone_id_slave', () => {
    const src = readRepoFile(`${TF_PG}/main.tf`);
    expect(src).toMatch(/category\s*=\s*"HighAvailability"|zone_id_slave/);
  });
  test('1.6-UNIT-009: TLS enforced (force_ssl or rds_force_ssl)', () => {
    const src = readRepoFile(`${TF_PG}/main.tf`);
    expect(src).toMatch(/force_ssl\s*=\s*true|rds_force_ssl/);
  });
  test('1.6-UNIT-010: KMS encryption_key or TDE enabled', () => {
    const src = readRepoFile(`${TF_PG}/main.tf`);
    expect(src).toMatch(/encryption_key|tde_status\s*=\s*"Enabled"/);
  });
  test('1.6-UNIT-011: no 0.0.0.0/0 in security_ips', () => {
    expect(readRepoFile(`${TF_PG}/main.tf`)).not.toMatch(/0\.0\.0\.0\/0/);
  });
  test('1.6-UNIT-012: variables.tf declares vpc_id / vswitch / kms_key_id', () => {
    const src = readRepoFile(`${TF_PG}/variables.tf`);
    expect(src).toMatch(/variable\s+"vpc_id"/);
    expect(src).toMatch(/variable\s+"vswitch_ids?"/);
    expect(src).toMatch(/variable\s+"kms_key_id"/);
  });
  test('1.6-UNIT-013: instance_class default pg.n2.medium.2c', () => {
    expect(readRepoFile(`${TF_PG}/variables.tf`)).toMatch(/pg\.n2\.medium\.2c/);
  });
  test('1.6-UNIT-014: outputs.tf exports endpoint + port + app_user', () => {
    const src = readRepoFile(`${TF_PG}/outputs.tf`);
    expect(src).toMatch(/output\s+"endpoint"/);
    expect(src).toMatch(/output\s+"port"/);
    expect(src).toMatch(/output\s+"app_user"/);
  });
  test('1.6-UNIT-015: outputs.tf does NOT expose password', () => {
    expect(readRepoFile(`${TF_PG}/outputs.tf`)).not.toMatch(/output\s+"\w*password\w*"/);
  });
  test('1.6-UNIT-016: outputs.tf endpoint sources from connection_string / host', () => {
    expect(readRepoFile(`${TF_PG}/outputs.tf`)).toMatch(/connection_string|\.host\b/);
  });
  test('1.6-UNIT-017: backup_retention_period = 7', () => {
    expect(readRepoFile(`${TF_PG}/main.tf`)).toMatch(/backup_retention_period\s*=\s*7/);
  });
  test('1.6-UNIT-018: versions.tf pins required_version >= 1.7', () => {
    expect(readRepoFile(`${TF_PG}/versions.tf`)).toMatch(/required_version\s*=\s*">=\s*1\.7|~>\s*1\.7/);
  });
});

describe('AC1 / T1b: Terraform module — redis-tair', () => {
  test('1.6-UNIT-020: directory exists', () => {
    expect(existsSync(repoPath(TF_REDIS))).toBe(true);
  });
  test('1.6-UNIT-021: four-file layout', () => {
    expect(repoFileExists(`${TF_REDIS}/main.tf`)).toBe(true);
    expect(repoFileExists(`${TF_REDIS}/variables.tf`)).toBe(true);
    expect(repoFileExists(`${TF_REDIS}/outputs.tf`)).toBe(true);
    expect(repoFileExists(`${TF_REDIS}/versions.tf`)).toBe(true);
  });
  test('1.6-UNIT-022: references alicloud_kvstore_instance', () => {
    expect(readRepoFile(`${TF_REDIS}/main.tf`)).toMatch(/alicloud_kvstore_instance/);
  });
  test('1.6-UNIT-023: engine_version 7.0 or 7.2', () => {
    expect(readRepoFile(`${TF_REDIS}/main.tf`)).toMatch(/engine_version\s*=\s*"?7\.[02]"?/);
  });
  test('1.6-UNIT-024: TLS enforced (tls_enabled or ssl_enable)', () => {
    expect(readRepoFile(`${TF_REDIS}/main.tf`)).toMatch(/tls_enabled\s*=\s*true|ssl_enable\s*=\s*"Open"/);
  });
  test('1.6-UNIT-025: KMS encryption declared', () => {
    expect(readRepoFile(`${TF_REDIS}/main.tf`)).toMatch(/encryption_key|kms/i);
  });
  test('1.6-UNIT-026: cluster edition (Tair family or cluster architecture)', () => {
    expect(readRepoFile(`${TF_REDIS}/main.tf`)).toMatch(/Tair|architecture_type\s*=\s*"cluster"/);
  });
  test('1.6-UNIT-027: vswitch_id present, no public network', () => {
    const src = readRepoFile(`${TF_REDIS}/main.tf`);
    expect(src).toMatch(/vswitch_id/);
    expect(src).not.toMatch(/0\.0\.0\.0\/0/);
  });
  test('1.6-UNIT-028: outputs export endpoint + port + app_user; no password', () => {
    const src = readRepoFile(`${TF_REDIS}/outputs.tf`);
    expect(src).toMatch(/output\s+"endpoint"/);
    expect(src).toMatch(/output\s+"port"/);
    expect(src).toMatch(/output\s+"app_user"/);
    expect(src).not.toMatch(/output\s+"\w*password\w*"/);
  });
  test('1.6-UNIT-029: instance_class default redis.shard.small.ce', () => {
    expect(readRepoFile(`${TF_REDIS}/variables.tf`)).toMatch(/redis\.shard\.small\.ce/);
  });
  test('1.6-UNIT-030: versions.tf pins required_version >= 1.7', () => {
    expect(readRepoFile(`${TF_REDIS}/versions.tf`)).toMatch(/required_version\s*=\s*">=\s*1\.7|~>\s*1\.7/);
  });
});

describe('AC1 / T1c: Terraform module — clickhouse', () => {
  test('1.6-UNIT-040: directory exists', () => {
    expect(existsSync(repoPath(TF_CH))).toBe(true);
  });
  test('1.6-UNIT-041: four-file layout', () => {
    expect(repoFileExists(`${TF_CH}/main.tf`)).toBe(true);
    expect(repoFileExists(`${TF_CH}/variables.tf`)).toBe(true);
    expect(repoFileExists(`${TF_CH}/outputs.tf`)).toBe(true);
    expect(repoFileExists(`${TF_CH}/versions.tf`)).toBe(true);
  });
  test('1.6-UNIT-042: references alicloud_click_house_db_cluster', () => {
    expect(readRepoFile(`${TF_CH}/main.tf`)).toMatch(/alicloud_click_house_db_cluster|clickhouse/i);
  });
  test('1.6-UNIT-043: db_cluster_version 24+', () => {
    expect(readRepoFile(`${TF_CH}/main.tf`)).toMatch(/db_cluster_version\s*=\s*"?24(\.\d+){0,3}"?/);
  });
  test('1.6-UNIT-044: TLS enforced', () => {
    expect(readRepoFile(`${TF_CH}/main.tf`)).toMatch(/tls_enabled\s*=\s*true|enable_https/);
  });
  test('1.6-UNIT-045: KMS encryption declared', () => {
    expect(readRepoFile(`${TF_CH}/main.tf`)).toMatch(/encryption_key|kms/i);
  });
  test('1.6-UNIT-046: no public network attribute (or empty)', () => {
    const src = readRepoFile(`${TF_CH}/main.tf`);
    expect(src).not.toMatch(/0\.0\.0\.0\/0/);
    expect(src.match(/public_connection_string\s*=\s*"[^"]+"/)).toBeNull();
  });
  test('1.6-UNIT-047: outputs export endpoint + port + app_user; no password', () => {
    const src = readRepoFile(`${TF_CH}/outputs.tf`);
    expect(src).toMatch(/output\s+"endpoint"/);
    expect(src).toMatch(/output\s+"port"/);
    expect(src).toMatch(/output\s+"app_user"/);
    expect(src).not.toMatch(/output\s+"\w*password\w*"/);
  });
  test('1.6-UNIT-048: db_node_class baseline default (2c8g family)', () => {
    expect(readRepoFile(`${TF_CH}/variables.tf`)).toMatch(/db_node_class|node_count/);
  });
  test('1.6-UNIT-049: versions.tf pins required_version >= 1.7', () => {
    expect(readRepoFile(`${TF_CH}/versions.tf`)).toMatch(/required_version\s*=\s*">=\s*1\.7|~>\s*1\.7/);
  });
});

describe('AC1 / T1d: envs/staging integration', () => {
  test('1.6-UNIT-060: envs/staging/main.tf imports rds-postgres module', () => {
    expect(readRepoFile(`${TF_ENVS}/main.tf`)).toMatch(/module\s+"rds_postgres"/);
  });
  test('1.6-UNIT-061: envs/staging/main.tf imports redis-tair module', () => {
    expect(readRepoFile(`${TF_ENVS}/main.tf`)).toMatch(/module\s+"redis_tair"/);
  });
  test('1.6-UNIT-062: envs/staging/main.tf imports clickhouse module', () => {
    expect(readRepoFile(`${TF_ENVS}/main.tf`)).toMatch(/module\s+"clickhouse"/);
  });
  test('1.6-UNIT-063: DB modules wired to vpc module outputs', () => {
    const src = readRepoFile(`${TF_ENVS}/main.tf`);
    expect(src).toMatch(/module\.vpc\.(vpc_id|vswitch)/);
  });
  test('1.6-UNIT-064: DB modules receive kms_key_id', () => {
    expect(readRepoFile(`${TF_ENVS}/main.tf`)).toMatch(/kms_key_id\s*=/);
  });
  test('1.6-UNIT-065: envs/staging/outputs.tf exposes three FQDN endpoints', () => {
    const src = readRepoFile(`${TF_ENVS}/outputs.tf`);
    expect(src).toMatch(/output\s+"postgres_endpoint"/);
    expect(src).toMatch(/output\s+"redis_endpoint"/);
    expect(src).toMatch(/output\s+"clickhouse_endpoint"/);
  });
  test('1.6-UNIT-066: envs/staging/variables.tf declares DB-related sensitive vars', () => {
    expect(readRepoFile(`${TF_ENVS}/variables.tf`)).toMatch(/sensitive\s*=\s*true/);
  });
  test('1.6-UNIT-067: envs/staging does NOT instantiate ArgoCD for db-doctor', () => {
    const src = readRepoFile(`${TF_ENVS}/main.tf`);
    expect(src).not.toMatch(/argocd_application[\s\S]{0,200}db-doctor|db-doctor[\s\S]{0,200}argoproj\.io/);
  });
});

describe('AC1 / Integration + E2E', () => {
  test.skip('1.6-INT-001: tflint --module per DB module exits 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-002: terraform validate per module + envs/staging exits 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-003: tflint required_providers/required_version rules pass', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-001: terraform plan shows 3 resource adds', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-002: terraform apply provisions all three DBs; FQDN endpoints not IPs', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-003: second terraform apply reports No changes (BR-1.5)', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-004: VPC-private DNS resolves to RFC1918 from staging pod', () => {
    throw new Error(SKIP_REASON);
  });
});

// ============================================================
// AC2: K8s Secret credentials (admin + app, namespace + RBAC) — M-1 ruling
// ============================================================

describe('AC2 / T2: Admin K8s Secret (Vault deferred — M-1)', () => {
  test('1.6-UNIT-080: he-api-ops namespace declared via Terraform', () => {
    const src = readRepoFile(`${TF_ENVS}/main.tf`);
    expect(src).toMatch(/kubernetes_namespace[\s\S]{0,200}"he-api-ops"|metadata\s*{\s*name\s*=\s*"he-api-ops"/);
  });
  test('1.6-UNIT-081: ClusterRoleBinding to ops-cluster-admin declared', () => {
    expect(readRepoFile(`${TF_ENVS}/main.tf`)).toMatch(/kubernetes_cluster_role_binding|ops-cluster-admin/);
  });
  test('1.6-UNIT-082: admin Secret declared in he-api-ops namespace', () => {
    const src = readRepoFile(`${TF_ENVS}/main.tf`);
    expect(src).toMatch(/he-api-db-admin-creds/);
    expect(src).toMatch(/namespace\s*=\s*"he-api-ops"/);
  });
  test('1.6-UNIT-083: admin Secret carries ACK KMS envelope annotation', () => {
    expect(readRepoFile(`${TF_ENVS}/main.tf`)).toMatch(/cloud\.alibaba\.com\/kms-encrypted/);
  });
  test('1.6-UNIT-084: admin Secret data keys include three admin passwords', () => {
    const src = readRepoFile(`${TF_ENVS}/main.tf`);
    expect(src).toMatch(/postgres_admin_password/);
    expect(src).toMatch(/redis_admin_password/);
    expect(src).toMatch(/clickhouse_admin_password/);
  });
  test('1.6-UNIT-085: admin Secret type = Opaque', () => {
    expect(readRepoFile(`${TF_ENVS}/main.tf`)).toMatch(/type\s*=\s*"Opaque"/);
  });
  test('1.6-UNIT-086: no Vault path references outside docs/Architect review prose', () => {
    const offenders = ['scripts/db-migrate.sh', 'scripts/db-doctor.sh', `${HELM_CHART}/templates/secret.yaml`];
    for (const f of offenders) {
      if (repoFileExists(f)) {
        expect(readRepoFile(f)).not.toMatch(/vault:\/\/|secret\/he-api\/staging\/db\/[^/]+\/(admin|application)/);
      }
    }
  });
});

describe('AC2 / T3: Application K8s Secret + ACL (M-1)', () => {
  test('1.6-UNIT-090: secret.yaml template exists', () => {
    expect(repoFileExists(`${HELM_CHART}/templates/secret.yaml`)).toBe(true);
  });
  test('1.6-UNIT-091: secret.yaml is plain Kubernetes Secret (NOT ExternalSecret/SealedSecret)', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/secret.yaml`);
    expect(src).toMatch(/kind:\s*Secret\b/);
    expect(src).toMatch(/apiVersion:\s*v1\b/);
    expect(src).not.toMatch(/kind:\s*ExternalSecret|kind:\s*SealedSecret|external-secrets\.io|bitnami\.com/);
  });
  test('1.6-UNIT-092: namespace renders to he-api-staging', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/secret.yaml`);
    expect(src).toMatch(/namespace:\s*(\{\{\s*\.Release\.Namespace\s*\}\}|he-api-staging)/);
  });
  test('1.6-UNIT-093: Secret name is he-api-db-creds', () => {
    expect(readRepoFile(`${HELM_CHART}/templates/secret.yaml`)).toMatch(/name:\s*he-api-db-creds/);
  });
  test('1.6-UNIT-094: ACK KMS envelope annotation present', () => {
    expect(readRepoFile(`${HELM_CHART}/templates/secret.yaml`)).toMatch(/cloud\.alibaba\.com\/kms-encrypted/);
  });
  test('1.6-UNIT-095: data keys include three URIs (BR-2.5 naming)', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/secret.yaml`);
    expect(src).toMatch(/HE_API_DB_POSTGRES_URI/);
    expect(src).toMatch(/HE_API_DB_REDIS_URI/);
    expect(src).toMatch(/HE_API_DB_CLICKHOUSE_URI/);
  });
  test('1.6-UNIT-096: values.yaml sources Secret values from Terraform-injected variables', () => {
    const tpl = readRepoFile(`${HELM_CHART}/templates/secret.yaml`);
    expect(tpl).toMatch(/\{\{\s*\.Values\.(postgres|redis|clickhouse)\.uri/);
  });
  test('1.6-UNIT-097: PG baseline contains psql-variable role grant (NOT Vault placeholder)', () => {
    const src = readRepoFile(`${MIG_PG}/0001_baseline.sql`);
    expect(src).toMatch(/CREATE ROLE he_api LOGIN PASSWORD :'app_password'/);
  });
  test('1.6-UNIT-098: PG baseline grants USAGE on he_api schema + default privileges', () => {
    const src = readRepoFile(`${MIG_PG}/0001_baseline.sql`);
    expect(src).toMatch(/GRANT\s+(USAGE|CREATE|USAGE\s*,\s*CREATE)\s+ON\s+SCHEMA\s+he_api\s+TO\s+he_api/i);
    expect(src).toMatch(/ALTER DEFAULT PRIVILEGES IN SCHEMA he_api/i);
  });
  test('1.6-UNIT-099: PG baseline does NOT grant SUPERUSER/CREATEROLE/CREATEDB to he_api', () => {
    const src = readRepoFile(`${MIG_PG}/0001_baseline.sql`);
    expect(src).not.toMatch(/SUPERUSER|CREATEROLE|CREATEDB/);
  });
  test('1.6-UNIT-100: CH baseline contains parameterized password injection (NOT Vault placeholder)', () => {
    const src = readRepoFile(`${MIG_CH}/001_baseline.up.sql`);
    expect(src).toMatch(/CREATE USER (IF NOT EXISTS )?he_api IDENTIFIED WITH plaintext_password BY \{app_password:String\}/);
  });
  test('1.6-UNIT-101: CH baseline grants only SELECT, INSERT on he_api.* (no DROP/ALTER/CREATE TABLE)', () => {
    const src = readRepoFile(`${MIG_CH}/001_baseline.up.sql`);
    expect(src).toMatch(/GRANT\s+SELECT,\s*INSERT\s+ON\s+he_api\.\*/i);
    expect(src).not.toMatch(/GRANT[^;]*\bDROP\b/i);
  });
  test('1.6-UNIT-102: Redis ACL setup documented with he-api:* prefix and -@dangerous', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src).toMatch(/ACL SETUSER he-api/);
    expect(src).toMatch(/~he-api:\*/);
    expect(src).toMatch(/-@dangerous/);
  });
  test('1.6-UNIT-103: .gitignore blocks plaintext credential files', () => {
    const src = repoFileExists('.gitignore') ? readRepoFile('.gitignore') : '';
    const infraGi = repoFileExists('infra/.gitignore') ? readRepoFile('infra/.gitignore') : '';
    const combined = `${src}\n${infraGi}`;
    expect(combined).toMatch(/\*\.tfvars|\.he-api\/staging\.env|\.env|secrets?\.(ya?ml|tfvars)/i);
  });
  test('1.6-UNIT-104: no plaintext password literal under infra/terraform/', () => {
    const walk = (dir: string): string[] => {
      const out: string[] = [];
      for (const entry of readdirSync(repoPath(dir), { withFileTypes: true })) {
        if (entry.name.startsWith('.')) continue;
        const rel = `${dir}/${entry.name}`;
        if (entry.isDirectory()) out.push(...walk(rel));
        else if (entry.isFile() && entry.name.endsWith('.tf')) out.push(rel);
      }
      return out;
    };
    if (existsSync(repoPath('infra/terraform'))) {
      for (const f of walk('infra/terraform')) {
        const txt = readRepoFile(f);
        expect(txt).not.toMatch(/password\s*=\s*"[^"$][^"]*"/i);
      }
    }
  });
  test('1.6-UNIT-105: secret.yaml type Opaque', () => {
    expect(readRepoFile(`${HELM_CHART}/templates/secret.yaml`)).toMatch(/type:\s*Opaque/);
  });
});

describe('AC2 / Integration + E2E', () => {
  test.skip('1.6-INT-005: helm template grep returns no ExternalSecret/SealedSecret', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-010: admin Secret readable by ops-cluster-admin SA', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-011: cross-namespace get returns 403 Forbidden', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-012: app-cred DROP SCHEMA he_api returns 42501', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-013: app-cred Redis unauthorized key returns NOPERM', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-014: app-cred CH CREATE TABLE returns Not enough privileges', () => {
    throw new Error(SKIP_REASON);
  });
});

// ============================================================
// AC3: Migration toolchain — Atlas (PG) + golang-migrate (CH)
// ============================================================

describe('AC3 / T4: PG migration via Atlas (versioned mode, m-1)', () => {
  test('1.6-UNIT-120: atlas.hcl exists', () => {
    expect(repoFileExists(`${MIG_PG}/atlas.hcl`)).toBe(true);
  });
  test('1.6-UNIT-121: atlas.hcl declares env { migration { dir = ... } }', () => {
    const src = readRepoFile(`${MIG_PG}/atlas.hcl`);
    expect(src).toMatch(/env\s+"?\w*"?\s*\{[\s\S]*migration\s*\{[\s\S]*dir\s*=\s*"file:\/\//);
  });
  test('1.6-UNIT-122: atlas.hcl does NOT declare a declarative schema src loader', () => {
    const src = readRepoFile(`${MIG_PG}/atlas.hcl`);
    expect(src).not.toMatch(/schema\s*\{[\s\S]{0,200}src\s*=/);
  });
  test('1.6-UNIT-123: baseline filename matches versioned convention', () => {
    expect(/^\d{4}_[a-z][a-z0-9_]*\.sql$/.test('0001_baseline.sql')).toBe(true);
    expect(repoFileExists(`${MIG_PG}/0001_baseline.sql`)).toBe(true);
  });
  test('1.6-UNIT-124: baseline includes pgcrypto extension', () => {
    expect(readRepoFile(`${MIG_PG}/0001_baseline.sql`)).toMatch(/CREATE EXTENSION IF NOT EXISTS pgcrypto/i);
  });
  test('1.6-UNIT-125: baseline creates he_api schema', () => {
    expect(readRepoFile(`${MIG_PG}/0001_baseline.sql`)).toMatch(/CREATE SCHEMA IF NOT EXISTS he_api/i);
  });
  test('1.6-UNIT-126: baseline contains NO CREATE TABLE (BR-3.6)', () => {
    const src = readRepoFile(`${MIG_PG}/0001_baseline.sql`)
      .split('\n')
      .filter((l) => !l.trim().startsWith('--'))
      .join('\n');
    expect(src).not.toMatch(/CREATE\s+TABLE/i);
  });
  test('1.6-UNIT-127: baseline contains NO CREATE VIEW/FUNCTION/TRIGGER', () => {
    const src = readRepoFile(`${MIG_PG}/0001_baseline.sql`)
      .split('\n')
      .filter((l) => !l.trim().startsWith('--'))
      .join('\n');
    expect(src).not.toMatch(/CREATE\s+(MATERIALIZED\s+)?VIEW|CREATE\s+FUNCTION|CREATE\s+TRIGGER/i);
  });
  test('1.6-UNIT-128: migrations/postgres/*.sql contains exactly one file', () => {
    const files = readdirSync(repoPath(MIG_PG)).filter((f) => f.endsWith('.sql'));
    expect(files).toHaveLength(1);
  });
  test('1.6-UNIT-129: atlas.sum integrity file present', () => {
    expect(repoFileExists(`${MIG_PG}/atlas.sum`)).toBe(true);
  });
});

describe('AC3 / T5: CH migration via golang-migrate (m-2, m-3)', () => {
  test('1.6-UNIT-140: 001_baseline.up.sql exists', () => {
    expect(repoFileExists(`${MIG_CH}/001_baseline.up.sql`)).toBe(true);
  });
  test('1.6-UNIT-141: up filename matches golang-migrate convention', () => {
    expect(/^\d{3}_[a-z][a-z0-9_]*\.up\.sql$/.test('001_baseline.up.sql')).toBe(true);
  });
  test('1.6-UNIT-142: up file creates he_api database', () => {
    expect(readRepoFile(`${MIG_CH}/001_baseline.up.sql`)).toMatch(/CREATE DATABASE IF NOT EXISTS he_api/i);
  });
  test('1.6-UNIT-143: up file contains NO CREATE TABLE (BR-3.6)', () => {
    const src = readRepoFile(`${MIG_CH}/001_baseline.up.sql`)
      .split('\n')
      .filter((l) => !l.trim().startsWith('--'))
      .join('\n');
    expect(src).not.toMatch(/CREATE\s+TABLE/i);
  });
  test('1.6-UNIT-144: paired 001_baseline.down.sql exists (m-2)', () => {
    expect(repoFileExists(`${MIG_CH}/001_baseline.down.sql`)).toBe(true);
  });
  test('1.6-UNIT-145: down.sql first non-blank line is the literal m-2 comment', () => {
    const lines = readRepoFile(`${MIG_CH}/001_baseline.down.sql`)
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l.length > 0);
    expect(lines[0]).toBe(
      '-- intentionally empty; baseline migration is one-way per BR-3.3 (rollback via destroy-and-re-provision, not migration)',
    );
  });
  test('1.6-UNIT-146: down.sql has no executable SQL (only blank lines + comments)', () => {
    const lines = readRepoFile(`${MIG_CH}/001_baseline.down.sql`)
      .split('\n')
      .filter((l) => l.trim().length > 0 && !l.trim().startsWith('--'));
    expect(lines).toHaveLength(0);
  });
  test('1.6-UNIT-147: migrations/clickhouse contains exactly the paired up/down files', () => {
    const files = readdirSync(repoPath(MIG_CH))
      .filter((f) => f.endsWith('.sql'))
      .sort();
    expect(files).toEqual(['001_baseline.down.sql', '001_baseline.up.sql']);
  });
});

describe('AC3 / T6: scripts/db-migrate.sh', () => {
  test('1.6-UNIT-160: db-migrate.sh exists AND is executable', () => {
    expect(repoFileExists(DB_MIGRATE)).toBe(true);
    expect(isExecutable(DB_MIGRATE)).toBe(true);
  });
  test('1.6-UNIT-161: shebang #!/usr/bin/env bash', () => {
    expect(readRepoFile(DB_MIGRATE).split('\n')[0]).toBe('#!/usr/bin/env bash');
  });
  test('1.6-UNIT-162: contains set -euo pipefail in first 10 lines', () => {
    expect(readRepoFile(DB_MIGRATE).split('\n').slice(0, 10).join('\n')).toMatch(/set -euo pipefail/);
  });
  test('1.6-UNIT-163: implements up / down / status / diff subcommands', () => {
    const src = readRepoFile(DB_MIGRATE);
    expect(src).toMatch(/\bup\b/);
    expect(src).toMatch(/\bdown\b/);
    expect(src).toMatch(/\bstatus\b/);
    expect(src).toMatch(/\bdiff\b/);
  });
  test('1.6-UNIT-164: credential chain reads env + K8s Secret only (no vault invocation)', () => {
    const src = readRepoFile(DB_MIGRATE);
    expect(src).toMatch(/HE_API_DB_(POSTGRES|REDIS|CLICKHOUSE)_URI|kubectl get secret/);
    expect(src).not.toMatch(/vault\s+(read|kv\s+get)|VAULT_ADDR|VAULT_TOKEN/);
  });
  test('1.6-UNIT-165: invokes atlas migrate apply --dir migrations/postgres', () => {
    expect(readRepoFile(DB_MIGRATE)).toMatch(/atlas\s+migrate\s+apply\s+--dir\s+\S*migrations\/postgres/);
  });
  test('1.6-UNIT-166: does NOT invoke atlas schema apply (declarative prohibited)', () => {
    expect(readRepoFile(DB_MIGRATE)).not.toMatch(/atlas\s+schema\s+apply/);
  });
  test('1.6-UNIT-167: invokes golang-migrate for ClickHouse', () => {
    expect(readRepoFile(DB_MIGRATE)).toMatch(/migrate\s+-path\s+\S*migrations\/clickhouse\s+-database/);
  });
  test('1.6-UNIT-168: diff subcommand invokes atlas migrate diff (or status)', () => {
    expect(readRepoFile(DB_MIGRATE)).toMatch(/atlas\s+migrate\s+(diff|status)/);
  });
  test('1.6-UNIT-169: portable cwd (git rev-parse OR dirname-walk)', () => {
    expect(readRepoFile(DB_MIGRATE)).toMatch(/git rev-parse --show-toplevel|\$\(\s*dirname\b/);
  });
  test('1.6-UNIT-170: BR-3.6 boundary check (only baseline file allowed)', () => {
    const src = readRepoFile(DB_MIGRATE);
    expect(src).toMatch(/0001_baseline\.sql|find\s+\S*migrations\/postgres/);
  });
});

describe('AC3 / T6: CI workflow db-migrate-check.yml', () => {
  test('1.6-UNIT-180: workflow exists', () => {
    expect(repoFileExists(CI_DB_MIGRATE)).toBe(true);
  });
  test('1.6-UNIT-181: triggers on pull_request', () => {
    const doc = loadYaml<{ on?: unknown }>(CI_DB_MIGRATE);
    expect(JSON.stringify(doc.on)).toMatch(/pull_request/);
  });
  test('1.6-UNIT-182: declares ephemeral postgres:16 service container', () => {
    expect(readRepoFile(CI_DB_MIGRATE)).toMatch(/postgres:16(-alpine)?/);
  });
  test('1.6-UNIT-183: runs db-migrate.sh up AND diff', () => {
    const src = readRepoFile(CI_DB_MIGRATE);
    expect(src).toMatch(/db-migrate\.sh\s+up/);
    expect(src).toMatch(/db-migrate\.sh\s+diff/);
  });
  test('1.6-UNIT-184: pins Atlas binary version', () => {
    expect(readRepoFile(CI_DB_MIGRATE)).toMatch(/ariga\/setup-atlas|atlas\/atlas-action|ATLAS_VERSION/);
  });
  test('1.6-UNIT-185: concurrency block cancel-in-progress', () => {
    expect(readRepoFile(CI_DB_MIGRATE)).toMatch(/concurrency:[\s\S]{0,200}cancel-in-progress/);
  });
});

describe('AC3 / Integration + E2E', () => {
  test.skip('1.6-INT-010: PG baseline apply succeeds in ephemeral PG container', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-011: CH baseline apply succeeds in ephemeral CH container', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-012: re-running db-migrate.sh up is idempotent', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-013: db-migrate.sh diff on baseline returns exit 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-014: BR-3.6 enforcement — drift file fails the CI gate', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-015: golang-migrate down 1 on baseline is a no-op (m-2 stub)', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-016: bash -n db-migrate.sh exits 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-017: shellcheck db-migrate.sh exits 0 (no errors)', () => {
    throw new Error(SKIP_REASON);
  });
});

// ============================================================
// AC4: DB Doctor + Helm chart + docs (Q5 + m-4 + m-5)
// ============================================================

describe('AC4 / T7: scripts/db-doctor.sh', () => {
  test('1.6-UNIT-200: db-doctor.sh exists AND is executable', () => {
    expect(repoFileExists(DB_DOCTOR)).toBe(true);
    expect(isExecutable(DB_DOCTOR)).toBe(true);
  });
  test('1.6-UNIT-201: shebang + strict mode', () => {
    const src = readRepoFile(DB_DOCTOR);
    expect(src.split('\n')[0]).toBe('#!/usr/bin/env bash');
    expect(src.split('\n').slice(0, 10).join('\n')).toMatch(/set -euo pipefail/);
  });
  test('1.6-UNIT-202: reads ~/.he-api/staging.env', () => {
    expect(readRepoFile(DB_DOCTOR)).toMatch(/\.he-api\/staging\.env/);
  });
  test('1.6-UNIT-203: invokes psql + redis-cli + clickhouse-client', () => {
    const src = readRepoFile(DB_DOCTOR);
    expect(src).toMatch(/\bpsql\b/);
    expect(src).toMatch(/\bredis-cli\b/);
    expect(src).toMatch(/\bclickhouse-client\b/);
  });
  test('1.6-UNIT-204: sources probes from scripts/db-doctor/probes/ (Q5 SoT)', () => {
    expect(readRepoFile(DB_DOCTOR)).toMatch(/scripts\/db-doctor\/probes\/|db-doctor\/probes\//);
  });
  test('1.6-UNIT-205: exit-code semantics (0/1/2)', () => {
    const src = readRepoFile(DB_DOCTOR);
    expect(src).toMatch(/exit\s+0/);
    expect(src).toMatch(/exit\s+1/);
    expect(src).toMatch(/exit\s+2/);
  });
  test('1.6-UNIT-206: grep-able [PASS]/[FAIL] line prefix', () => {
    const src = readRepoFile(DB_DOCTOR);
    expect(src).toMatch(/\[PASS\]/);
    expect(src).toMatch(/\[FAIL\]/);
  });
  test('1.6-UNIT-207: emits at least five check labels (postgres SELECT 1, baseline version, redis PING, clickhouse SELECT 1, baseline version)', () => {
    const src = readRepoFile(DB_DOCTOR);
    expect(src).toMatch(/postgres/i);
    expect(src).toMatch(/redis/i);
    expect(src).toMatch(/clickhouse/i);
    expect(src).toMatch(/baseline migration|migration applied/);
  });
  test('1.6-UNIT-208: reports latency=Xms', () => {
    expect(readRepoFile(DB_DOCTOR)).toMatch(/latency/i);
  });
  test('1.6-UNIT-209: asserts PG baseline via atlas migrate status or atlas_schema_revisions', () => {
    expect(readRepoFile(DB_DOCTOR)).toMatch(/atlas\s+migrate\s+status|atlas_schema_revisions/);
  });
  test('1.6-UNIT-210: asserts CH baseline via schema_migrations or migrate version', () => {
    expect(readRepoFile(DB_DOCTOR)).toMatch(/schema_migrations|migrate\s+(-path\s+\S+\s+)?version/);
  });
});

describe('AC4 / T7: SQL probe single-source-of-truth (Q5)', () => {
  test('1.6-UNIT-220: probes directory exists', () => {
    expect(existsSync(repoPath(PROBES))).toBe(true);
  });
  test('1.6-UNIT-221: postgres.sql exists with SELECT 1', () => {
    expect(repoFileExists(`${PROBES}/postgres.sql`)).toBe(true);
    expect(readRepoFile(`${PROBES}/postgres.sql`)).toMatch(/SELECT\s+1/i);
  });
  test('1.6-UNIT-222: redis-ping.sh exists, executable, bash shebang', () => {
    expect(repoFileExists(`${PROBES}/redis-ping.sh`)).toBe(true);
    expect(isExecutable(`${PROBES}/redis-ping.sh`)).toBe(true);
    expect(readRepoFile(`${PROBES}/redis-ping.sh`).split('\n')[0]).toBe('#!/usr/bin/env bash');
  });
  test('1.6-UNIT-223: redis-ping.sh invokes redis-cli PING and expects PONG', () => {
    const src = readRepoFile(`${PROBES}/redis-ping.sh`);
    expect(src).toMatch(/redis-cli[^|\n]*\bPING\b/);
    expect(src).toMatch(/PONG/);
  });
  test('1.6-UNIT-224: clickhouse.sql exists with SELECT 1', () => {
    expect(repoFileExists(`${PROBES}/clickhouse.sql`)).toBe(true);
    expect(readRepoFile(`${PROBES}/clickhouse.sql`)).toMatch(/SELECT\s+1/i);
  });
  test('1.6-UNIT-225: probes contain no embedded password / connection string', () => {
    for (const f of ['postgres.sql', 'redis-ping.sh', 'clickhouse.sql']) {
      const txt = readRepoFile(`${PROBES}/${f}`);
      expect(txt).not.toMatch(/password\s*=|@[^@\s]+:[^@\s]+@/i);
    }
  });
});

describe('AC4 / T8: Helm chart infra/helm/db-doctor/', () => {
  test('1.6-UNIT-240: Chart.yaml exists', () => {
    expect(repoFileExists(`${HELM_CHART}/Chart.yaml`)).toBe(true);
  });
  test('1.6-UNIT-241: Chart.yaml apiVersion v2 / name db-doctor / type application', () => {
    const chart = loadYaml<{ apiVersion: string; name: string; type: string }>(`${HELM_CHART}/Chart.yaml`);
    expect(chart.apiVersion).toBe('v2');
    expect(chart.name).toBe('db-doctor');
    expect(chart.type).toBe('application');
  });
  test('1.6-UNIT-242: values.yaml defaults schedule */30 and activeDeadlineSeconds 300', () => {
    const values = loadYaml<{ schedule?: string; activeDeadlineSeconds?: number }>(`${HELM_CHART}/values.yaml`);
    expect(values.schedule).toBe('*/30 * * * *');
    expect(values.activeDeadlineSeconds).toBe(300);
  });
  test('1.6-UNIT-243: templates/cronjob.yaml kind CronJob; schedule templated', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`);
    expect(src).toMatch(/kind:\s*CronJob/);
    expect(src).toMatch(/schedule:\s*\{\{\s*\.Values\.schedule\s*\}\}/);
  });
  test('1.6-UNIT-244: activeDeadlineSeconds templated from values', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`);
    expect(src).toMatch(/activeDeadlineSeconds:\s*\{\{\s*\.Values\.activeDeadlineSeconds\s*\}\}/);
  });
  test('1.6-UNIT-245: cronjob Pod runs as non-root (PSR 6 baseline, runAsUser 65532)', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`);
    expect(src).toMatch(/runAsNonRoot:\s*true/);
    expect(src).toMatch(/runAsUser:\s*65532/);
  });
  test('1.6-UNIT-246: Pod loads credentials via envFrom secretRef (he-api-db-creds)', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`);
    expect(src).toMatch(/envFrom:[\s\S]{0,200}secretRef:[\s\S]{0,100}name:\s*he-api-db-creds/);
  });
  test('1.6-UNIT-247: configmap.yaml uses .Files.Get probes/postgres.sql', () => {
    expect(readRepoFile(`${HELM_CHART}/templates/configmap.yaml`)).toMatch(/\.Files\.Get\s+"probes\/postgres\.sql"/);
  });
  test('1.6-UNIT-248: configmap.yaml references clickhouse + redis probe files', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/configmap.yaml`);
    expect(src).toMatch(/probes\/clickhouse\.sql/);
    expect(src).toMatch(/probes\/redis-ping\.sh/);
  });
  test('1.6-UNIT-249: secret.yaml is plain Kubernetes Secret (no operator references)', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/secret.yaml`);
    expect(src).toMatch(/kind:\s*Secret\b/);
    expect(src).not.toMatch(/kind:\s*ExternalSecret|kind:\s*SealedSecret|external-secrets\.io|bitnami\.com/);
  });
  test('1.6-UNIT-250: servicemonitor.yaml declares ServiceMonitor for the CronJob', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/servicemonitor.yaml`);
    expect(src).toMatch(/kind:\s*ServiceMonitor/);
  });
  test('1.6-UNIT-251: cronjob exposes /metrics with he_api_db_doctor_check_status gauge', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`);
    expect(src).toMatch(/he_api_db_doctor_check_status|\/metrics/);
  });
  test('1.6-UNIT-252: container image bundles three DB CLIs (referenced in values or comment)', () => {
    const src =
      readRepoFile(`${HELM_CHART}/values.yaml`) + '\n' + readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`);
    expect(src).toMatch(/image:\s*\S+/);
    // Either values.yaml documents the image contains psql/redis-cli/clickhouse-client,
    // or the chart pins a known multi-CLI base; require an explicit reference.
    expect(src).toMatch(/psql|redis-cli|clickhouse-client|db-doctor/);
  });
  test('1.6-UNIT-253: no ArgoCD Application manifest in chart dir (M-2)', () => {
    const files = readdirSync(repoPath(HELM_CHART)).concat(readdirSync(repoPath(`${HELM_CHART}/templates`)));
    expect(files.some((f) => f.includes('argocd'))).toBe(false);
    for (const f of readdirSync(repoPath(`${HELM_CHART}/templates`))) {
      expect(readRepoFile(`${HELM_CHART}/templates/${f}`)).not.toMatch(/argoproj\.io\/v1alpha1[\s\S]{0,80}kind:\s*Application/);
    }
  });
  test('1.6-UNIT-254: Chart.yaml appVersion set', () => {
    const chart = loadYaml<{ appVersion?: string }>(`${HELM_CHART}/Chart.yaml`);
    expect(chart.appVersion).toBeTruthy();
  });
  test('1.6-UNIT-255: cronjob restartPolicy OnFailure or Never', () => {
    expect(readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`)).toMatch(/restartPolicy:\s*(OnFailure|Never)/);
  });
});

describe('AC4 / T9: docs/architecture/database-bootstrap.md (m-4 + m-5)', () => {
  test('1.6-UNIT-270: file exists', () => {
    expect(repoFileExists(DOC_BOOT)).toBe(true);
  });
  test('1.6-UNIT-271: contains six top-level sections', () => {
    const src = readRepoFile(DOC_BOOT);
    const h2 = src.split('\n').filter((l) => /^##\s+/.test(l));
    expect(h2.length).toBeGreaterThanOrEqual(6);
    expect(src).toMatch(/Topology/i);
    expect(src).toMatch(/Migration Workflow/i);
    expect(src).toMatch(/Credentials/i);
    expect(src).toMatch(/Capacity/i);
    expect(src).toMatch(/Operator Runbook/i);
    expect(src).toMatch(/Decision Lineage/i);
  });
  test('1.6-UNIT-272: VPC-private DNS subsection lists three FQDN suffixes (m-5)', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src).toMatch(/\*\.pg\.rds\.aliyuncs\.com/);
    expect(src).toMatch(/\*\.redis\.rds\.aliyuncs\.com/);
    expect(src).toMatch(/\*\.clickhouseserver\.aliyuncs\.com/);
  });
  test('1.6-UNIT-273: explicitly notes terraform output exposes FQDNs not IPs (m-5)', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src.toLowerCase()).toMatch(/fqdn/);
    expect(src.toLowerCase()).toMatch(/not\s+ips?|ip(s)?\s+may\s+rotate/);
  });
  test('1.6-UNIT-274: Section 2 documents Atlas versioned + golang-migrate paired semantics', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src).toMatch(/Atlas/);
    expect(src).toMatch(/golang-migrate/);
    expect(src).toMatch(/versioned/i);
    expect(src).toMatch(/paired\s+up\/down|up\/down/i);
  });
  test('1.6-UNIT-275: Section 2 documents drift gate + down-stub no-op semantics', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src).toMatch(/atlas\s+migrate\s+diff/);
    expect(src).toMatch(/down 1|no-op|no\s*op/i);
  });
  test('1.6-UNIT-276: Section 3 title contains Credentials AND Vault Migration Path', () => {
    expect(readRepoFile(DOC_BOOT)).toMatch(/Credentials\s+(&|and)\s+Vault Migration Path/);
  });
  test('1.6-UNIT-277: Section 3 documents K8s Secret only AND ExternalSecret CR migration path', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src).toMatch(/K8s Secret only|only.*K8s Secret/i);
    expect(src).toMatch(/ExternalSecret/);
    expect(src).toMatch(/secret\/he-api\/staging\/db\//);
  });
  test('1.6-UNIT-278: Section 3 "Open Followups" lists Vault provisioning + ExternalSecretsOperator install', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src).toMatch(/Open Followups/);
    expect(src).toMatch(/Vault provisioning/i);
    expect(src).toMatch(/ExternalSecretsOperator/);
  });
  test('1.6-UNIT-279: Section 3 documents rotation flow + RTO <= 2h', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src).toMatch(/rotation/i);
    expect(src).toMatch(/RTO\s*[≤<=]?\s*2\s*h/i);
  });
  test('1.6-UNIT-280: Section 5 runbook covers four failure modes', () => {
    const src = readRepoFile(DOC_BOOT);
    expect(src).toMatch(/连不上|cannot connect|connect.*failure/i);
    expect(src).toMatch(/drift/i);
    expect(src).toMatch(/凭据丢失|credential\s+loss|missing credential/i);
    expect(src).toMatch(/KMS unwrap|KMS.*fail/i);
  });
  test('1.6-UNIT-281: Section 6 Decision Lineage enumerates Q1..Q5 + M-1, M-2, m-1..m-5', () => {
    const src = readRepoFile(DOC_BOOT);
    for (const key of ['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'M-1', 'M-2', 'm-1', 'm-2', 'm-3', 'm-4', 'm-5']) {
      expect(src).toContain(key);
    }
  });
  test('1.6-UNIT-282: Section 6 rows carry [Source: ...] citations', () => {
    expect(readRepoFile(DOC_BOOT)).toMatch(/\[Source:[^\]]+\]/);
  });
});

describe('AC4 / T9: source-tree + README', () => {
  test('1.6-UNIT-290: source-tree.md registers rds-postgres module', () => {
    expect(readRepoFile(DOC_TREE)).toMatch(/infra\/terraform\/modules\/rds-postgres/);
  });
  test('1.6-UNIT-291: source-tree.md registers redis-tair + clickhouse modules', () => {
    const src = readRepoFile(DOC_TREE);
    expect(src).toMatch(/infra\/terraform\/modules\/redis-tair/);
    expect(src).toMatch(/infra\/terraform\/modules\/clickhouse/);
  });
  test('1.6-UNIT-292: source-tree.md registers migrations directories', () => {
    const src = readRepoFile(DOC_TREE);
    expect(src).toMatch(/migrations\/postgres/);
    expect(src).toMatch(/migrations\/clickhouse/);
  });
  test('1.6-UNIT-293: source-tree.md registers probes/ SoT dir', () => {
    expect(readRepoFile(DOC_TREE)).toMatch(/scripts\/db-doctor\/probes/);
  });
  test('1.6-UNIT-294: source-tree.md registers helm chart + db-*.sh scripts', () => {
    const src = readRepoFile(DOC_TREE);
    expect(src).toMatch(/infra\/helm\/db-doctor/);
    expect(src).toMatch(/scripts\/db-migrate\.sh/);
    expect(src).toMatch(/scripts\/db-doctor\.sh/);
  });
  test('1.6-UNIT-295: source-tree.md carries Story 1.6 footnote attribution', () => {
    expect(readRepoFile(DOC_TREE)).toMatch(/Story 1\.6/);
  });
  test('1.6-UNIT-296: README.md contains DB Doctor 自检 section', () => {
    expect(readRepoFile(README)).toMatch(/DB Doctor\s*自检|DB Doctor\s*self-check/i);
  });
  test('1.6-UNIT-297: README references db-doctor.sh AND db-migrate.sh', () => {
    const src = readRepoFile(README);
    expect(src).toMatch(/db-doctor\.sh/);
    expect(src).toMatch(/db-migrate\.sh/);
  });
});

describe('AC4 / Integration + E2E', () => {
  test.skip('1.6-INT-020: helm lint infra/helm/db-doctor/ exits 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-021: helm template | kubeconform -strict exits 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-022: shellcheck db-doctor + probes exits 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-023: yamllint infra/helm/db-doctor/templates exits 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-INT-024: doctor against ephemeral PG only — exits 1, has [FAIL] line', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-020: helm install db-doctor succeeds (M-2 direct install)', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-021: db-doctor.sh in staging pod exits 0 in <= 5 min, 5/5 PASS', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-022: CronJob runs at next */30 window; logs show PASS', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-023: Prometheus he_api_db_doctor_check_status = 1 for all three DBs', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-024: stop Tair → metric flips to 0 → alertmanager fires', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-E2E-025: credential rotation rehearsal — CronJob still PASS', () => {
    throw new Error(SKIP_REASON);
  });
});

// ============================================================
// Blind Spot Scenarios [BLIND-SPOT]
// ============================================================

describe('Blind Spots: BOUNDARY', () => {
  test.skip('1.6-BLIND-BOUNDARY-001: db-migrate.sh with empty POSTGRES_URI exits non-zero', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-BOUNDARY-002: db-doctor.sh with missing staging.env exits 2', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-BOUNDARY-003: doctor at 5:00 wall-clock still exits 0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-BOUNDARY-004: doctor > 5:00 → CronJob killed at 300s + DOC-DB-002 alert', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-BOUNDARY-005: malformed URI fast-fails before DB contact', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-BOUNDARY-006: PG URI without sslmode=require → refused', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-BOUNDARY-007: redis:// (non-TLS) URI → refused', () => {
    throw new Error(SKIP_REASON);
  });
});

describe('Blind Spots: ERROR', () => {
  test.skip('1.6-BLIND-ERROR-001: mid-apply PG kill → Atlas rolls back transactional migration', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-ERROR-002: PG unreachable → [FAIL] line + metric=0', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-ERROR-003: ACK KMS unwrap fails → CronJob pod fails + alert', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-ERROR-004: out-of-band schema change → db-migrate.sh diff exit non-zero', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-ERROR-005: terraform apply with KMS inaccessible recovers cleanly on retry', () => {
    throw new Error(SKIP_REASON);
  });
});

describe('Blind Spots: CONCURRENCY', () => {
  test.skip('1.6-BLIND-CONCURRENCY-001: parallel db-migrate.sh up → Atlas lock prevents double-apply', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-CONCURRENCY-002: credential rotation during CronJob run → no orphaned connections', () => {
    throw new Error(SKIP_REASON);
  });
});

describe('Blind Spots: DATA', () => {
  test('1.6-BLIND-DATA-001: BR-3.6 — adding a CREATE TABLE migration is rejected by CI gate', () => {
    // Static guard: the CI workflow contains the BR-3.6 enforcement command/regex
    const src = readRepoFile(CI_DB_MIGRATE);
    expect(src).toMatch(/MIG-DB-001|0001_baseline\.sql|BR-3\.6/);
  });
  test.skip('1.6-BLIND-DATA-002: app-cred DROP SCHEMA he_api permission denied (cross-listed with E2E-012)', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-DATA-003: terraform state JSON has no plaintext password matches', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-DATA-004: git log -p migrations/ has no plaintext password matches', () => {
    throw new Error(SKIP_REASON);
  });
});

describe('Blind Spots: RESOURCE', () => {
  test('1.6-BLIND-RESOURCE-001: CronJob activeDeadlineSeconds = 300 strictly enforced', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`);
    expect(src).toMatch(/activeDeadlineSeconds:\s*\{\{\s*\.Values\.activeDeadlineSeconds\s*\}\}/);
    const values = loadYaml<{ activeDeadlineSeconds?: number }>(`${HELM_CHART}/values.yaml`);
    expect(values.activeDeadlineSeconds).toBe(300);
  });
  test('1.6-BLIND-RESOURCE-002: cronjob declares resources.limits.{memory,cpu}', () => {
    const src = readRepoFile(`${HELM_CHART}/templates/cronjob.yaml`);
    expect(src).toMatch(/resources:[\s\S]{0,200}limits:/);
    expect(src).toMatch(/memory:/);
    expect(src).toMatch(/cpu:/);
  });
  test.skip('1.6-BLIND-RESOURCE-003: failure of one DB does not leak connections on others', () => {
    throw new Error(SKIP_REASON);
  });
});

describe('Blind Spots: FLOW', () => {
  test.skip('1.6-BLIND-FLOW-001: terraform apply SIGTERM mid-way → state consistent + resumable', () => {
    throw new Error(SKIP_REASON);
  });
  test.skip('1.6-BLIND-FLOW-002: helm uninstall db-doctor → no orphan ConfigMap/Secret leak', () => {
    throw new Error(SKIP_REASON);
  });
});
