/**
 * Test Skeleton for Story 1.7: staging 部署管线接通（GitOps 端到端）
 *
 * AUTO-GENERATED by QA Test Design (Turing, 2026-06-16). Dev implemented all TODO blocks.
 * Do NOT delete any test case — each maps to a designed scenario.
 *
 * This is a STATIC GitOps deploy-wiring story (no docker/atlas/buf/helm locally — see memory:
 * toolchain env limits). Scenarios are implemented as static assertions over repo artifacts using
 * the shared helpers below (raw-text/regex, YAML parse, file existence, readdir). The helm-render +
 * kubeconform + actionlint runtime checks run in CI (build-images.yml / chart-lint); here the same
 * invariants are asserted statically over the template/values/workflow source — which is the point
 * of this story (every contract is statically assertable).
 *
 * Test Design: docs/qa/assessments/1.7-test-design-20260616.md
 * Generated: 2026-06-16
 */

import { describe, expect, test } from 'vitest';
import { readFileSync, existsSync, statSync, readdirSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, '..', '..', '..');

const repoPath = (rel: string): string => resolve(REPO_ROOT, rel);
const repoFileExists = (rel: string): boolean => existsSync(repoPath(rel));
const readRepoFile = (rel: string): string => readFileSync(repoPath(rel), 'utf8');
const loadYaml = <T = unknown>(rel: string): T => parseYaml(readRepoFile(rel)) as T;

// ------------------------------------------------------------
// Story-1.7-specific helpers
// ------------------------------------------------------------
const APPS_DIR = 'infra/argocd/applications';
const HELM_DIR = 'infra/helm';
const BUILD_WF = '.github/workflows/build-images.yml';
const DEPLOY_WF = '.github/workflows/deploy-staging.yml';
const STORY = 'docs/stories/1.7-staging-deploy-pipeline-wiring.md';
const REPO_URL = 'https://github.com/he-api/he-api';
const SAMPLES = ['sample-otel-app', 'sample-grpc-app'];

const listAppFiles = (): string[] =>
  readdirSync(repoPath(APPS_DIR))
    .filter((f) => f.endsWith('.yaml'))
    .sort();

const loadApp = (file: string): any => loadYaml(`${APPS_DIR}/${file}`);
const allApps = (): any[] => listAppFiles().map(loadApp);

const helmCharts = (): string[] =>
  readdirSync(repoPath(HELM_DIR)).filter((d) => existsSync(repoPath(`${HELM_DIR}/${d}/Chart.yaml`)));

// Recursive Dockerfile finder under apps/.
const findDockerfiles = (rel: string): string[] => {
  const out: string[] = [];
  for (const entry of readdirSync(repoPath(rel), { withFileTypes: true })) {
    const child = join(rel, entry.name);
    if (entry.isDirectory()) out.push(...findDockerfiles(child));
    else if (entry.name === 'Dockerfile') out.push(child);
  }
  return out;
};

const buildWf = (): any => loadYaml(BUILD_WF);
const prMatrix = (): any[] => buildWf().jobs['build-image-pr'].strategy.matrix.svc;
const nonSampleMatrix = (): any[] => prMatrix().filter((e) => e.sample !== true);

// values*.yaml across all charts.
const valuesFiles = (): string[] => {
  const out: string[] = [];
  for (const c of readdirSync(repoPath(HELM_DIR))) {
    for (const f of ['values.yaml', 'values-staging.yaml']) {
      if (existsSync(repoPath(`${HELM_DIR}/${c}/${f}`))) out.push(`${HELM_DIR}/${c}/${f}`);
    }
  }
  return out;
};

// Collect every image.tag value reachable in a parsed values object (main + cron sub-images).
const collectTags = (node: any, acc: string[] = []): string[] => {
  if (node && typeof node === 'object') {
    if (typeof node.repository === 'string' && node.tag !== undefined) acc.push(String(node.tag));
    for (const v of Object.values(node)) collectTags(v, acc);
  }
  return acc;
};
const collectRepositories = (node: any, acc: string[] = []): string[] => {
  if (node && typeof node === 'object') {
    if (typeof node.repository === 'string') acc.push(node.repository);
    for (const v of Object.values(node)) collectRepositories(v, acc);
  }
  return acc;
};

const PLACEHOLDER = 'ArgoCD sync placeholder (real CLI wired in Story 1.4)';

// ============================================================
// AC1 (B1): ArgoCD 同步换成真实 `argocd app sync`
// ============================================================

describe('AC1 (B1): real argocd app sync', () => {
  test('1.7-UNIT-001: ArgoCD sync placeholder string removed repo-wide (grep 0 hits)', () => {
    expect(readRepoFile(DEPLOY_WF)).not.toContain(PLACEHOLDER);
    expect(readRepoFile(DEPLOY_WF)).not.toContain('real CLI wired in Story 1.4');
  });

  test('1.7-UNIT-002: deploy-staging trigger-argocd-sync runs real `argocd app sync` + `argocd app wait --health`', () => {
    const wf = readRepoFile(DEPLOY_WF);
    expect(wf).toMatch(/argocd app sync/);
    expect(wf).toMatch(/argocd app wait/);
    expect(wf).toMatch(/--health/);
    expect(wf).not.toMatch(/echo "ArgoCD sync placeholder/);
  });

  test('1.7-UNIT-003: argocd login uses secrets.ARGOCD_AUTH_TOKEN + vars.ARGOCD_ENDPOINT, --grpc-web, no plaintext/hardcoded creds', () => {
    const wf = readRepoFile(DEPLOY_WF);
    expect(wf).toContain('secrets.ARGOCD_AUTH_TOKEN');
    expect(wf).toContain('vars.ARGOCD_ENDPOINT');
    expect(wf).toContain('--grpc-web');
    // No hardcoded argocd endpoint URL, no plaintext token flag.
    expect(wf).not.toMatch(/--server\s+https?:\/\//);
    expect(wf).not.toMatch(/--auth-token\s+\S/);
    expect(wf).not.toContain('--plaintext');
  });

  test('1.7-UNIT-005: deploy-staging.yml passes actionlint / YAML parse', () => {
    expect(() => loadYaml(DEPLOY_WF)).not.toThrow();
  });

  test('1.7-INT-001: sync target app list == infra/argocd/applications/*.yaml inventory (single source)', () => {
    const wf = readRepoFile(DEPLOY_WF);
    // The sync step derives names from the Application inventory dir (single source, BR1.4).
    expect(wf).toContain(APPS_DIR);
    expect(wf).toMatch(/argocd app sync "\$name"/);
    expect(listAppFiles().length).toBeGreaterThanOrEqual(13);
  });

  test('[BLIND-SPOT] 1.7-BLIND-ERROR-001: argocd login failure → non-zero exit, job fails, does NOT enter sync', () => {
    const wf = readRepoFile(DEPLOY_WF);
    // Login is a separate, earlier step that validates the session (get-user-info)
    // under `set -euo pipefail`; a bad token/endpoint fails before any sync step.
    expect(wf).toMatch(/ArgoCD login[\s\S]*set -euo pipefail[\s\S]*get-user-info/);
    expect(wf.indexOf('get-user-info')).toBeLessThan(wf.indexOf('argocd app sync'));
  });

  test('[BLIND-SPOT] 1.7-BLIND-ERROR-002: app sync/wait timeout or unhealthy → job fails (non-zero), error not swallowed', () => {
    const wf = readRepoFile(DEPLOY_WF);
    // rc accumulator + explicit exit "$rc" → a failed sync/wait fails the job.
    expect(wf).toMatch(/argocd app wait[\s\S]*--health/);
    expect(wf).toMatch(/rc=1/);
    expect(wf).toMatch(/exit "\$rc"/);
  });

  test('[BLIND-SPOT] 1.7-BLIND-BOUNDARY-001: ARGOCD_ENDPOINT empty/unset (HAS_ARGOCD != true) → skip message, not crash', () => {
    const wf = readRepoFile(DEPLOY_WF);
    expect(wf).toContain("HAS_ARGOCD: ${{ vars.ARGOCD_ENDPOINT != '' && 'true' || 'false' }}");
    expect(wf).toMatch(/Skip ArgoCD sync \(fallback\)/);
  });

  test('[BLIND-SPOT] 1.7-BLIND-FLOW-001: HAS_ARGOCD != true → fallback skip step preserved (no-creds CI not broken)', () => {
    const wf = readRepoFile(DEPLOY_WF);
    expect(wf).toMatch(/if: env\.HAS_ARGOCD != 'true'/);
  });
});

// ============================================================
// AC2 (B2): build-images 矩阵覆盖全部可部署镜像
// ============================================================

describe('AC2 (B2): build-images matrix covers all deployable images', () => {
  test('1.7-UNIT-010: &svc_list anchor extended; pr+main matrices share single anchor (1.5-UNIT-216 no regression)', () => {
    const raw = readRepoFile(BUILD_WF);
    // Exactly one anchor DEFINITION (`svc: &svc_list`) and one ALIAS reuse
    // (`svc: *svc_list`) — the single-append-point contract. (Comments may
    // mention the anchor name; match the structural form, not bare mentions.)
    expect((raw.match(/svc: &svc_list/g) || []).length).toBe(1);
    expect((raw.match(/svc: \*svc_list/g) || []).length).toBe(1);
    // Resolved anchor → pr and main matrices are identical.
    const wf = buildWf();
    expect(wf.jobs['build-image-main'].strategy.matrix.svc).toEqual(
      wf.jobs['build-image-pr'].strategy.matrix.svc,
    );
  });

  test('1.7-UNIT-011: main-branch push tags images :${github.sha} (immutable, no latest)', () => {
    const raw = readRepoFile(BUILD_WF);
    expect(raw).toMatch(/tags: \$\{\{ secrets\.ACR_REGISTRY \}\}\/he-api\/\$\{\{ matrix\.svc\.name \}\}:\$\{\{ github\.sha \}\}/);
    expect(raw).not.toMatch(/:latest/);
  });

  test('1.7-UNIT-012: cron images with context != apps/<svc> carry explicit context/dockerfile matrix-include fields', () => {
    for (const e of prMatrix()) {
      expect(typeof e.context).toBe('string');
      expect(typeof e.dockerfile).toBe('string');
    }
  });

  test('1.7-UNIT-013: sample-otel-app / sample-grpc-app retained in matrix but excluded from the 17 count', () => {
    const names = prMatrix().map((e) => e.name);
    for (const s of SAMPLES) expect(names).toContain(s);
    for (const e of prMatrix().filter((x) => SAMPLES.includes(x.name))) expect(e.sample).toBe(true);
    expect(nonSampleMatrix().some((e) => SAMPLES.includes(e.name))).toBe(false);
  });

  test('1.7-UNIT-014: image-sha artifact upload preserved; deploy-staging download step not broken', () => {
    const build = readRepoFile(BUILD_WF);
    expect(build).toContain('upload-artifact');
    expect(build).toMatch(/name: image-sha/);
    expect(build).toMatch(/if: matrix\.svc\.name == 'api-gateway'/);
    const deploy = readRepoFile(DEPLOY_WF);
    expect(deploy).toContain('download-artifact');
    expect(deploy).toMatch(/name: image-sha/);
  });

  test('1.7-INT-002: matrix entry count == authoritative apps/**/Dockerfile target count (17)', () => {
    const deployableDockerfiles = findDockerfiles('apps').filter(
      (d) => !SAMPLES.some((s) => d.includes(`/${s}/`)),
    );
    expect(deployableDockerfiles.length).toBe(17);
    expect(nonSampleMatrix().length).toBe(17);
  });

  test('[BLIND-SPOT] 1.7-BLIND-ERROR-003: single image build fails → fail-fast:false (others continue) BUT job overall fails', () => {
    const wf = buildWf();
    expect(wf.jobs['build-image-pr'].strategy['fail-fast']).toBe(false);
    expect(wf.jobs['build-image-main'].strategy['fail-fast']).toBe(false);
  });

  test('[BLIND-SPOT] 1.7-BLIND-FLOW-002: HAS_ACR != true → skip-push branch preserved (no-creds CI only validates)', () => {
    const raw = readRepoFile(BUILD_WF);
    expect(raw).toMatch(/Skip push \(no ACR secrets\)/);
    expect(raw).toMatch(/if: env\.HAS_ACR != 'true'/);
  });

  test('[BLIND-SPOT] 1.7-BLIND-DATA-001: every build-matrix entry resolves to an existing Dockerfile (no orphan/unbuildable entry)', () => {
    for (const e of prMatrix()) {
      expect(repoFileExists(e.dockerfile), `dockerfile missing: ${e.dockerfile}`).toBe(true);
    }
  });
});

// ============================================================
// AC3 (B3): ArgoCD Application + values-staging + he-api AppProject
// ============================================================

describe('AC3 (B3): Application + AppProject + values-staging wiring', () => {
  const PROJECT = 'infra/argocd/projects/he-api.yaml';
  const NEW_APPS = ['api-gateway', 'auth-svc', 'billing-svc', 'notification-svc', 'payment-svc', 'analytics-svc'];

  test('1.7-UNIT-020: infra/argocd/projects/he-api.yaml exists (kind: AppProject, name he-api)', () => {
    expect(repoFileExists(PROJECT)).toBe(true);
    const p = loadYaml<any>(PROJECT);
    expect(p.kind).toBe('AppProject');
    expect(p.metadata.name).toBe('he-api');
  });

  test('1.7-UNIT-021: AppProject destinations limited to kubernetes.default.svc + he-api ns; sourceRepos limited to this repo', () => {
    const p = loadYaml<any>(PROJECT);
    expect(p.spec.sourceRepos).toEqual([REPO_URL]);
    for (const d of p.spec.destinations) {
      expect(d.server).toBe('https://kubernetes.default.svc');
      expect(['he-api-staging', 'he-api-adapters']).toContain(d.namespace);
    }
    expect(p.spec.destinations.some((d: any) => d.namespace === 'he-api-staging')).toBe(true);
  });

  test('1.7-UNIT-022: new Applications exist: api-gateway, auth-svc, billing-svc, notification-svc, payment-svc, analytics-svc', () => {
    for (const a of NEW_APPS) expect(repoFileExists(`${APPS_DIR}/${a}.yaml`), a).toBe(true);
  });

  test('1.7-UNIT-023: new Applications reuse routing-svc syncPolicy (automated prune+selfHeal, CreateNamespace=true, retry limit 5)', () => {
    for (const a of NEW_APPS) {
      const app = loadApp(`${a}.yaml`);
      const sp = app.spec.syncPolicy;
      expect(sp.automated.prune).toBe(true);
      expect(sp.automated.selfHeal).toBe(true);
      expect(sp.syncOptions).toContain('CreateNamespace=true');
      expect(sp.retry.limit).toBe(5);
    }
  });

  test('1.7-UNIT-024: every Application carries he-api/epic + he-api/story labels', () => {
    for (const app of allApps()) {
      expect(app.metadata.labels['he-api/epic']).toBeDefined();
      expect(app.metadata.labels['he-api/story']).toBeDefined();
    }
  });

  test('1.7-UNIT-025: every Application helm.valueFiles == [values.yaml, values-staging.yaml] (overlay last)', () => {
    for (const app of allApps()) {
      expect(app.spec.source.helm.valueFiles).toEqual(['values.yaml', 'values-staging.yaml']);
    }
  });

  test('1.7-INT-003: analytics-svc Application source.path -> infra/helm/analytics-svc/ which exists (H-1 resolved)', () => {
    const app = loadApp('analytics-svc.yaml');
    expect(app.spec.source.path).toBe('infra/helm/analytics-svc');
    expect(repoFileExists('infra/helm/analytics-svc/Chart.yaml')).toBe(true);
  });

  test('1.7-INT-004: every Application source.path points to an existing chart dir (no dangling chart)', () => {
    for (const app of allApps()) {
      expect(repoFileExists(`${app.spec.source.path}/Chart.yaml`), app.spec.source.path).toBe(true);
    }
  });

  test('[BLIND-SPOT] 1.7-BLIND-ERROR-004: Application references a non-existent values file → guard: every referenced values-staging.yaml exists', () => {
    for (const app of allApps()) {
      for (const vf of app.spec.source.helm.valueFiles) {
        expect(repoFileExists(`${app.spec.source.path}/${vf}`), `${app.spec.source.path}/${vf}`).toBe(true);
      }
    }
  });
});

// ============================================================
// AC4 (B4): 消除镜像占位符与 `tag: latest`
// ============================================================

describe('AC4 (B4): eliminate image placeholders and tag:latest', () => {
  test('1.7-UNIT-030: grep — no `tag: latest` / moving tag in any values*.yaml (0 hits)', () => {
    for (const f of valuesFiles()) {
      for (const tag of collectTags(loadYaml<any>(f))) {
        expect(tag, `${f} has moving tag`).not.toBe('latest');
      }
    }
  });

  test('1.7-UNIT-031: image repository placeholder syntax unified to ONE convention repo-wide (no $$ vs ${} split)', () => {
    for (const f of valuesFiles()) {
      for (const repo of collectRepositories(loadYaml<any>(f))) {
        expect(repo, `${f} uses double-dollar placeholder`).not.toContain('$$');
      }
    }
  });

  test('1.7-UNIT-032: deploy-staging update-helm-values bumps ALL staging apps image.tag = ${github.sha} (not just api-gateway)', () => {
    const wf = readRepoFile(DEPLOY_WF);
    // Loops over the Application inventory and recursively bumps every image tag.
    expect(wf).toContain(APPS_DIR);
    expect(wf).toMatch(/select\(has\("repository"\) and has\("tag"\)\) \| \.tag\) = strenv\(SHA\)/);
    // No longer a single hardcoded api-gateway-only bump.
    expect(wf).not.toMatch(/yq eval -i '\.image\.tag = strenv\(SHA\)' infra\/helm\/api-gateway\/values-staging\.yaml/);
  });

  test('1.7-UNIT-033: values.yaml (default) keeps semver; only values-staging.yaml SHA-bumped', () => {
    // Default values.yaml tags are semver-ish (no token, no 40-hex SHA).
    for (const c of helmCharts()) {
      const vf = `${HELM_DIR}/${c}/values.yaml`;
      if (!repoFileExists(vf)) continue;
      for (const tag of collectTags(loadYaml<any>(vf))) {
        expect(tag, `${vf} default tag should be semver`).toMatch(/^\d+\.\d+\.\d+$/);
      }
    }
    // The bump workflow only writes values-staging.yaml, never values.yaml.
    const wf = readRepoFile(DEPLOY_WF);
    expect(wf).toMatch(/values-staging\.yaml/);
    expect(wf).not.toMatch(/yq -i[^\n]*\/values\.yaml/);
  });

  test('1.7-UNIT-034: api-gateway values-staging whitelist comment updated for expanded bump scope; image.tag stays yq-writable', () => {
    const raw = readRepoFile('infra/helm/api-gateway/values-staging.yaml');
    expect(raw).toMatch(/1\.7/);
    expect(raw).toMatch(/ingress/i);
    // image.tag is a plain quoted scalar (yq-writable), not a Helm/templated value.
    const v = loadYaml<any>('infra/helm/api-gateway/values-staging.yaml');
    expect(String(v.image.tag)).not.toContain('{{');
    expect(String(v.image.tag)).not.toContain('$');
  });

  test('1.7-INT-005: bump service list == B3 Application list (single source)', () => {
    const wf = readRepoFile(DEPLOY_WF);
    // Both the bump (update-helm-values) and sync (trigger-argocd-sync) iterate
    // the SAME Application inventory dir → a service can't be bumped-but-not-synced.
    expect((wf.match(new RegExp(`find ${APPS_DIR.replace(/\//g, '\\/')}`, 'g')) || []).length).toBeGreaterThanOrEqual(2);
  });

  test('[BLIND-SPOT] 1.7-BLIND-BOUNDARY-002: unreplaced placeholder blocked by static grep BEFORE entering sync path', () => {
    const wf = readRepoFile(DEPLOY_WF);
    // Pre-sync guard greps for a residual ${ACR_REGISTRY} token and fails closed.
    const syncIdx = wf.indexOf('argocd app sync "$name"');
    const guardIdx = wf.indexOf("grep -q '${ACR_REGISTRY}'");
    expect(guardIdx).toBeGreaterThan(-1);
    expect(guardIdx).toBeLessThan(syncIdx);
  });
});

// ============================================================
// AC5 (B5): Ingress 模板 + staging DNS/TLS
// ============================================================

describe('AC5 (B5): Ingress template + staging DNS/TLS', () => {
  const ING_TMPL = 'infra/helm/api-gateway/templates/ingress.yaml';

  test('1.7-UNIT-040: api-gateway templates/ingress.yaml exists; values expose ingress.*', () => {
    expect(repoFileExists(ING_TMPL)).toBe(true);
    const v = loadYaml<any>('infra/helm/api-gateway/values.yaml');
    expect(v.ingress).toBeDefined();
    expect(v.ingress.enabled).toBe(false); // default off
  });

  test('1.7-UNIT-041: ingressClassName set (e.g. ingress-nginx)', () => {
    expect(readRepoFile(ING_TMPL)).toContain('ingressClassName');
    const vs = loadYaml<any>('infra/helm/api-gateway/values-staging.yaml');
    expect(vs.ingress.className).toBe('ingress-nginx');
  });

  test('1.7-UNIT-042: api-gateway values-staging FORBIDDEN:ingress.* whitelist lifted + comment de-drifted (1.7 not 1.4)', () => {
    const raw = readRepoFile('infra/helm/api-gateway/values-staging.yaml');
    // ingress is now enabled (whitelist lifted) and attributed to 1.7.
    const vs = loadYaml<any>('infra/helm/api-gateway/values-staging.yaml');
    expect(vs.ingress.enabled).toBe(true);
    expect(raw).not.toMatch(/FORBIDDEN[\s\S]*ingress\.\*\s+—\s+Story 1\.4 adds ingress-nginx/);
    expect(raw).toMatch(/owns ingress|ingress.*Story 1\.7|NOT 1\.4/i);
  });

  test('1.7-UNIT-043: TLS source documented (cert-manager Issuer/ClusterIssuer or preset Secret) in Dev Notes', () => {
    const story = readRepoFile(STORY);
    expect(story).toMatch(/cert-manager/i);
    expect(story).toMatch(/ClusterIssuer|Issuer|secretName/);
  });

  test('1.7-UNIT-044: only externally-exposed svc (api-gateway) get Ingress; internal svc not exposed', () => {
    for (const c of helmCharts()) {
      const tmpl = `${HELM_DIR}/${c}/templates/ingress.yaml`;
      if (c === 'api-gateway') expect(repoFileExists(tmpl)).toBe(true);
      else expect(repoFileExists(tmpl), `${c} should NOT expose Ingress`).toBe(false);
    }
  });

  test('1.7-INT-006: api-gateway staging renders Ingress with staging host + TLS (secretName/issuer) [CI: helm template | kubeconform]', () => {
    const tmpl = readRepoFile(ING_TMPL);
    expect(tmpl).toContain('kind: Ingress');
    expect(tmpl).toMatch(/\.Values\.ingress\.hosts/);
    expect(tmpl).toMatch(/\.Values\.ingress\.tls/);
    const vs = loadYaml<any>('infra/helm/api-gateway/values-staging.yaml');
    expect(vs.ingress.hosts[0].host).toMatch(/staging\.he-api\.com$/);
    expect(vs.ingress.tls[0].secretName).toBeTruthy();
    expect(vs.ingress.annotations['cert-manager.io/cluster-issuer']).toBeTruthy();
  });

  test('1.7-INT-007: ingress disabled (default values.yaml) → no Ingress rendered', () => {
    const v = loadYaml<any>('infra/helm/api-gateway/values.yaml');
    expect(v.ingress.enabled).toBe(false);
    // Template is guarded by `if .Values.ingress.enabled`.
    expect(readRepoFile(ING_TMPL)).toMatch(/{{-?\s*if\s+\.Values\.ingress\.enabled/);
  });

  test('[BLIND-SPOT] 1.7-BLIND-BOUNDARY-003: ingress.enabled true but missing host/TLS → render fails loudly (not silently broken)', () => {
    // The template builds rules ONLY by ranging .Values.ingress.hosts[].host; an
    // enabled-but-hostless config renders an Ingress with no rules → kubeconform/
    // apiserver rejects it (loud failure, not a silent no-op). The staging values
    // DO provide host+TLS, so the happy path renders a valid resource.
    const tmpl = readRepoFile(ING_TMPL);
    expect(tmpl).toMatch(/range \.Values\.ingress\.hosts/);
    expect(tmpl).toMatch(/host:/);
  });
});

// ============================================================
// AC6 (B6): cron Dockerfile + billing-svc Deployment
// ============================================================

describe('AC6 (B6): cron Dockerfiles + billing-svc Deployment', () => {
  const CRONS = [
    'apps/auth-svc/cmd/monthly-cost-reset/Dockerfile',
    'apps/auth-svc/cmd/account-deletion-sweeper/Dockerfile',
    'apps/api-gateway/cmd/safety-log-retention/Dockerfile',
  ];

  test('1.7-UNIT-050: apps/api-gateway/cmd/safety-log-retention/Dockerfile exists', () => {
    expect(repoFileExists('apps/api-gateway/cmd/safety-log-retention/Dockerfile')).toBe(true);
  });

  test('1.7-UNIT-051: apps/auth-svc/cmd/account-deletion-sweeper/Dockerfile exists', () => {
    expect(repoFileExists('apps/auth-svc/cmd/account-deletion-sweeper/Dockerfile')).toBe(true);
  });

  test('1.7-UNIT-052: 3 cron Dockerfiles follow multi-stage + distroless/non-root pattern', () => {
    for (const d of CRONS) {
      const c = readRepoFile(d);
      expect(c, `${d} multi-stage`).toMatch(/AS build/i);
      expect(c, `${d} distroless`).toMatch(/distroless/);
      expect(c, `${d} non-root`).toMatch(/USER (65532|nonroot)/);
    }
  });

  test('1.7-UNIT-053: db-doctor image build-path decision recorded in Dev Notes AND consistent with B2 matrix', () => {
    const story = readRepoFile(STORY);
    expect(story).toMatch(/db-doctor/);
    expect(story).toMatch(/reuse|复用|no.*Dockerfile|无 Dockerfile/i);
    // db-doctor is NOT a build-matrix entry (it has no Dockerfile).
    expect(prMatrix().some((e) => e.name === 'db-doctor')).toBe(false);
    expect(repoFileExists('apps/db-doctor/Dockerfile')).toBe(false);
  });

  test('1.7-UNIT-054: infra/helm/billing-svc/templates/deployment.yaml exists, driven by values.yaml billing-svc main-service block', () => {
    const tmpl = 'infra/helm/billing-svc/templates/deployment.yaml';
    expect(repoFileExists(tmpl)).toBe(true);
    expect(readRepoFile(tmpl)).toMatch(/\.Values\.image\.repository/);
    const v = loadYaml<any>('infra/helm/billing-svc/values.yaml');
    expect(v.image.repository).toContain('billing-svc');
  });

  test('1.7-UNIT-055: fx-refresh schedule "0 0 * * *" UNCHANGED (verify-cron-schedule.sh still green)', () => {
    const v = loadYaml<any>('infra/helm/billing-svc/values.yaml');
    expect(v.fxRefresh.schedule).toBe('0 0 * * *');
  });

  test('1.7-INT-008: billing-svc Deployment renders PSR + OTel env + probes + SA [CI: helm template | kubeconform]', () => {
    const d = readRepoFile('infra/helm/billing-svc/templates/deployment.yaml');
    expect(d).toMatch(/runAsNonRoot: true/);
    expect(d).toMatch(/seccompProfile:\s*\n\s*type: RuntimeDefault/);
    expect(d).toMatch(/OTEL_EXPORTER_OTLP_ENDPOINT/);
    expect(d).toMatch(/readinessProbe/);
    expect(d).toMatch(/serviceAccountName/);
  });

  test('[BLIND-SPOT] 1.7-BLIND-ERROR-005: cron image context mismatch with B2 matrix → B2 entry carries context/dockerfile override', () => {
    const cronNames = ['monthly-cost-reset', 'account-deletion-sweeper', 'fx-refresh', 'safety-log-retention'];
    for (const n of cronNames) {
      const e = prMatrix().find((x) => x.name === n);
      expect(e, `matrix entry ${n}`).toBeDefined();
      expect(repoFileExists(e.dockerfile), e.dockerfile).toBe(true);
    }
  });

  test('[BLIND-SPOT] 1.7-BLIND-DATA-003: billing-svc Deployment + fx-refresh cron are separate workloads (share values, distinct templates)', () => {
    expect(repoFileExists('infra/helm/billing-svc/templates/deployment.yaml')).toBe(true);
    expect(repoFileExists('infra/helm/billing-svc/templates/cronjob-fx-refresh.yaml')).toBe(true);
    expect(readRepoFile('infra/helm/billing-svc/templates/deployment.yaml')).toMatch(/kind: Deployment/);
    expect(readRepoFile('infra/helm/billing-svc/templates/cronjob-fx-refresh.yaml')).toMatch(/kind: CronJob/);
  });
});

// ============================================================
// AC7 (B7): payment-svc Helm chart + 5 payment secrets
// ============================================================

describe('AC7 (B7): payment-svc Helm chart + 5 payment secrets', () => {
  const CHART = 'infra/helm/payment-svc';

  test('1.7-UNIT-060: payment-svc chart exists (Chart.yaml + templates + values.yaml + values-staging.yaml)', () => {
    for (const f of [
      'Chart.yaml',
      'values.yaml',
      'values-staging.yaml',
      'templates/_helpers.tpl',
      'templates/deployment.yaml',
      'templates/service.yaml',
      'templates/serviceaccount.yaml',
      'templates/networkpolicy.yaml',
    ]) {
      expect(repoFileExists(`${CHART}/${f}`), f).toBe(true);
    }
  });

  test('1.7-UNIT-061: 5 payment secrets NEVER plaintext in values; via envFrom/secretRef to out-of-band Secret', () => {
    const dep = readRepoFile(`${CHART}/templates/deployment.yaml`);
    expect(dep).toMatch(/envFrom/);
    expect(dep).toMatch(/secretRef/);
    // No real secret material in values (only key NAMES in requiredKeys, no values).
    const vraw = readRepoFile(`${CHART}/values.yaml`) + readRepoFile(`${CHART}/values-staging.yaml`);
    expect(vraw).not.toMatch(/sk_(live|test)_/);
    expect(vraw).not.toMatch(/whsec_/);
    const v = loadYaml<any>(`${CHART}/values.yaml`);
    expect(Array.isArray(v.paymentProvider.requiredKeys)).toBe(true);
    // The chart renders no Secret object (the Secret is out-of-band).
    expect(repoFileExists(`${CHART}/templates/secret.yaml`)).toBe(false);
  });

  test('1.7-UNIT-062: payment-svc chart structure aligned with auth-svc (Pod Security Restricted, OTel, ServiceMonitor)', () => {
    const dep = readRepoFile(`${CHART}/templates/deployment.yaml`);
    expect(dep).toMatch(/runAsNonRoot: true/);
    expect(dep).toMatch(/readOnlyRootFilesystem: true/);
    expect(dep).toMatch(/OTEL_EXPORTER_OTLP_ENDPOINT/);
    expect(repoFileExists(`${CHART}/templates/servicemonitor.yaml`)).toBe(true);
  });

  test('1.7-INT-009: secretRef key names EXACTLY match apps/payment-svc env var names', () => {
    const v = loadYaml<any>(`${CHART}/values.yaml`);
    const required: string[] = v.paymentProvider.requiredKeys;
    // Env var names actually read by the provider wiring.
    const main = readRepoFile('apps/payment-svc/cmd/server/main.go');
    const codeEnv = new Set([...main.matchAll(/os\.Getenv\("([A-Z0-9_]+)"\)/g)].map((m) => m[1]));
    for (const k of required) {
      expect(codeEnv.has(k), `requiredKey ${k} not read by payment-svc code`).toBe(true);
    }
    // Spot-check the families the test design calls out.
    expect(required).toContain('STRIPE_SECRET_KEY');
    expect(required).toContain('STRIPE_WEBHOOK_SIGNING_SECRET');
    expect(required).toContain('WECHAT_PAY_MCH_ID');
    expect(required).toContain('WECHAT_PAY_APIV3_KEY');
  });

  test('1.7-INT-010: payment-svc helm lint + template renders [CI: helm template | kubeconform]', () => {
    expect(() => loadYaml(`${CHART}/Chart.yaml`)).not.toThrow();
    expect(() => loadYaml(`${CHART}/values.yaml`)).not.toThrow();
    expect(loadYaml<any>(`${CHART}/Chart.yaml`).name).toBe('payment-svc');
  });

  test('1.7-E2E-001: payment-svc present in ALL four single-source lists (B2 matrix / B3 Application / B4 SHA bump / values-staging)', () => {
    expect(nonSampleMatrix().some((e) => e.name === 'payment-svc')).toBe(true); // B2
    expect(repoFileExists(`${APPS_DIR}/payment-svc.yaml`)).toBe(true); // B3
    expect(repoFileExists(`${CHART}/values-staging.yaml`)).toBe(true); // values-staging
    // B4 SHA bump — covered because the bump iterates the Application inventory,
    // which includes payment-svc → its values-staging image gets bumped.
    const app = loadApp('payment-svc.yaml');
    expect(app.spec.source.helm.valueFiles).toContain('values-staging.yaml');
  });

  test('[BLIND-SPOT] 1.7-BLIND-ERROR-006: payment Secret missing → CreateContainerConfigError documented as ops prereq; chart only wires secretRef', () => {
    const doc = readRepoFile('docs/dev/secrets/payment-provider.md');
    expect(doc).toMatch(/envFrom|secretRef/);
    // Chart references the Secret but does not create it.
    expect(repoFileExists(`${CHART}/templates/secret.yaml`)).toBe(false);
    const v = loadYaml<any>(`${CHART}/values.yaml`);
    expect(v.paymentProvider.secretName).toBeTruthy();
  });
});

// ============================================================
// AC8 (B7b): analytics-svc Helm chart 补建
// ============================================================

describe('AC8 (B7b): analytics-svc Helm chart', () => {
  const CHART = 'infra/helm/analytics-svc';

  test('1.7-UNIT-070: analytics-svc chart exists (Chart.yaml + templates + values.yaml + values-staging.yaml)', () => {
    for (const f of [
      'Chart.yaml',
      'values.yaml',
      'values-staging.yaml',
      'templates/_helpers.tpl',
      'templates/deployment.yaml',
      'templates/service.yaml',
      'templates/serviceaccount.yaml',
      'templates/networkpolicy.yaml',
    ]) {
      expect(repoFileExists(`${CHART}/${f}`), f).toBe(true);
    }
  });

  test('1.7-UNIT-071: analytics-svc chart has NO payment-secret secretRef (not a payment svc)', () => {
    const all = readdirSync(repoPath(`${CHART}/templates`))
      .map((f) => readRepoFile(`${CHART}/templates/${f}`))
      .join('\n') + readRepoFile(`${CHART}/values.yaml`);
    expect(all).not.toMatch(/STRIPE|PAYPAL|COINBASE|ALIPAY|WECHAT|paymentProvider/);
  });

  test('1.7-UNIT-072: analytics-svc chart structure aligned with auth-svc (Pod Security Restricted, OTel, probes, SA)', () => {
    const dep = readRepoFile(`${CHART}/templates/deployment.yaml`);
    expect(dep).toMatch(/runAsNonRoot: true/);
    expect(dep).toMatch(/readOnlyRootFilesystem: true/);
    expect(dep).toMatch(/OTEL_EXPORTER_OTLP_ENDPOINT/);
    expect(dep).toMatch(/readinessProbe/);
    expect(dep).toMatch(/serviceAccountName/);
  });

  test('1.7-UNIT-073: analytics-svc chart addition does NOT change the 17 image count (Dockerfile pre-exists)', () => {
    expect(repoFileExists('apps/analytics-svc/Dockerfile')).toBe(true);
    expect(nonSampleMatrix().some((e) => e.name === 'analytics-svc')).toBe(true);
    expect(nonSampleMatrix().length).toBe(17);
  });

  test('1.7-INT-011: analytics-svc helm lint + template renders [CI: helm template | kubeconform]', () => {
    expect(() => loadYaml(`${CHART}/Chart.yaml`)).not.toThrow();
    expect(loadYaml<any>(`${CHART}/Chart.yaml`).name).toBe('analytics-svc');
  });

  test('1.7-E2E-002: analytics-svc present in ALL four single-source lists at parity with payment-svc', () => {
    expect(nonSampleMatrix().some((e) => e.name === 'analytics-svc')).toBe(true); // B2
    expect(repoFileExists(`${APPS_DIR}/analytics-svc.yaml`)).toBe(true); // B3
    expect(repoFileExists(`${CHART}/values-staging.yaml`)).toBe(true); // values-staging
    const app = loadApp('analytics-svc.yaml');
    expect(app.spec.source.helm.valueFiles).toContain('values-staging.yaml'); // B4 bump
  });
});

// ============================================================
// Cross-AC / Boundary (T8, T9)
// ============================================================

describe('Cross-AC / Boundary (T8, T9)', () => {
  test('1.7-E2E-003: T8.1 — build-matrix images ⊆ ArgoCD Applications ⊆ values-staging SHA-bump (tri-count consistent)', () => {
    // Every non-sample build image's `he-api/<name>` repository must appear in
    // SOME values-staging.yaml (main service or cron sub-image block) — proving
    // build ⊆ values-staging SHA-bump (the bump iterates the Application set, and
    // every Application has a values-staging.yaml → Application ⊆ values-staging).
    const stagingRepos: string[] = [];
    for (const c of readdirSync(repoPath(HELM_DIR))) {
      const vs = `${HELM_DIR}/${c}/values-staging.yaml`;
      if (repoFileExists(vs)) stagingRepos.push(...collectRepositories(loadYaml<any>(vs)));
    }
    for (const e of nonSampleMatrix()) {
      const found = stagingRepos.some((r) => r.endsWith(`/he-api/${e.name}`) || r.endsWith(`he-api/${e.name}`));
      expect(found, `build image ${e.name} not bumped in any values-staging`).toBe(true);
    }
    // Application ⊆ values-staging: every Application's chart has a values-staging.
    for (const app of allApps()) {
      expect(repoFileExists(`${app.spec.source.path}/values-staging.yaml`), app.spec.source.path).toBe(true);
    }
  });

  test('1.7-E2E-005: T8.4 — OUT-OF-SCOPE guard: no envs/prod touched, no values-prod / prod ArgoCD app added', () => {
    for (const c of readdirSync(repoPath(HELM_DIR))) {
      expect(repoFileExists(`${HELM_DIR}/${c}/values-prod.yaml`), `${c} values-prod`).toBe(false);
    }
    for (const f of listAppFiles()) {
      expect(f).not.toMatch(/prod/);
    }
    expect(readRepoFile(DEPLOY_WF)).not.toMatch(/envs\/prod|values-prod/);
  });

  test('1.7-UNIT-080: T8.2 — repo-wide grep aggregate: no tag:latest, no unreplaced placeholder, no "real CLI wired in Story 1.4"', () => {
    for (const f of valuesFiles()) {
      const parsed = loadYaml<any>(f);
      for (const tag of collectTags(parsed)) expect(tag, f).not.toBe('latest');
      for (const repo of collectRepositories(parsed)) expect(repo, f).not.toContain('$$');
    }
    expect(readRepoFile(DEPLOY_WF)).not.toContain(PLACEHOLDER);
    expect(readRepoFile(BUILD_WF)).not.toContain(PLACEHOLDER);
  });

  test('1.7-UNIT-081: T9.2 — all affected workflows actionlint / YAML parse green', () => {
    expect(() => loadYaml(BUILD_WF)).not.toThrow();
    expect(() => loadYaml(DEPLOY_WF)).not.toThrow();
  });

  test('1.7-INT-013: T9.1 — all affected charts parse + have Chart.yaml [CI: helm lint + helm template | kubeconform]', () => {
    for (const c of ['payment-svc', 'analytics-svc', 'billing-svc', 'api-gateway', 'auth-svc']) {
      expect(repoFileExists(`${HELM_DIR}/${c}/Chart.yaml`), c).toBe(true);
      expect(() => loadYaml(`${HELM_DIR}/${c}/values.yaml`), c).not.toThrow();
      expect(() => loadYaml(`${HELM_DIR}/${c}/values-staging.yaml`), c).not.toThrow();
    }
  });

  test('[BLIND-SPOT] 1.7-BLIND-DATA-002: every spec.project: he-api reference resolves to the he-api AppProject (no orphan project ref)', () => {
    const proj = loadYaml<any>('infra/argocd/projects/he-api.yaml');
    expect(proj.metadata.name).toBe('he-api');
    for (const app of allApps()) {
      expect(app.spec.project).toBe('he-api');
    }
  });
});
