// Package story_4_1_skeleton_test is the AUTO-GENERATED Story 4.1 test skeleton.
//
// Test Skeleton for Story 4.1: DeepSeek Adapter (Streaming + Non-Streaming).
//
// AUTO-GENERATED by QA Test Design (2026-05-19). Dev MUST implement all subtests.
// Do NOT delete any subtest — each maps to a designed scenario in:
//
//	docs/qa/assessments/4.1-test-design-20260519.md
//
// If a scenario becomes non-applicable, change to t.Skip("<reason>") with a tracking
// comment.
//
// CONSOLIDATION NOTE: this single skeleton file groups UNIT-001..040 + INT-001..016
// + 13 BLIND-SPOT overlays as t.Run subtests so no scenario is lost. CHAOS-001..006
// live in a SEPARATE file (apps/adapters/deepseek/tests/chaos_test.go, build-tag
// gated `//go:build chaos`) per Story File Locations table — NOT in this skeleton.
// Dev MUST, during T1..T4 implementation, MOVE each subtest into its natural
// per-package location enumerated in the Story File Locations table (e.g.,
// UNIT-001..006 → apps/adapters/deepseek/internal/upstream/translate_test.go;
// UNIT-021..025 → apps/adapters/deepseek/internal/upstream/sse_decoder_test.go).
// After move, replace the subtest body here with a t.Skip("moved to <path>") —
// do NOT delete the line.
//
// Race detector required for UNIT-008/011 + BLIND-CONCURRENCY-001 (`go test -race`).
//
// QA gate criteria: all 48 P0 subtests must pass before Dev marks Status = Review.
package story_4_1_skeleton_test

import (
	"testing"
)

// ============================================================
// AC1.A — translateRequest Outbound HTTPS Shape (Unit, BR-1.7)
// ============================================================

func TestStory_4_1_AC1_A_translateRequest(t *testing.T) {
	t.Run("4.1-UNIT-001/Bearer_authorization_header_set", func(t *testing.T) {
		// Priority: P0 | Level: unit
		// BR-1.7 (b) + OQ1 anchor (he.adapter.v1 proto pkg)
		// Input: translateRequest with DEEPSEEK_UPSTREAM_API_KEY="sk-test123"
		// Expected: outbound carries Authorization: Bearer sk-test123 AND
		//   import path is exactly github.com/he-api/he-api/packages/proto/gen/go/he/adapter/v1
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-001")
	})

	t.Run("4.1-UNIT-002/Content_Type_application_json", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.7 (c)
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-002")
	})

	t.Run("4.1-UNIT-003/Accept_application_json_for_nonstream", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.7 (d) non-streaming
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-003")
	})

	t.Run("4.1-UNIT-004/Accept_text_event_stream_AND_stream_options_for_stream", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.7 (d) streaming + BR-2.9 forced inclusion
		// Body MUST include stream_options.include_usage:true even if request omits it
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-004")
	})

	t.Run("4.1-UNIT-005/X_Request_Id_propagated_AND_HTTP2_forced", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.7 (e) + BR-1.5 + OQ7 anchor
		// Assert outbound proto == "HTTP/2.0" (forced via golang.org/x/net/http2.Transport)
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-005")
	})

	t.Run("4.1-UNIT-006/Body_marshal_identity_for_DeepSeek", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.7 (f) identity-mapping
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-006")
	})
}

// ============================================================
// AC1.B — adapter.Chat Non-Streaming Branch (Unit, BR-1.3)
// ============================================================

func TestStory_4_1_AC1_B_Chat_NonStreaming(t *testing.T) {
	t.Run("4.1-UNIT-007/Emits_single_terminal_chunk", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.3 single terminal chunk
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-007")
	})

	t.Run("4.1-UNIT-008/Concurrent_calls_no_shared_state", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.3 + R7 mitigation
		// MUST be run with `go test -race`
		// 50 goroutines call adapter.Chat; each receives independent ChatChunk
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-008")
	})

	t.Run("4.1-UNIT-009/Context_deadline_propagated_to_upstream", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.8 context-deadline propagation
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-009")
	})

	t.Run("4.1-UNIT-010/Emits_BR_1_9_PII_safe_logs", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.9 + R3 mitigation
		// slog test-double: NO record contains prompt content; only event/he_request_id/
		// model/messages_count/prompt_tokens/completion_tokens/total_tokens/
		// upstream_status_code/upstream_latency_ms
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-010")
	})
}

// ============================================================
// AC1.C — adapterclient.Registry (Unit, BR-1.1)
// ============================================================

func TestStory_4_1_AC1_C_Registry(t *testing.T) {
	t.Run("4.1-UNIT-011/Resolve_deepseek_v3_returns_handle_concurrent_safe", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.1 + OQ4 + R7 mitigation
		// 100 concurrent goroutines all return the same handle (no race)
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-011")
	})

	t.Run("4.1-UNIT-012/Resolve_unknown_model_returns_ok_false", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.1 fall-through
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-012")
	})
}

// ============================================================
// AC1.D — ChatCompletionsHandler.serveNonStream Adapter Branch (Unit, BR-1.2)
// ============================================================

func TestStory_4_1_AC1_D_serveNonStream(t *testing.T) {
	t.Run("4.1-UNIT-013/deepseek_v3_dispatches_to_adapter", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.2
		// Stubbed ClientHandle MUST be invoked; mock path NOT invoked
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-013")
	})

	t.Run("4.1-UNIT-014/qwen_max_falls_through_to_mock", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.2 mock-fallback preserved
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-014")
	})

	t.Run("4.1-UNIT-015/Adapter_DeadlineExceeded_emits_504_envelope", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.4 row 6
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-015")
	})

	t.Run("4.1-UNIT-016/Adapter_Unavailable_emits_502_envelope", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.4 row 7
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-016")
	})
}

// ============================================================
// AC2.A — streaming.AdapterChunker (Unit, BR-2.2)
// ============================================================

func TestStory_4_1_AC2_A_AdapterChunker(t *testing.T) {
	t.Run("4.1-UNIT-017/Emits_N_SSE_frames_plus_DONE", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.2 1:1 forward
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-017")
	})

	t.Run("4.1-UNIT-018/Returns_correct_metrics", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.2 + BR-2.7 TTFB metric
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-018")
	})

	t.Run("4.1-UNIT-019/Tail_usage_threaded_into_final_SSE_frame_before_DONE", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.4 + BR-3.7
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-019")
	})

	t.Run("4.1-UNIT-020/Flushes_each_chunk_individually", func(t *testing.T) {
		// Priority: P1 | Level: unit | BR-2.2 no re-buffering
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-020")
	})
}

// ============================================================
// AC2.B — sse_decoder.NextChunk (Unit, BR-2.3 + OQ6 strict-RFC)
// ============================================================

func TestStory_4_1_AC2_B_SSEDecoder(t *testing.T) {
	t.Run("4.1-UNIT-021/Decodes_standard_data_json_frame", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.3 happy-path
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-021")
	})

	t.Run("4.1-UNIT-022/Returns_io_EOF_on_DONE", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.3 + BR-2.8 terminator
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-022")
	})

	t.Run("4.1-UNIT-023/Returns_ErrMalformedFrame_on_missing_data_prefix", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.8 + OQ6 + R4 mitigation
		// NO silent skip — must return error
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-023")
	})

	t.Run("4.1-UNIT-024/Returns_ErrMalformedFrame_on_invalid_json", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.3 JSON unmarshal failure
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-024")
	})

	t.Run("4.1-UNIT-025/Protects_against_pathological_line", func(t *testing.T) {
		// Priority: P1 | Level: unit | BR-2.3 1 MiB buffer cap
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-025")
	})
}

// ============================================================
// AC2.C — adapter.Chat Streaming Branch (Unit, BR-1.3 + BR-2.4)
// ============================================================

func TestStory_4_1_AC2_C_Chat_Streaming(t *testing.T) {
	t.Run("4.1-UNIT-026/Emits_N_chunks_via_server_stream", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.3 + BR-2.4
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-026")
	})

	t.Run("4.1-UNIT-027/Terminal_chunk_carries_usage_intermediates_nil", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.4 terminal-chunk convention
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-027")
	})

	t.Run("4.1-UNIT-028/Forces_stream_options_include_usage_true", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.9 forced inclusion
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-028")
	})

	t.Run("4.1-UNIT-029/Client_cancel_cancels_upstream_within_200ms", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-1.8 + AC2 WHEN client disconnects + R6 mitigation
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-029")
	})
}

// ============================================================
// AC2.D — Gateway Emit-Before-Flush Boundary (Unit, BR-2.5)
// ============================================================

func TestStory_4_1_AC2_D_EmitBeforeFlushBoundary(t *testing.T) {
	t.Run("4.1-UNIT-030/Upstream_5xx_before_first_chunk_emits_JSON_envelope", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.5 pre-flush
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-030")
	})

	t.Run("4.1-UNIT-031/Upstream_5xx_after_first_chunk_emits_SSE_error_frame", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.5 + BR-2.6 post-flush
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-031")
	})

	t.Run("4.1-UNIT-032/HeadersFlushed_true_after_WriteEvent", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.5 new helper introduced by Story 4.1
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-032")
	})

	t.Run("4.1-UNIT-033/Mid_stream_error_frame_byte_exact", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-2.6 envelope shape preservation in SSE channel
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-033")
	})
}

// ============================================================
// AC3.A — usage.Normaliser Constraint Enforcement (Unit, BR-3.2 + BR-3.3)
// ============================================================

func TestStory_4_1_AC3_A_Normaliser(t *testing.T) {
	t.Run("4.1-UNIT-034/Identity_mapping_for_DeepSeek", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-3.2 DeepSeek identity
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-034")
	})

	t.Run("4.1-UNIT-035/Zero_prompt_tokens_returns_ErrUsageConstraintViolation", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-3.3 prompt-tokens positivity
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-035")
	})

	t.Run("4.1-UNIT-036/Negative_completion_tokens_returns_error", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-3.3 completion-tokens non-negative
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-036")
	})

	t.Run("4.1-UNIT-037/Total_not_equal_sum_returns_error", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-3.3 exact-sum invariant
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-037")
	})

	t.Run("4.1-UNIT-038/Negative_total_returns_error", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-3.3 total-tokens non-negative
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-038")
	})

	t.Run("4.1-UNIT-039/Interface_compatibility_for_future_vendors", func(t *testing.T) {
		// Priority: P1 | Level: unit | BR-3.2 interface-seam
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-039")
	})
}

// ============================================================
// AC3.B — Adapter BR-3.6 Structured Logging (Unit)
// ============================================================

func TestStory_4_1_AC3_B_BR_3_6_Logging(t *testing.T) {
	t.Run("4.1-UNIT-040/Chat_emits_request_end_log_with_token_counts", func(t *testing.T) {
		// Priority: P0 | Level: unit | BR-3.6 + R2 mitigation + OQ8 anchor
		// slog must carry prompt_tokens / completion_tokens / total_tokens / he_request_id
		// he_request_id extracted via packages/go-observability/requestid.FromContext
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-UNIT-040")
	})
}

// ============================================================
// Integration Scenarios (apps/adapters/deepseek/tests/adapter_test.go +
//                       apps/api-gateway/tests/adapter_integration_test.go)
// ============================================================

func TestStory_4_1_Integration_NonStreaming(t *testing.T) {
	t.Run("4.1-INT-001/NonStreaming_HappyPath_DeepSeek", func(t *testing.T) {
		// Priority: P0 | Level: integration | AC1 + BR-1.3
		// httptest.NewTLSServer returns canonical DeepSeek JSON
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-001")
	})

	t.Run("4.1-INT-002/Authorization_header_byte_exact_to_upstream", func(t *testing.T) {
		// Priority: P0 | Level: integration | BR-1.7 (b)
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-002")
	})

	t.Run("4.1-INT-003/5xx_returns_Connect_Unavailable", func(t *testing.T) {
		// Priority: P0 | Level: integration | BR-1.4 row 1
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-003")
	})

	t.Run("4.1-INT-004/4xx_401_treated_as_misconfig", func(t *testing.T) {
		// Priority: P0 | Level: integration | BR-1.4 row 5 + M2 disambiguation
		// upstream_error_kind=auth_revoked slog attribute
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-004")
	})

	t.Run("4.1-INT-005/X_Request_Id_propagated_to_upstream", func(t *testing.T) {
		// Priority: P0 | Level: integration | BR-1.5 + R3 mitigation
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-005")
	})

	t.Run("4.1-INT-006/Proto_HTTP2_negotiated_on_wire", func(t *testing.T) {
		// Priority: P0 | Level: integration | OQ7 anchor + BR-1.7 (a)
		// upstream-fake receives req.Proto == "HTTP/2.0"
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-006")
	})
}

func TestStory_4_1_Integration_Streaming(t *testing.T) {
	t.Run("4.1-INT-007/Streaming_HappyPath_DeepSeek", func(t *testing.T) {
		// Priority: P0 | Level: integration | AC2 + BR-1.3 + BR-2.4
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-007")
	})

	t.Run("4.1-INT-008/SSE_decoder_through_real_upstream_fake", func(t *testing.T) {
		// Priority: P0 | Level: integration | BR-2.3 + R4 mitigation
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-008")
	})

	t.Run("4.1-INT-009/stream_options_include_usage_forced", func(t *testing.T) {
		// Priority: P0 | Level: integration | BR-2.9
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-009")
	})

	t.Run("4.1-INT-010/Terminal_chunk_usage_threaded_to_SSE_tail", func(t *testing.T) {
		// Priority: P0 | Level: integration | BR-2.4 + BR-3.7
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-010")
	})

	t.Run("4.1-INT-011/X_He_Request_Id_propagated_via_Connect_header", func(t *testing.T) {
		// Priority: P0 | Level: integration | BR-1.5 + R3 mitigation streaming variant
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-011")
	})

	t.Run("4.1-INT-012/Client_disconnect_mid_stream_cancels_upstream", func(t *testing.T) {
		// Priority: P0 | Level: integration | AC2 WHEN client disconnects + BR-1.8 + R6
		// client closes connection after second chunk; upstream cancelled within 200ms
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-012")
	})
}

func TestStory_4_1_Integration_TokenUsage_And_Hostile(t *testing.T) {
	t.Run("4.1-INT-013/TokenUsage_oracle_invariant_fixture_replay", func(t *testing.T) {
		// Priority: P0 | Level: integration | AC3 + BR-3.1 + R2 mitigation
		// ~20-fixture set from apps/adapters/deepseek/tests/fixtures/usage/*.json
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-013")
	})

	t.Run("4.1-INT-014/MissingUsage_emits_Connect_Unavailable_with_validation_failure", func(t *testing.T) {
		// Priority: P0 | Level: integration | AC3 WHEN upstream omits usage + BR-3.4 + R2
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-014")
	})

	t.Run("4.1-INT-015/UnknownModel_400_invalid_request_envelope", func(t *testing.T) {
		// Priority: P0 | Level: integration | AC1 WHEN unknown model + BR-5.x
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-015")
	})

	t.Run("4.1-INT-016/AdapterPodDown_502_upstream_unavailable_envelope", func(t *testing.T) {
		// Priority: P0 | Level: integration | AC1 WHEN adapter Connect-RPC fails + BR-1.4 row 7
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-INT-016")
	})
}

// ============================================================
// Blind-Spot Overlay Scenarios [BLIND-SPOT]
// (per blind-spot-categories.yaml backend_api applicability)
// ============================================================

func TestStory_4_1_BlindSpot_Boundary(t *testing.T) {
	t.Run("4.1-BLIND-BOUNDARY-001/[BLIND-SPOT]/Adapter_rejects_empty_messages_array", func(t *testing.T) {
		// Priority: P1 | Level: unit | Ref: BOUNDARY-001 null/empty input
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-BOUNDARY-001")
	})

	t.Run("4.1-BLIND-BOUNDARY-002/[BLIND-SPOT]/Adapter_handles_max_messages_array_256", func(t *testing.T) {
		// Priority: P2 | Level: unit | Ref: BOUNDARY-003 max value
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-BOUNDARY-002")
	})

	t.Run("4.1-BLIND-BOUNDARY-003/[BLIND-SPOT]/Adapter_rejects_uppercase_model_id", func(t *testing.T) {
		// Priority: P1 | Level: unit | Ref: BOUNDARY-005 type/format mismatch
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-BOUNDARY-003")
	})
}

func TestStory_4_1_BlindSpot_Error(t *testing.T) {
	t.Run("4.1-BLIND-ERROR-001/[BLIND-SPOT]/DNS_failure_emits_Code_Unavailable", func(t *testing.T) {
		// Priority: P1 | Level: unit | Ref: ERROR-001 (covered by CHAOS-006 in chaos suite)
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-ERROR-001")
	})

	t.Run("4.1-BLIND-ERROR-002/[BLIND-SPOT]/Malformed_upstream_json_emits_Code_Unavailable", func(t *testing.T) {
		// Priority: P1 | Level: unit | Ref: ERROR-003 invalid response
		// validation_failure=response_unmarshal_failed slog attribute
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-ERROR-002")
	})

	t.Run("4.1-BLIND-ERROR-003/[BLIND-SPOT]/Extra_unknown_fields_in_response_ignored", func(t *testing.T) {
		// Priority: P2 | Level: unit | Ref: ERROR-003 forward-compat coverage
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-ERROR-003")
	})

	t.Run("4.1-BLIND-ERROR-004/[BLIND-SPOT]/Upstream_429_emits_Connect_Unavailable_quota_kind", func(t *testing.T) {
		// Priority: P1 | Level: unit | Ref: ERROR-005 + M2 anchor
		// upstream_error_kind=quota_exhausted slog
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-ERROR-004")
	})
}

func TestStory_4_1_BlindSpot_Concurrency(t *testing.T) {
	t.Run("4.1-BLIND-CONCURRENCY-001/[BLIND-SPOT]/100_concurrent_mixed_no_state_corruption", func(t *testing.T) {
		// Priority: P1 | Level: integration | Ref: CONCURRENCY-002 + R7 mitigation
		// MUST be run with `go test -race`
		// 100 goroutines: 50 stream=true, 50 stream=false
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-CONCURRENCY-001")
	})

	t.Run("4.1-BLIND-CONCURRENCY-002/[BLIND-SPOT]/Registry_concurrent_read_during_in_process_update_documented_as_deferred", func(t *testing.T) {
		// Priority: P2 | Level: unit | Ref: CONCURRENCY-001 — explicit non-coverage marker
		// Static registry for Story 4.1; dynamic concurrent-update semantics deferred to
		// routing-svc / Epic 6
		t.Skip("Deferred to Epic 6 routing-svc — Story 4.1 registry is static (no dynamic config swap)")
	})
}

func TestStory_4_1_BlindSpot_Data(t *testing.T) {
	t.Run("4.1-BLIND-DATA-001/[BLIND-SPOT]/RequestId_continuity_three_way_equality", func(t *testing.T) {
		// Priority: P0 | Level: integration | Ref: DATA-002 + R3 mitigation
		// header == body field == slog attribute (three-way byte equality)
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-DATA-001")
	})

	t.Run("4.1-BLIND-DATA-002/[BLIND-SPOT]/TokenUsage_byte_equality_across_chain", func(t *testing.T) {
		// Priority: P0 | Level: integration | Ref: DATA-002 + R2 mitigation
		// adapter slog total_tokens == gateway body usage.total_tokens == SDK chunk.usage.total_tokens
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-DATA-002")
	})
}

func TestStory_4_1_BlindSpot_Resource(t *testing.T) {
	t.Run("4.1-BLIND-RESOURCE-001/[BLIND-SPOT]/HTTPS_connection_released_on_all_exit_paths", func(t *testing.T) {
		// Priority: P1 | Level: integration | Ref: RESOURCE-001 + R6 mitigation
		// Table-driven: success / 5xx / cancel mid-stream / DeadlineExceeded
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-RESOURCE-001")
	})

	t.Run("4.1-BLIND-RESOURCE-002/[BLIND-SPOT]/1000_request_sustained_load_no_connection_pool_leak", func(t *testing.T) {
		// Priority: P1 | Level: integration | Ref: RESOURCE-001 sustained-load
		t.Skip("Phase-A: see per-package tests OR pending Phase B/C: 4.1-BLIND-RESOURCE-002")
	})
}
