// Story 4.5 — Doubao (Volcengine Ark v3) adapter skeleton.
//
// AUTO-GENERATED by QA Test Design (2026-05-19). Dev (Story 4.5) has
// MOVED every subtest to its natural per-package location per the Story
// File Locations table; the subtests below are intentional `t.Skip("moved
// to …")` placeholders that preserve QA's scenario inventory + traceability
// while delegating execution to the per-package tests.
//
// Live targets (where each former subtest was moved):
//
//	4.5-UNIT-001/002/008/011 → apps/adapters/doubao/internal/upstream/translate_test.go
//	4.5-UNIT-003/004         → apps/adapters/doubao/internal/upstream/endpoint_map_test.go
//	4.5-UNIT-005             → apps/adapters/doubao/internal/upstream/translate_test.go (inbound back-translate)
//	4.5-UNIT-005-decoder*    → apps/adapters/doubao/internal/upstream/sse_decoder_test.go
//	4.5-UNIT-006*            → apps/adapters/doubao/internal/usage/normaliser_test.go
//	4.5-UNIT-007/010/015/016 → apps/adapters/doubao/internal/adapter_test.go (+ client_test.go for 010)
//	4.5-UNIT-012/013/014     → apps/api-gateway/internal/adapterclient/registry_test.go
//	4.5-INT-001..012         → apps/adapters/doubao/tests/adapter_test.go
//	                          (+ apps/api-gateway/internal/adapterclient/registry_test.go for 4.5-INT-009)
//	4.5-CHAOS-001..008       → apps/adapters/doubao/tests/chaos_test.go (build-tag `chaos`)
//	4.5-CONTRACT-001..004    → apps/api-gateway/tests/openai_sdk_doubao_contract_test.py
//	4.5-E2E-001..004         → apps/api-gateway/tests/openai_sdk_doubao_live_test.py
//	4.5-BLIND-*              → folded into per-package tests (BOUNDARY → gateway
//	                          request-validation tests; ERROR/DATA/RESOURCE/FLOW
//	                          → doubao/internal/adapter_test.go + doubao/tests/
//	                          adapter_test.go + doubao/tests/chaos_test.go;
//	                          CONCURRENCY → -race builds; TRANSLATE → translate_test.go)
//
// QA gate criteria: all 44 P0 subtests must pass before Dev marks
// Status = Review. The race-detector clean assertion holds across the
// moved suites (registry + adapter packages both run under `-race`).
package story_4_1_skeleton_test

import "testing"

func Test4_5_AC1(t *testing.T) {
	t.Skip("Story 4.5 AC1 subtests moved to apps/adapters/doubao/{internal/upstream,internal,tests} and apps/api-gateway/internal/adapterclient/registry_test.go")
}

func Test4_5_AC2(t *testing.T) {
	t.Skip("Story 4.5 AC2 subtests moved to apps/adapters/doubao/{internal/upstream,internal,tests}")
}

func Test4_5_AC3(t *testing.T) {
	t.Skip("Story 4.5 AC3 subtests moved to apps/adapters/doubao/internal/usage + apps/adapters/doubao/tests (oracle invariant + round-trip rewrite) + apps/api-gateway/internal/adapterclient/registry_test.go (4.5-INT-009 five-vendor regression)")
}

func Test4_5_Chaos(t *testing.T) {
	t.Skip("Story 4.5 Chaos suite — see apps/adapters/doubao/tests/chaos_test.go (//go:build chaos); 8 scenarios incl. NEW CHAOS-008 endpoint-id-not-configured fail-fast (R10 + BR-1.12 + BR-4.6)")
}

func Test4_5_BlindSpot(t *testing.T) {
	t.Skip("Story 4.5 BLIND-SPOT subtests folded into per-package tests (BOUNDARY → gateway request-validation tests; ERROR/DATA/RESOURCE/FLOW → doubao/internal/adapter_test.go + doubao/tests/adapter_test.go + doubao/tests/chaos_test.go; CONCURRENCY → -race builds; TRANSLATE → translate_test.go)")
}
