// Package story_4_1_skeleton_test — Story 4.6 Ernie skeleton.
//
// AUTO-GENERATED by QA Test Design (2026-05-19). Dev (Story 4.6) has
// MOVED every subtest to its natural per-package location per the
// Story File Locations table; the subtests below are intentional
// `t.Skip("moved to …")` placeholders that preserve QA's scenario
// inventory + traceability while delegating execution to the per-package
// tests.
//
// Live targets (where each former subtest was moved):
//
//	4.6-UNIT-001/004/008      → apps/adapters/ernie/internal/upstream/translate_test.go
//	4.6-UNIT-004/013          → apps/adapters/ernie/internal/upstream/client_test.go
//	4.6-UNIT-007/009/015/016  → apps/adapters/ernie/internal/adapter_test.go
//	4.6-UNIT-005*             → apps/adapters/ernie/internal/upstream/sse_decoder_test.go
//	4.6-UNIT-006*             → apps/adapters/ernie/internal/usage/normaliser_test.go
//	4.6-UNIT-011/012/013/014  → apps/api-gateway/internal/adapterclient/registry_test.go
//	4.6-INT-001..008/012      → apps/adapters/ernie/tests/adapter_test.go
//	4.6-INT-009               → apps/api-gateway/internal/adapterclient/registry_test.go
//	4.6-CHAOS-001..007        → apps/adapters/ernie/tests/chaos_test.go (build-tag `chaos`)
//	4.6-CONTRACT-001..002     → apps/api-gateway/tests/openai_sdk_ernie_contract_test.py
//	4.6-E2E-001..002          → apps/api-gateway/tests/openai_sdk_ernie_live_test.py
//
// QA gate criteria: all P0 subtests must pass before Dev marks
// Status = Review. The race-detector clean assertion holds across the
// moved suites (registry + adapter packages both run under `-race`).
package story_4_1_skeleton_test

import "testing"

func Test4_6_AC1(t *testing.T) {
	t.Skip("Story 4.6 AC1 subtests moved to apps/adapters/ernie/{internal/upstream,internal,tests} and apps/api-gateway/internal/adapterclient/registry_test.go")
}

func Test4_6_AC2(t *testing.T) {
	t.Skip("Story 4.6 AC2 subtests moved to apps/adapters/ernie/{internal/upstream,internal,tests}")
}

func Test4_6_AC3(t *testing.T) {
	t.Skip("Story 4.6 AC3 subtests moved to apps/adapters/ernie/internal/usage + apps/adapters/ernie/tests (oracle invariant) + apps/api-gateway/internal/adapterclient/registry_test.go (4.6-INT-009 six-vendor regression)")
}

func Test4_6_BlindSpot(t *testing.T) {
	t.Skip("Story 4.6 BLIND-SPOT subtests folded into per-package tests (BOUNDARY → gateway request validation tests; ERROR/DATA/RESOURCE/FLOW → ernie/internal/adapter_test.go + ernie/tests/adapter_test.go + ernie/tests/chaos_test.go; CONCURRENCY → -race builds)")
}
