// Test Skeleton for Story 7.2: 多币种 + 汇率刷新.
//
// AUTO-GENERATED by QA Test Design (Turing, 2026-06-09). Per the QA contract,
// NO subtest line is deleted — each maps 1:1 to a designed scenario in:
//
//	docs/qa/assessments/7.2-test-design-20260609.md
//
// DEV STATUS (Linus, 2026-06-09): every scenario has been REALISED in its
// natural per-package location (the t.Skip body now records where), EXCEPT the
// scenarios that require buf/atlas/docker/python — those abort locally
// ([[project_toolchain_env_limits]]) and run in CI; they are marked "CI-only".
// This file stays the live scenario manifest (same convention as
// 7.1_billing_engine_skeleton_test.go).
//
// Realised locations:
//   UNIT-001..009                 -> apps/api-gateway/internal/fxrate/convert_test.go
//   UNIT-010..012                 -> apps/api-gateway/internal/fxrate/snapshot_test.go
//   UNIT-013                      -> apps/api-gateway/internal/openaierr/metadata_test.go
//   UNIT-015..020                 -> apps/billing-svc/internal/fx/{provider,refresh}_test.go
//   INT-001..017                  -> apps/api-gateway/internal/handlers/billing_read_test.go
//   INT-020..027, INT-031         -> apps/billing-svc/internal/fx/refresh_test.go
//   INT-028                       -> infra/helm/billing-svc/{templates/cronjob-fx-refresh.yaml,values.yaml}
//   INT-029                       -> scripts/ci/verify-cron-schedule.sh
//   INT-030                       -> apps/billing-svc/cmd/fx-refresh/{main_test.go,Dockerfile}
// CI-only (toolchain abort locally):
//   UNIT-014, INT-019             -> 0009 migration round-trip + seed idempotency (atlas, CI)
//   INT-018                       -> billing-svc testcontainers chat→deduct→reconcile (docker, CI);
//                                    gateway-side read-only guard realised as DATA-001 (handlers)
//   CONTRACT-001                  -> apps/api-gateway/tests/openai_sdk_*_contract_test.py (python, CI)
//   E2E-001                       -> billing-svc testcontainers cron→read (docker, CI)

// Story 7.2 multi-currency + fx-refresh skeleton. Joins the shared `tests/`
// external-test package (one package per dir — same convention as every other
// skeleton here); the Test7_2_* function names keep it collision-free.
package story_4_1_skeleton_test

import "testing"

// ============================================================
// AC1: 多币种展示 — USD 默认 / RMB 可切换 (display-only; USD stays the single SoT)
// ============================================================

func Test7_2_AC1_ConversionUtility(t *testing.T) {
	// --- convert(usdDecimal, rate) -> displayDecimal: shopspring/decimal, HALF-UP, 2dp, NEVER float (T1.1) ---
	t.Run("UNIT-001 P0: convert(12.3400, 7.21000000) -> \"88.97\" [AC1 worked example, BR-B-6]", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_GoldenVector")
	})
	t.Run("UNIT-002 P0: HALF-UP at .xx5 boundary -> rounds UP (never half-even / never down) [Q-ROUND]", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_HalfUpBoundary")
	})
	t.Run("UNIT-003 P0: zero balance convert(0.0000, rate) -> \"0.00\"", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_Zero")
	})
	t.Run("UNIT-004 P1: large balance (1_000_000.0000 x 7.21345678) -> exact, no overflow / precision loss", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_LargeMagnitude")
	})
	t.Run("UNIT-005 P0: [M-1] float-slip vector -> shopspring/decimal HALF-UP byte-exact 2dp (Decimal-not-float)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_DecimalNotFloat")
	})
	t.Run("UNIT-006 P0: rate full 8dp NUMERIC(18,8) applied BEFORE rounding display to 2dp [Q-ROUND]", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_PrecisionOrder")
	})
	t.Run("UNIT-007 P1: USD-default identity rate=1.00000000 -> current_display==current_usd at 4dp (echoes SoT, BR-B-7)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_USDIdentity4dp")
	})
	t.Run("UNIT-008 P1: purity — same (usd,rate) -> identical Decimal; no I/O, no clock", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_Pure")
	})
	t.Run("UNIT-009 P2: bounded-negative balance convert(-0.5000, 7.21) -> \"-3.61\" (7.1 E2E-003 race edge)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_NegativeBound")
	})

	// --- Latest-rate snapshot read: boot+~60s-refresh, ORDER BY fetched_at DESC LIMIT 1 (T1.2, gateway-side Q-CONVLOC) ---
	t.Run("UNIT-010 P1: boot-load latest fx_rates row per (USD,CNY) via ORDER BY fetched_at DESC LIMIT 1 [L-1, BR-C-1]", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/snapshot_test.go TestLoad_LatestFetchedAtPerPair")
	})
	t.Run("UNIT-011 P1: ~60s refresh picks up a newer row; conversion uses new rate AND fx_as_of advances", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/snapshot_test.go TestProvider_RefreshSwapsSnapshot")
	})
	t.Run("UNIT-012 P0: read path NEVER calls FxProvider — PG / in-proc snapshot only [BR-C-5]", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/snapshot_test.go TestSnapshot_LookupNoIO")
	})
}

func Test7_2_AC1_BalanceEndpoint(t *testing.T) {
	t.Run("INT-001 P0: GET /v1/balance (no selector) -> 7.1 bytes + {currency:USD, fx_rate:1.00000000, current_display==current_usd, fx_as_of} [BR-B-7]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT001_BalanceUSDDefaultAdditive")
	})
	t.Run("INT-002 P0: GET /v1/balance?currency=rmb -> {current_usd, currency:RMB, current_display:88.97, fx_rate, fx_as_of=rate.fetched_at, updated_at}", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT002_BalanceRMB")
	})
	t.Run("INT-003 P0: current_usd ALWAYS present on RMB path; *_display additive, never a replacement [BR-B-3]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT003_CurrentUSDAlwaysPresent")
	})
	t.Run("INT-004 P1: ?currency=USD explicit == no-selector; case-insensitive [BR-B-2]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT004_ExplicitUSDCaseInsensitive")
	})
	t.Run("INT-005 P1: ?currency=\" RMB \" whitespace-trimmed + case-insensitive -> RMB path [BR-B-2]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT005_WhitespaceAndEmpty")
	})
	t.Run("INT-006 P1: lazy-absent balances row + ?currency=rmb -> current_usd \"0.0000\", current_display \"0.00\"", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT006_LazyAbsentRMB")
	})
	t.Run("INT-007 P0: money discipline — current_usd/current_display/fx_rate ALL string-decimals; parse round-trip keeps precision [BR-B-4]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT007_BalanceMoneyDiscipline")
	})
}

func Test7_2_AC1_UsageEndpoint(t *testing.T) {
	t.Run("INT-008 P0: GET /v1/usage (no selector) -> 7.1 bytes + {currency:USD, fx_rate:1.00000000, total_cost_display==total_cost_usd, fx_as_of}", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT008_UsageUSDDefault")
	})
	t.Run("INT-009 P0: GET /v1/usage?currency=rmb -> total_cost_display = total_cost_usd x rate HALF-UP 2dp; fx_rate, fx_as_of added", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT009_UsageRMB")
	})
	t.Run("INT-010 P1: [M-2] mixed-currency — top-line total_cost_display RMB BUT by_model[].cost_usd STAYS USD on ?currency=rmb [Q-APISHAPE]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT010_MixedCurrencyByModel")
	})
	t.Run("INT-011 P1: GET /v1/usage zero rows + ?currency=rmb -> total_cost_usd \"0.0000\", total_cost_display \"0.00\"", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT011_UsageZeroRMB")
	})
	t.Run("INT-012 P0: usage money discipline — every money + rate field a string-decimal [BR-B-4]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT012_UsageMoneyDiscipline")
	})
}

func Test7_2_AC1_UnsupportedCurrency(t *testing.T) {
	t.Run("UNIT-013 P0: [M-1] 400_unsupported_currency registered in openaierr.CodeMetadata as invalid_request_error (Story-3.6 single-writer)", func(t *testing.T) {
		t.Skip("realised: internal/openaierr/metadata_test.go Test7_2_UNIT013_UnsupportedCurrencyRegistered")
	})
	t.Run("INT-013 P0: GET /v1/balance?currency=eur -> 400 400_unsupported_currency; reject BEFORE any PG read [BR-B-5]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT013_BalanceUnsupportedBeforeRead")
	})
	t.Run("INT-014 P0: ?currency=xyz -> 400; NO silent fallback to USD [BR-B-5]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT014_BalanceArbitraryCurrency")
	})
	t.Run("INT-015 P1: 400 body matches §5.1.2 envelope {type:invalid_request_error, code:400_unsupported_currency} [M-1]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT015_UnsupportedEnvelope")
	})
	t.Run("INT-016 P1: GET /v1/usage?currency=eur -> same 400 (both endpoints reject identically)", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT016_UsageUnsupported")
	})
}

func Test7_2_AC1_ColdStartGuard(t *testing.T) {
	t.Run("INT-017 P1: ?currency=rmb but NO fx_rates row (impossible post-seed) -> 200 degraded USD-only: current_display==current_usd, fx_rate:\"1.00000000\", fx_degraded:true + slog fx_rate_missing + metric [Q-FXFAIL]", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT017_ColdStartDegraded")
	})
}

// ============================================================
// AC2: 汇率刷新 — fx_rates 表 + 每日 UTC 00:00 (外部源 + stale-serve)
// ============================================================

func Test7_2_AC2_MigrationAndSeed(t *testing.T) {
	t.Run("INT-019 P1: 0009 up->down round-trip on scratch PG; fx_rates shape + PK(base,quote,fetched_at); bootstrap seed present; current_rmb UNTOUCHED; atlas.sum [BR-C-6]", func(t *testing.T) {
		t.Skip("CI-only: migrations/postgres/0009_create_fx_rates.sql + atlas.sum; atlas round-trip runs in CI (atlas aborts locally, [[project_toolchain_env_limits]])")
	})
	t.Run("UNIT-014 P1: bootstrap seed idempotency — re-apply ON CONFLICT DO NOTHING seed twice -> exactly ONE bootstrap row [BR-C-6]", func(t *testing.T) {
		t.Skip("CI-only: 0009 seed uses ON CONFLICT (base,quote,fetched_at) DO NOTHING with a fixed fetched_at; idempotency verified on scratch PG in CI")
	})
}

func Test7_2_AC2_FxProvider(t *testing.T) {
	t.Run("UNIT-015 P0: FxProvider.Get(ctx) success -> positive decimal.Decimal USD->CNY [Q-FXSRC]", func(t *testing.T) {
		t.Skip("realised: internal/fx/provider_test.go Test7_2_UNIT015_HTTPProviderSuccess")
	})
	t.Run("UNIT-016 P0: FX_MANUAL_USD_CNY set -> bypass provider, return env rate (dev/CI/air-gapped) [Q-FXSRC]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_UNIT016_ManualOverride")
	})
	t.Run("UNIT-017 P0: FX_MANUAL_USD_CNY unparseable / <=0 -> fail-fast boot error", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_UNIT017_ManualFailFast")
	})
	t.Run("UNIT-018 P0: [Q-FXSRC ADD] provider call carries a hard context deadline; deadline propagated & enforced", func(t *testing.T) {
		t.Skip("realised: internal/fx/provider_test.go Test7_2_UNIT018_BoundedFetchDeadline")
	})
	t.Run("UNIT-019 P1: secret base-URL/key env-injected, NEVER logged (slog redaction); rate value MAY be logged [BR-C-7]", func(t *testing.T) {
		t.Skip("realised: internal/fx/provider_test.go Test7_2_UNIT019_SecretNeverInError")
	})
	t.Run("UNIT-020 P0: rate validation — finite, >0, NUMERIC(18,8); NaN/Inf/zero/negative rejected", func(t *testing.T) {
		t.Skip("realised: internal/fx/provider_test.go Test7_2_UNIT020_RateValidation + refresh_test.go INT-024")
	})
}

func Test7_2_AC2_RefreshAndStaleServe(t *testing.T) {
	t.Run("INT-020 P0: fx-refresh success -> INSERT {USD,CNY,rate,source,fetched_at=now()}; active=ORDER BY fetched_at DESC LIMIT 1; fx_refresh.completed [BR-C-1]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT020_RefreshSuccessInserts")
	})
	t.Run("INT-021 P0: STALE-SERVE provider TIMEOUT -> NO insert, last row active, fx_refresh.failed + alert, cron exit 0 [BR-C-3]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT021_StaleServeOnTimeout")
	})
	t.Run("INT-022 P0: provider NON-2xx (500/503) -> stale-serve (no insert, exit 0, alert) [BR-C-3]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT022_023_StaleServeOnProviderError + provider_test.go BLIND-ERROR-003")
	})
	t.Run("INT-023 P0: provider MALFORMED (bad JSON / missing field / wrong type) -> stale-serve [BR-C-3]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT022_023_StaleServeOnProviderError + provider_test.go UNIT-020")
	})
	t.Run("INT-024 P0: provider RATE<=0 (zero/negative) -> REJECT; NEVER persist or serve zero/null [BR-C-3 crux]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT024_RejectNonPositiveRate")
	})
	t.Run("INT-025 P1: provider same rate as last -> append a new harmless row (append-only; reads take latest) [BR-C-4]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT025_SameRateAppends")
	})
	t.Run("INT-026 P0: idempotency — same-UTC-day re-run appends; read takes ORDER BY fetched_at DESC LIMIT 1; NO UPDATE-in-place [BR-C-4]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT026_DayIdempotencyAppends + INT027_AppendOnlyNoUpdate")
	})
	t.Run("INT-027 P1: append-only retention — historical rows retained after N refreshes; active=latest only [BR-C-1]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT027_AppendOnlyNoUpdate")
	})
}

func Test7_2_AC2_CronManifestAndObservability(t *testing.T) {
	t.Run("INT-028 P0: [H-2] CronJob schedule==\"0 0 * * *\", timeZone Etc/UTC, concurrencyPolicy Forbid, startingDeadlineSeconds 200, backoffLimit 0, history 3 (5.4 parity)", func(t *testing.T) {
		t.Skip("realised: infra/helm/billing-svc/values.yaml (fxRefresh hardening literals) + templates/cronjob-fx-refresh.yaml (field bindings)")
	})
	t.Run("INT-029 P0: [H-2] scripts/ci/verify-cron-schedule.sh locks the new 0 0 * * * literal (drift gold-gate)", func(t *testing.T) {
		t.Skip("realised: scripts/ci/verify-cron-schedule.sh verify_schedule fx-refresh \"0 0 * * *\"")
	})
	t.Run("INT-030 P1: [H-1] CronJob invokes DEDICATED apps/billing-svc/cmd/fx-refresh (own main + Dockerfile + Helm image), NOT a cmd/server subcommand", func(t *testing.T) {
		t.Skip("realised: apps/billing-svc/cmd/fx-refresh/{main.go,main_test.go,Dockerfile} + helm image he-api/fx-refresh")
	})
	t.Run("INT-031 P1: observability — fx_refresh.completed/failed counters + last-success-timestamp gauge; non-PII slog (rate ok, secret never) [BR-C-7]", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go Test7_2_INT031_Observability + metrics.go")
	})
}

// ============================================================
// Cross-AC integration / SoT-preservation (T3)
// ============================================================

func Test7_2_CrossAC(t *testing.T) {
	t.Run("INT-018 P0 CRITICAL: SoT-preservation — chat->deduct->reconcile w/ ?currency=rmb reads interleaved -> deduction/ledger/402-gate/reconciliation BYTE-FOR-BYTE unchanged [BR-B-1, Q-SOT]", func(t *testing.T) {
		t.Skip("CI-only: testcontainers/compose (docker aborts locally). Gateway-side read-only guard realised: internal/handlers/billing_read_test.go Test7_2_DATA001_DisplayReadIsWriteFree")
	})
	t.Run("CONTRACT-001 P0: USD-default GET /v1/balance + /v1/usage byte-compatible with 7.1 via extra-field-tolerant round-trip (4.7-CONTRACT-001) [BR-B-7]", func(t *testing.T) {
		t.Skip("CI-only: python OpenAI-SDK tolerant round-trip (apps/api-gateway/tests/*.py). Local proxy: INT-001/INT-008 assert additive-only fields")
	})
	t.Run("E2E-001 P0: cron inserts fresh rate -> GET /v1/balance?currency=rmb reflects it (fx_as_of advances); provider-down next cron -> prior rate still served [BR-C-3/C-5]", func(t *testing.T) {
		t.Skip("CI-only: testcontainers cron→read end-to-end (docker). Components realised: fx.Refresh (INT-020) + fxrate.Provider refresh (UNIT-011) + stale-serve (INT-021)")
	})
}

// ============================================================
// Blind Spot Scenarios [BLIND-SPOT]
// Backend-API: BOUNDARY, ERROR, CONCURRENCY, DATA, RESOURCE (+ FLOW)
// ============================================================

func Test7_2_BlindSpots(t *testing.T) {
	// --- BOUNDARY ---
	t.Run("[BLIND-SPOT] BOUNDARY-001 P1: zero balance convert -> \"0.00\" (xref UNIT-003)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_Zero")
	})
	t.Run("[BLIND-SPOT] BOUNDARY-002 P1: very-large balance x 8dp rate -> no overflow / precision loss (xref UNIT-004)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_LargeMagnitude")
	})
	t.Run("[BLIND-SPOT] BOUNDARY-003 P0: HALF-UP at exact .xx5 boundary -> rounds up (xref UNIT-002)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_HalfUpBoundary")
	})
	t.Run("[BLIND-SPOT] BOUNDARY-004 P1: ?currency= empty string -> treated as DEFAULT usd (BR-B-2; distinguish empty from invalid)", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_INT005_WhitespaceAndEmpty (empty case)")
	})
	t.Run("[BLIND-SPOT] BOUNDARY-005 P2: rate full 8dp (7.21345678) applied then 2dp-rounded — boundary precision", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/convert_test.go TestConvert_PrecisionOrder")
	})
	// --- ERROR ---
	t.Run("[BLIND-SPOT] ERROR-001 P1: snapshot ~60s refresh PG-read fails -> keep last-good snapshot + slog WARN; reads continue (xref UNIT-011)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/snapshot_test.go TestProvider_RefreshErrorKeepsLastGood")
	})
	t.Run("[BLIND-SPOT] ERROR-002 P0: FX provider network failure (timeout/conn refused) on cron -> stale-serve (xref INT-021)", func(t *testing.T) {
		t.Skip("realised: internal/fx/provider_test.go Test7_2_BLIND_ERROR002_NetworkFailure + refresh_test.go INT-021")
	})
	t.Run("[BLIND-SPOT] ERROR-003 P0: FX provider 503 service-unavailable -> stale-serve (xref INT-022)", func(t *testing.T) {
		t.Skip("realised: internal/fx/provider_test.go Test7_2_BLIND_ERROR003_Non2xx + refresh_test.go INT-022")
	})
	t.Run("[BLIND-SPOT] ERROR-004 P1: FX provider invalid response (bad JSON / missing-field / wrong type) -> stale-serve (xref INT-023)", func(t *testing.T) {
		t.Skip("realised: internal/fx/provider_test.go Test7_2_UNIT020_RateValidation + refresh_test.go INT-023")
	})
	// --- CONCURRENCY ---
	t.Run("[BLIND-SPOT] CONCURRENCY-001 P1: two cron runs overlap same UTC day -> append-only harmless, read takes latest, no lost-update; Forbid also guards (xref INT-026)", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go INT-026 (append-only, no UPDATE) + helm concurrencyPolicy: Forbid")
	})
	t.Run("[BLIND-SPOT] CONCURRENCY-002 P1: snapshot refresh races a fresh cron INSERT -> read sees old OR new latest row, never torn/partial (atomic row read)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/snapshot.go atomic.Pointer[Snapshot] swap (lock-free read sees old-or-new, never torn); covered by RefreshSwapsSnapshot")
	})
	// --- DATA ---
	t.Run("[BLIND-SPOT] DATA-001 P0: SoT — RMB display reads NEVER write balances.* / usage_ledger; 7.1 reconciliation byte-identical (xref INT-018)", func(t *testing.T) {
		t.Skip("realised: internal/handlers/billing_read_test.go Test7_2_DATA001_DisplayReadIsWriteFree")
	})
	t.Run("[BLIND-SPOT] DATA-002 P1: fx_rates insert atomic — no orphan/partial row on a failed cron insert", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh.go single-statement INSERT (atomic) + refresh_test.go INT-020")
	})
	// --- RESOURCE ---
	t.Run("[BLIND-SPOT] RESOURCE-001 P1: FX provider HTTP client/conn released on timeout (no leak); ctx deadline enforced (xref UNIT-018)", func(t *testing.T) {
		t.Skip("realised: internal/fx/provider.go (defer body drain+close) + provider_test.go UNIT-018")
	})
	t.Run("[BLIND-SPOT] RESOURCE-002 P2: snapshot ~60s ticker goroutine stops on ctx cancel (no goroutine leak) (7.1 parity)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/snapshot_test.go TestProvider_RunStopsOnCancel")
	})
	t.Run("[BLIND-SPOT] RESOURCE-003 P2: PG connection returned to pool after cron INSERT / on error (no pool leak)", func(t *testing.T) {
		t.Skip("realised: internal/fxrate/snapshot.go defer rows.Close() + fx-refresh defer pool.Close(); CI pool-leak check")
	})
	// --- FLOW ---
	t.Run("[BLIND-SPOT] FLOW-001 P1: cold-start — fresh DB, cron never ran -> bootstrap seed serves AC1 until first refresh (xref INT-017/INT-019)", func(t *testing.T) {
		t.Skip("realised: migrations 0009 bootstrap seed + internal/handlers/billing_read_test.go INT-017 cold-start guard")
	})
	t.Run("[BLIND-SPOT] FLOW-002 P2: provider recovers after a failure day -> next cron inserts fresh row, fx_as_of advances, stale window ends (xref E2E-001)", func(t *testing.T) {
		t.Skip("realised: internal/fx/refresh_test.go INT-020 (recovery = next success appends) + fxrate snapshot UNIT-011 (fx_as_of advances)")
	})
}
