"""Story 4.7 — `GET /public/models` unauthenticated contract test skeleton.

AUTO-GENERATED by QA Test Design (2026-05-20). Dev (Story 4.7) MUST
implement every test case below. The OpenAI SDK has no key-less
``ModelList`` client, so this surface is exercised via plain ``httpx``.

Scenarios:

  4.7-CONTRACT-003 — Unauthenticated ``GET /public/models`` returns
                     200 + well-shaped body with 11 entries each carrying
                     the 7-key ``capabilities`` sub-struct (BR-1.7).
  4.7-CONTRACT-004 — ``POST /public/models`` returns 405 +
                     ``code=405_method_not_allowed`` envelope +
                     ``Allow: GET`` response header (OQ-4.7-6 ratified).
  4.7-CONTRACT-005 — ``GET /v1/models`` (bearer) and ``GET /public/models``
                     (no bearer) return parse-identical JSON
                     (R1 single-source-of-truth SDK-tier confirmation).

Env contract (Story 3.3 cascade):

  - HE_API_TEST_GATEWAY_URL — gateway base URL, e.g. ``http://localhost:8080``.
    Tests skip when unset (CI-default).
  - HE_API_TEST_API_KEY     — bearer for the ``/v1/models`` cross-endpoint
    check at CONTRACT-005.

QA gate: every test case MUST pass before Dev marks Status = Review.
Converting a test to ``pytest.skip(...)`` requires a written reason in
the docstring citing why the scenario is not applicable.
"""

from __future__ import annotations

import os

import httpx
import pytest

# Story 4.8 T4.11 — rewire per-entry shape to shared helper. Keep the
# byte-identity test (CONTRACT-005) inline since it's test-specific.
from _protocol_invariants import assert_model_entry_shape

GATEWAY_URL = os.environ.get("HE_API_TEST_GATEWAY_URL")
API_KEY = os.environ.get("HE_API_TEST_API_KEY")

pytestmark = pytest.mark.skipif(
    GATEWAY_URL is None,
    reason="HE_API_TEST_GATEWAY_URL not set; skipping Story-4.7 public-models contract tests",
)


# ---------------------------------------------------------------------------
# AC1 — Public endpoint wire contract
# ---------------------------------------------------------------------------


CAPABILITY_BOOL_KEYS = (
    "chat",
    "streaming",
    "function_calling",
    "vision",
    "json_mode",
)
CAPABILITY_INT_KEYS = (
    "context_window_tokens",
    "max_output_tokens",
)


def test_4_7_contract_003_public_models_unauthenticated_get_returns_well_shaped_body(
    httpx_client: httpx.Client,
) -> None:
    """4.7-CONTRACT-003 — Unauth GET /public/models returns 200 + 11-entry body.

    Priority: P0 (load-bearing R6 — unauthenticated wire contract).
    """
    resp = httpx_client.get(_public_models_url())
    assert resp.status_code == 200, f"status={resp.status_code} body={resp.text}"
    content_type = resp.headers.get("Content-Type", "")
    assert content_type.startswith("application/json"), (
        f"Content-Type={content_type!r}"
    )

    body = resp.json()
    assert body.get("object") == "list", f"object={body.get('object')!r}"
    data = body.get("data")
    assert isinstance(data, list), f"data is {type(data)!r}"
    assert len(data) == 11, f"len(data)={len(data)}"

    # Story 4.8 T4.11 — per-entry shape delegated to the shared helper. The
    # Story 4.7 capability sub-key typing (bool × 5 + int × 2) stays inline
    # because it's narrower than the helper's generic dict assertion.
    for entry in data:
        assert_model_entry_shape(entry)
        caps = entry["capabilities"]
        for k in CAPABILITY_BOOL_KEYS:
            assert k in caps, f"{entry['id']}: capabilities missing {k!r}"
            assert isinstance(caps[k], bool), (
                f"{entry['id']}: capabilities.{k} type={type(caps[k])!r}, want bool"
            )
        for k in CAPABILITY_INT_KEYS:
            assert k in caps, f"{entry['id']}: capabilities missing {k!r}"
            assert isinstance(caps[k], int) and not isinstance(caps[k], bool), (
                f"{entry['id']}: capabilities.{k} type={type(caps[k])!r}, want int"
            )


def test_4_7_contract_004_public_models_POST_returns_405_method_not_allowed(
    httpx_client: httpx.Client,
) -> None:
    """4.7-CONTRACT-004 — POST /public/models returns 405 envelope + Allow: GET.

    Priority: P0 (load-bearing R14 — NEW envelope code per OQ-4.7-6).
    """
    resp = httpx_client.post(_public_models_url())
    assert resp.status_code == 405, f"status={resp.status_code} body={resp.text}"
    assert resp.headers.get("Allow") == "GET", (
        f"Allow={resp.headers.get('Allow')!r}"
    )

    body = resp.json()
    error = body.get("error")
    assert isinstance(error, dict), f"body.error is {type(error)!r}"
    assert error.get("code") == "405_method_not_allowed", (
        f"error.code={error.get('code')!r}"
    )
    assert error.get("message") == "Only GET is allowed on /public/models.", (
        f"error.message={error.get('message')!r}"
    )
    assert error.get("type") == "invalid_request_error", (
        f"error.type={error.get('type')!r} (per §5.1.2 mapping)"
    )


def test_4_7_contract_005_public_models_body_matches_v1_models_body(
    httpx_client: httpx.Client,
) -> None:
    """4.7-CONTRACT-005 — Public + bearer-gated endpoints parse-equal.

    Priority: P0 (R1 SDK-tier confirmation of byte-identical claim).
    """
    if API_KEY is None:
        pytest.skip(
            "HE_API_TEST_API_KEY not set; cross-endpoint comparison requires a valid bearer"
        )

    v1 = httpx_client.get(
        _v1_models_url(), headers={"Authorization": f"Bearer {API_KEY}"}
    )
    assert v1.status_code == 200, f"/v1/models status={v1.status_code} body={v1.text}"
    pub = httpx_client.get(_public_models_url())
    assert pub.status_code == 200, f"/public/models status={pub.status_code} body={pub.text}"

    # Deep dict equality on the parsed JSON. The byte-identity assertion
    # lives at 4.7-INT-001 (Go integration test); CONTRACT-005 is the
    # SDK-tier sibling that proves the same claim through the wire.
    assert v1.json() == pub.json(), (
        "/v1/models and /public/models body mismatch:\n"
        f"  /v1: {v1.text}\n  /public: {pub.text}"
    )


# ---------------------------------------------------------------------------
# Helper scaffolding — Dev MAY add fixtures here as needed.
# ---------------------------------------------------------------------------


def _public_models_url() -> str:
    """Return the canonical public-models URL for the test gateway."""
    assert GATEWAY_URL is not None  # pytestmark already skipped if unset
    return f"{GATEWAY_URL.rstrip('/')}/public/models"


def _v1_models_url() -> str:
    """Return the canonical /v1/models URL for the test gateway."""
    assert GATEWAY_URL is not None
    return f"{GATEWAY_URL.rstrip('/')}/v1/models"


@pytest.fixture()
def httpx_client() -> httpx.Client:
    """Shared httpx.Client session for the contract suite.

    Dev MAY widen the fixture scope to ``module`` if test isolation
    tolerates session reuse; the default ``function`` scope is safe.
    """
    with httpx.Client(timeout=httpx.Timeout(10.0)) as client:
        yield client
