apiVersion: v1
kind: ServiceAccount
metadata:
  name: adapter-deepseek
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: adapter-deepseek
    app.kubernetes.io/part-of: he-api
