package contentsafety

// Story 8.3 (AC2): 流式出参过滤 — StreamGuard sliding-window no-false-negative core.
//
// Skeleton AUTO-GENERATED by QA Test Design (Turing, 2026-06-11); implemented by Dev.
// Each test maps to a designed scenario in docs/qa/assessments/8.3-test-design-20260611.md.
//
// BINDING design targets (Architect Round-1 rulings — SUPERSEDE the SM proposals):
//   OQ-8.3-2  scan-before-forward: Observe reports a hit on the term-COMPLETING delta BEFORE the
//             caller forwards it (the completing delta is withheld, never flushed).
//   OQ-8.3-3  window = max(512, max(TermLengths())); the no-FN bound is `window >= longest term`,
//             derived from corpus truth at NewStreamGuard time (NOT a bare magic constant).
//   M-3       the raw rune buffer is scanned via the shared Normalize-d ScanText, so the gravest
//             case is a zero-width-padded term split across deltas — it MUST still be detected.
//
// HARD gates (block merge): UNIT-011, 012, 014, 015, 031, 032. Latency (BENCH) is a SOFT gate.

import (
	"fmt"
	"strings"
	"sync"
	"testing"

	safetylexicon "github.com/he-api/he-api/packages/safety-lexicon"
)

// ----- guard construction helpers ---------------------------------------

func badwordGuard(t *testing.T) *StreamGuard {
	t.Helper()
	lex := lexiconWith(t, enRow("badword", safetylexicon.CategoryAbuse, safetylexicon.SeverityHigh, 4001))
	return NewStreamGuard(NewScanner(lex))
}

// observeAll feeds deltas in order and returns the first (Match, hitIndex);
// hitIndex == -1 when the sequence never fires.
func observeAll(g *StreamGuard, deltas []string) (safetylexicon.Match, int) {
	for i, d := range deltas {
		if m, hit := g.Observe(d); hit {
			return m, i
		}
	}
	return safetylexicon.Match{}, -1
}

// ============================================================
// AC2: StreamGuard.Observe — base detection
// ============================================================

func TestStreamGuard_SingleDeltaHit(t *testing.T) {
	// 8.3-UNIT-010 | P0 | unit
	g := badwordGuard(t)
	m, hit := g.Observe("please say badword now")
	if !hit {
		t.Fatal("term wholly inside one delta not detected")
	}
	if m.Canonical != "badword" {
		t.Fatalf("matched_rule = %q, want badword", m.Canonical)
	}
}

func TestStreamGuard_CrossSeamSplit(t *testing.T) {
	// 8.3-UNIT-011 | P0 | unit | HARD no-FN
	g := badwordGuard(t)
	if _, hit := g.Observe("please say bad"); hit {
		t.Fatal("partial first delta should NOT match")
	}
	m, hit := g.Observe("word now")
	if !hit {
		t.Fatal("FALSE-NEGATIVE: term split across two deltas not detected at the seam")
	}
	if m.Canonical != "badword" {
		t.Fatalf("matched_rule = %q, want badword", m.Canonical)
	}

	// Same defect class for a CJK term (no word boundaries).
	zlex := lexiconWith(t, zhRow("敏政词甲", safetylexicon.CategoryPolitical, safetylexicon.SeverityHigh, 4002))
	zg := NewStreamGuard(NewScanner(zlex))
	_, idx := observeAll(zg, []string{"前缀敏政", "词甲后缀"})
	if idx != 1 {
		t.Fatalf("CJK cross-seam term detected at delta %d, want the seam delta (1)", idx)
	}
}

func TestStreamGuard_MultiDeltaSplit(t *testing.T) {
	// 8.3-UNIT-012 | P0 | unit | HARD no-FN
	zlex := lexiconWith(t, zhRow("敏政词甲", safetylexicon.CategoryPolitical, safetylexicon.SeverityHigh, 4003))
	g := NewStreamGuard(NewScanner(zlex))
	m, idx := observeAll(g, []string{"敏", "政", "词", "甲"})
	if idx != 3 {
		t.Fatalf("term split across 4 deltas detected at delta %d, want the completing delta (3)", idx)
	}
	if m.Canonical != "敏政词甲" {
		t.Fatalf("matched_rule = %q, want 敏政词甲", m.Canonical)
	}
}

func TestStreamGuard_ScanBeforeForward(t *testing.T) {
	// 8.3-UNIT-013 | P0 | unit | OQ-8.3-2
	// The hit MUST fire on the delta that COMPLETES the term (so the caller can
	// withhold it before WriteEvent). Every prior delta must be clean.
	g := badwordGuard(t)
	deltas := []string{"please ", "say ", "bad", "word"}
	for i, d := range deltas {
		m, hit := g.Observe(d)
		if i < len(deltas)-1 {
			if hit {
				t.Fatalf("hit fired early on delta %d (%q) — would have leaked the completing delta", i, d)
			}
			continue
		}
		if !hit {
			t.Fatal("scan-before-forward: completing delta did not report the hit")
		}
		if m.Canonical != "badword" {
			t.Fatalf("matched_rule = %q, want badword", m.Canonical)
		}
	}
}

// ============================================================
// AC2 / OQ-8.3-3: window bound = corpus truth (no-FN by construction)
// ============================================================

func TestStreamGuard_WindowCoversLongestTerm(t *testing.T) {
	// 8.3-UNIT-014 | P0 | unit | HARD no-FN | OQ-8.3-3 / BR-2.5
	longTerm := strings.Repeat("z", 60) // normalize-stable ASCII, ≤100-rune cap
	lex := lexiconWith(t, enRow(longTerm, safetylexicon.CategoryOther, safetylexicon.SeverityLow, 4004))
	g := NewStreamGuard(NewScanner(lex))

	lengths := lex.TermLengths()
	maxTerm := lengths[len(lengths)-1]
	if g.Window() < maxTerm {
		t.Fatalf("window %d < max(TermLengths()) %d — a stored term could be split out of the window", g.Window(), maxTerm)
	}

	// Split the longest term across the seam → still detected (no-FN by construction).
	m, idx := observeAll(g, []string{"head " + longTerm[:30], longTerm[30:] + " tail"})
	if idx != 1 {
		t.Fatalf("longest term split across the seam detected at delta %d, want 1", idx)
	}
	if m.Canonical != longTerm {
		t.Fatalf("matched_rule = %q, want the 60-rune term", m.Canonical)
	}
}

func TestStreamGuard_SingleDeltaLargerThanWindow(t *testing.T) {
	// 8.3-UNIT-015 | P0 | unit | HARD no-FN (latent-hole guard — forbids trim-then-scan)
	g := badwordGuard(t)
	// ONE delta longer than the window, with the term in its LEADING portion. A
	// trim-then-scan implementation would drop the leading term → false-negative.
	huge := "badword" + strings.Repeat("x", g.Window()+200)
	m, hit := g.Observe(huge)
	if !hit {
		t.Fatal("FALSE-NEGATIVE: term in the leading portion of an over-window delta missed (trim-then-scan?)")
	}
	if m.Canonical != "badword" {
		t.Fatalf("matched_rule = %q, want badword", m.Canonical)
	}
}

// ============================================================
// AC2: bounded buffer / Bloom prefilter / determinism
// ============================================================

func TestStreamGuard_CleanStreamNoFire_BufferBounded(t *testing.T) {
	// 8.3-UNIT-016 | P1 | unit  (also BLIND-RESOURCE-002)
	g := badwordGuard(t)
	for i := 0; i < 2000; i++ {
		if _, hit := g.Observe("the quick brown fox jumps over the lazy dog "); hit {
			t.Fatalf("clean stream fired a hit at delta %d", i)
		}
		if len(g.buf) > g.window {
			t.Fatalf("buffer %d exceeded window %d at delta %d (unbounded growth)", len(g.buf), g.window, i)
		}
	}
}

func TestStreamGuard_BloomPrefilterExcludesCleanText(t *testing.T) {
	// 8.3-UNIT-017 | P1 | unit
	spy := &spyLex{inner: lexiconWith(t, enRow("badword", safetylexicon.CategoryAbuse, safetylexicon.SeverityHigh, 4005))}
	g := NewStreamGuard(newScannerFromLexicon(spy))
	for i := 0; i < 20; i++ {
		if _, hit := g.Observe("the quick brown fox "); hit {
			t.Fatal("clean text unexpectedly matched")
		}
	}
	if spy.might == 0 {
		t.Fatal("Bloom MightContain never consulted")
	}
	if spy.look > spy.mightTrue {
		t.Fatalf("Lookup (%d) exceeded Bloom positives (%d) — Lookup ran without a Bloom positive", spy.look, spy.mightTrue)
	}
}

func TestStreamGuard_Deterministic(t *testing.T) {
	// 8.3-UNIT-018 | P0 | unit | BR-4.3
	seq := []string{"please ", "say ", "bad", "word", " now"}
	m1, i1 := observeAll(badwordGuard(t), seq)
	m2, i2 := observeAll(badwordGuard(t), seq)
	if i1 != i2 {
		t.Fatalf("non-deterministic termination point: %d vs %d", i1, i2)
	}
	if m1.Canonical != m2.Canonical {
		t.Fatalf("non-deterministic matched_rule: %q vs %q", m1.Canonical, m2.Canonical)
	}
	if i1 != 3 {
		t.Fatalf("termination point = %d, want 3 (the completing delta)", i1)
	}
}

// ============================================================
// AC4: exhaustive no-FN (stream) + normalization-evasion × cross-seam (M-3)
// ============================================================

func TestStreamGuard_ExhaustiveNoFalseNegative_Stream(t *testing.T) {
	// 8.3-UNIT-031 | P0 | unit | HARD (BR-2.5)
	lex := sixByTwoLexicon(t)
	for _, seed := range sixByTwo {
		raw := []rune(seed.raw)
		mid := len(raw) / 2

		// (a) wholly inside one delta, embedded mid-text.
		whole := NewStreamGuard(NewScanner(lex))
		m, idx := observeAll(whole, []string{"noise " + seed.raw + " noise"})
		if idx < 0 {
			t.Fatalf("FALSE-NEGATIVE (compliance breach): term %q (cat=%s lang=%s) not detected whole-in-delta",
				seed.raw, seed.cat, seed.lang)
		}
		if m.Canonical != safetylexicon.Normalize(seed.raw) {
			t.Fatalf("term %q reported wrong canonical %q", seed.raw, m.Canonical)
		}

		// (b) split across a delta boundary, embedded mid-text.
		split := NewStreamGuard(NewScanner(lex))
		_, sidx := observeAll(split, []string{"前缀" + string(raw[:mid]), string(raw[mid:]) + "后缀"})
		if sidx < 0 {
			t.Fatalf("FALSE-NEGATIVE (compliance breach): term %q (cat=%s lang=%s) not detected when split across deltas",
				seed.raw, seed.cat, seed.lang)
		}
	}
}

func TestStreamGuard_EvasionTimesCrossSeam(t *testing.T) {
	// 8.3-UNIT-032 | P0 | unit | HARD (M-3)
	g := badwordGuard(t)
	// (a) zero-width padding (U+200C) WITHIN the term AND split across deltas.
	if _, idx := observeAll(g, []string{"ba", "d‌wo", "rd"}); idx < 0 {
		t.Fatal("FALSE-NEGATIVE (M-3): zero-width-padded term split across deltas not detected")
	}

	// (b) full-width + mixed case, split rune-by-rune across deltas → "badword".
	g2 := badwordGuard(t)
	if _, idx := observeAll(g2, []string{"Ｂ", "ａ", "ｄ", "Wo", "rd"}); idx < 0 {
		t.Fatal("FALSE-NEGATIVE (M-3): full-width/mixed-case term split across deltas not detected")
	}
}

// ============================================================
// BLIND-SPOT
// ============================================================

func TestStreamGuard_BoundaryEdgeOfWindow(t *testing.T) {
	// 8.3-BLIND-BOUNDARY-002 | P1 | unit | BOUNDARY-004
	g := badwordGuard(t)
	// Fill the window with clean runes, then split "badword" across the slide.
	filler := strings.Repeat("a", g.Window())
	if _, hit := g.Observe(filler); hit {
		t.Fatal("clean filler fired a hit")
	}
	if _, hit := g.Observe("bad"); hit {
		t.Fatal("partial 'bad' fired a hit")
	}
	m, hit := g.Observe("word")
	if !hit {
		t.Fatal("FALSE-NEGATIVE: term straddling the window-slide boundary not detected")
	}
	if m.Canonical != "badword" {
		t.Fatalf("matched_rule = %q, want badword", m.Canonical)
	}
}

func TestStreamGuard_BoundaryOneRunePerDelta(t *testing.T) {
	// 8.3-BLIND-BOUNDARY-003 | P1 | unit | BOUNDARY-002
	g := badwordGuard(t)
	deltas := strings.Split("badword", "")
	_, idx := observeAll(g, deltas)
	if idx != len(deltas)-1 {
		t.Fatalf("one-rune-per-delta term detected at %d, want the final rune (%d)", idx, len(deltas)-1)
	}
}

func TestStreamGuard_BoundaryLongestTermMaximallySplit(t *testing.T) {
	// 8.3-BLIND-BOUNDARY-004 | P1 | unit | BOUNDARY-003
	longTerm := strings.Repeat("q", 50)
	lex := lexiconWith(t, enRow(longTerm, safetylexicon.CategoryOther, safetylexicon.SeverityLow, 4006))
	g := NewStreamGuard(NewScanner(lex))
	_, idx := observeAll(g, strings.Split(longTerm, ""))
	if idx != len(longTerm)-1 {
		t.Fatalf("maximally-split longest term detected at %d, want %d (window floor must cover it)", idx, len(longTerm)-1)
	}
}

func TestStreamGuard_NotSharedAcrossGoroutines(t *testing.T) {
	// 8.3-BLIND-CONCURRENCY-001 | P0 | unit (-race) | CONCURRENCY-002
	// N goroutines, EACH its OWN guard but a SHARED *Scanner. Must be -race clean;
	// per-request guards isolate the only mutable state.
	scanner := NewScanner(lexiconWith(t, enRow("badword", safetylexicon.CategoryAbuse, safetylexicon.SeverityHigh, 4007)))
	const N = 50
	var wg sync.WaitGroup
	for i := 0; i < N; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			g := NewStreamGuard(scanner)
			if i%2 == 0 {
				if _, hit := observeAll(g, []string{"clean ", fmt.Sprintf("text-%d ", i), "bad", "word"}); hit == -1 {
					t.Errorf("goroutine %d: expected hit on its own stream", i)
				}
			} else {
				if _, hit := observeAll(g, []string{"all ", "clean ", "here ", fmt.Sprintf("%d", i)}); hit != -1 {
					t.Errorf("goroutine %d: unexpected hit on a clean stream", i)
				}
			}
		}(i)
	}
	wg.Wait()
}
