apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-svc.fullname" . }}
  labels:
    {{- include "auth-svc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "auth-svc.selectorLabels" . | nindent 4 }}
